### PR TITLE
Treat an exception as an assertion failure and always add it to the assertion list.

### LINKED ISSUE #4537: AssertException in TearDown hides Exception in Test
I know from other comments in issues that it is not recommended to do Assertions during TearDown. Nevertheless, I want to report the following to check if it is a known issue/by design or a bug.

Simple code example to demonstrate the issue:
```csharp
using NUnit.Framework;

namespace DemoTests; 

public class TearDownTests {
    [Test]
    public void Assertion() {
        Assert.IsTrue(false);
    }

    [Test]
    public void Exception() {
        throw new Exception("Test exception");
    }

    [Test]
    public void Pass() {
        
    }

    [TearDown]
    public void TearDown() {
        Assert.Warn("Warning");
    }
}
```

Result:

- Assertion() tests shows both failures and warnings
- Pass() shows Warning from TearDown
- Exception() only shows Warning and hides/forgets/overrides the Exception

This happens with any AssertException in TearDown. Of course, when I catch the exception and "rethrough" it using something like Assert.Fail(ex.Message), I see both failures as in Assertion() tests, but for me it is one of the big advantages of NUnit that I don't need to catch all my exceptions to let a test fail but that it fails automatically.

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #4537 

There is a change in `RepeatAttribute` behaviour:

1. If an exception is thrown and `StopOnFailure` is false, the test continues executing.
2. Test result are reset between runs. So if the last run passes, the test succeeds. Previously it would fail.

The above are side effects of #4861 and only affect the code when `StopOnFailure` is set to false.

### CODE REVIEW

File: src/NUnitFramework/framework/Attributes/RepeatAttribute.cs [hunk 1]
```diff
@@ -94,18 +94,33 @@ public override TestResult Execute(TestExecutionContext context)
...
-                    context.CurrentResult = innerCommand.Execute(context);
+                    try
+                    {
+                        context.CurrentResult = innerCommand.Execute(context);
+                    }
+                    // Commands are supposed to catch exceptions, but some don't
+                    // and we want to look at restructuring the API in the future.
+                    catch (Exception ex)
+                    {
+                        if (context.CurrentResult is null)
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Attributes/RepeatAttribute.cs:105]: CurrentResult is declared as non-nullable.
But TestExecutionContext doesn't explicitly set this to non-null.
Also see the comment on l.52 workitem.cs.  So, perhaps just accept this.......

File: src/NUnitFramework/framework/Interfaces/AssertionResult.cs [hunk 2]
```diff
@@ -14,12 +14,24 @@ public class AssertionResult : IEquatable<AssertionResult>
...
+        public AssertionResult(FailureSite site, AssertionStatus status, string message, string? stackTrace)
+        {
+            Site = site;
             Status = status;
             Message = message;
             StackTrace = stackTrace;
         }
 
+        /// <summary> Where did the failure occur.</summary>
+        public FailureSite Site;
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Interfaces/AssertionResult.cs:33]:
```suggestion
        public FailureSite Site { get; }
```

File: src/NUnitFramework/framework/Internal/Commands/OneTimeTearDownCommand.cs [hunk 3]
```diff
@@ -22,19 +20,7 @@ public OneTimeTearDownCommand(TestCommand innerCommand, SetUpTearDownItem setUpT
...
-            {
-                TestResult suiteResult = context.CurrentResult;
-
-                try
-                {
-                    setUpTearDownItem.RunTearDown(context);
-                }
-                catch (Exception ex)
-                {
-                    suiteResult.RecordTearDownException(ex);
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Internal/Commands/OneTimeTearDownCommand.cs:35]: Why should not this be run?

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 4]
```diff
@@ -480,23 +471,54 @@ public void RecordException(Exception ex, FailureSite site)
...
+        public void RecordException(Exception ex, FailureSite site)
+        {
+            var result = new ExceptionResult(ex, site);
 
-            ResultState resultState = ResultState == ResultState.Cancelled
-                ? ResultState.Cancelled
-                : ResultState.Error;
-            if (Test.IsSuite)
-                resultState = resultState.WithSite(FailureSite.TearDown);
+            if (ex is NUnitException nUnitException && nUnitException.InnerException is ResultStateException ||
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs:486]:
```suggestion
          if (ex is NUnitException { InnerException: ResultStateException } or ResultStateException)
```

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 5]
```diff
@@ -480,23 +471,54 @@ public void RecordException(Exception ex, FailureSite site)
...
+                ex is ResultStateException)
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs:487]:
```suggestion
              
```

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 6]
```diff
@@ -676,6 +703,27 @@ private ResultState AssertionStatusToResultState(AssertionStatus status)
             }
         }
 
+        private AssertionStatus ResultStateToAssertionStatus(ResultState resultState)
+        {
+            if (resultState.Status == TestStatus.Failed)
+            {
+                if (resultState.Label == ResultState.Error.Label)
+                    return AssertionStatus.Error;
+                else if (resultState.Label == ResultState.Failure.Label)
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs:712]:
```suggestion
                if (resultState.Label == ResultState.Failure.Label)
```

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 7]
```diff
@@ -676,6 +703,27 @@ private ResultState AssertionStatusToResultState(AssertionStatus status)
             }
         }
 
+        private AssertionStatus ResultStateToAssertionStatus(ResultState resultState)
+        {
+            if (resultState.Status == TestStatus.Failed)
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs:708]: Could perhaps be a switch statement

**Review by OsirisTerje — CHANGES_REQUESTED** [review]
Just commented on some smaller coding stuff.  
The change seems to hit  rather large, but seems to be well covered by the tests.

File: src/NUnitFramework/framework/Interfaces/AssertionResult.cs (hunk 2 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Interfaces/AssertionResult.cs:33]: Yes, thanks.

File: src/NUnitFramework/framework/Internal/Commands/OneTimeTearDownCommand.cs (hunk 3 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Commands/OneTimeTearDownCommand.cs:35]: Because the exceptions are already caught in the `RunTearDown` method hence it would never get into the `catch` part.

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs (hunk 5 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs:487]: If the user executes `Assert.Fail/Ignore/Success` in a SetUp or TearDown it will get here with a (derived) `ResultStateException`

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs (hunk 6 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs:712]: ok.

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs (hunk 7 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs:708]: ok

File: src/NUnitFramework/framework/Attributes/RepeatAttribute.cs (hunk 1 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Attributes/RepeatAttribute.cs:105]: TestExecutionContext its properties is fake nullable. With a TODO:
```csharp
// TODO: Fix design where properties are not set at unknown times.

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
```

It is literally copied from `RetryCommand.Execute`.
Looking at the code above, it assigns the result of the command to `context.CurrentResult`.
If the command fails, it is not assigned, unless it is assigned somewhere else previously which we cannot guarantee.

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs (hunk 4 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs:486]: Not used to the fancy nested pattern, but I like it.

**Review by OsirisTerje — APPROVED** [review]
