### PR TITLE
Catch exceptions preventing return of awaitable object

### LINKED ISSUE #3138: Assert.Ignore breaks when a Task is returned w/o using async/await
Writing a test that invokes `Assert.Ignore()` and it fails with the following exception:

<details><summary>Stacktrace</summary>

```
NUnit.Framework.Internal.NUnitException : Rethrown
  ----> NUnit.Framework.IgnoreException : should not run
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 281
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 77
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 84
--IgnoreException
   at NUnit.Framework.Assert.Ignore(String message, Object[] args) in C:\src\nunit\nunit\src\NUnitFramework\framework\Assert.cs:line 214
   at TestNUnit.Class1.Failing() in C:\Users\Sean\Desktop\TestNUnit\TestNUnit\Class1.cs:line 16
```
</details>
<br>

The failing test looks as the following:

```c#
        [Test]
        public Task Failing()
        {
            Assert.Ignore("should not run");

            return Task.FromResult(1);
        }
```

Changing the test to include the `async` keyword with `await` fixes this test:

```c#
        [Test]
        public async Task Working()
        {
            Assert.Ignore("should not run");

            await Task.FromResult(1);
        }
```

This fails with NUnit 3.11.0, but works with earlier versions.
Tested with .NET Framework 4.5.2

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #3138.

The problem was was an NUnitException with an InnerException of _another_ NUnitException with an InnerException of a Success/Ignore/InconclusiveException. `ValidateAndUnwrap` only unwraps one level, so `if (ex is ResultStateException)` never happens because the ResultStateException it's trying to find is actually `ex.InnerException` at that point.

https://github.com/nunit/nunit/blob/b5c1d549938476ff06f118557b29778b36593549/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L578-L585

https://github.com/nunit/nunit/blob/b5c1d549938476ff06f118557b29778b36593549/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L560-L568

The problem was caused in https://github.com/nunit/nunit/commit/b83f556cc41b3c12a6e1a7729d1e05e5e140f252#diff-6325ab2a4b2ce8d3a6fd52a0f58f75f5L98 by me keeping the `catch` block but failing to notice that it used to only apply to the `WaitForPendingOperationsToComplete` part and not the `Reflect.InvokeMethod` part which already wraps.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs [hunk 1]
```diff
@@ -79,14 +79,7 @@ private object RunTestMethod(TestExecutionContext context)
 #if ASYNC
             if (AsyncToSyncAdapter.IsAsyncOperation(testMethod.Method.MethodInfo))
             {
-                try
-                {
-                    return AsyncToSyncAdapter.Await(() => InvokeTestMethod(context));
-                }
-                catch (Exception e)
-                {
-                    throw new NUnitException("Rethrown", e);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs]: I'd like to deprecate `NUnitException` entirely in the future.

**Comment by jnm2** [comment]
Build failure is unrelated. See https://github.com/nunit/nunit/issues/3156.

File: src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs (hunk 1 above)
Comment (mikkelbu) [reply src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs]: So not wrapping the exception in a `NUnitException` solves the problem?
(Actually, I got most information from the title of the second commit `Fix twice-wrapped NUnitException to fix Assert.Pass, Ignore, and Inconclusive in non-async Task-returning methods` 😄).

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs]: NUnitException is an implementation detail that's never supposed to escape from the framework, so there shouldn't be anything to deprecate.

It was used internally to indicate that the wrapped exception has special meaning for NUnit and shouldn't be handled as an exception. It's predecessor in V2 was used more heavily than it is today so you could phase it out of the implementation, but there doesn't seem to be a lot of benefit in putting effort into removing it.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs]: @mikkelbu Correct. It was an NUnitException with an InnerException of an NUnitException with the InnerException of the Success/Ignore/InconclusiveException. `ValidateAndUnwrap` only unwraps one level, so `if (ex is ResultStateException)` fails because the ResultStateException is actually `ex.InnerException` at that point.

https://github.com/nunit/nunit/blob/b5c1d549938476ff06f118557b29778b36593549/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L578-L585

https://github.com/nunit/nunit/blob/b5c1d549938476ff06f118557b29778b36593549/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L560-L568

The problem was caused in https://github.com/nunit/nunit/commit/b83f556cc41b3c12a6e1a7729d1e05e5e140f252#diff-6325ab2a4b2ce8d3a6fd52a0f58f75f5L98 by me keeping the `catch` block but failing to notice that it used to only apply to the `WaitForPendingOperationsToComplete` part and not the `Reflect.InvokeMethod` part which already wraps.

**Comment by jnm2** [comment]
Rebuilt the PR, and all checks now pass.

File: src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs (hunk 1 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs]: @mikkelbu I moved the explanation to the PR body. Is there anything else I can clarify?
