### PR TITLE
Fix exception message formatting for Assert.Multiple

### LINKED ISSUE #3302: Incorrect formatting of failure message if test fails with Assert.Multiple
```csharp
Assert.Multiple(() =>
            {
                Assert.AreEqual(2, 3, "The first failed assert");
                Assert.AreEqual(4, 5, "The second failed assert");
                throw new Exception("And exception and the end.");
            });
```

XML report contains failure message with missing whitespace:
image

### PR DESCRIPTION
**Pull request by nvborisenko**
This PR fixes #3302.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 1]
```diff
@@ -511,7 +511,7 @@ public void RecordException(Exception ex)
             if (AssertionResults.Count > 0 && result.ResultState == ResultState.Error)
             {
                 // Add pending failures to the legacy result message
-                Message += CreateLegacyFailureMessage();
+                Message += " " + CreateLegacyFailureMessage();
```
Comment (CharliePoole) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs]: See my comment on the issue. This is obviously better than what we have, but I'm not sure it's enough.

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs]: I agree with @ChrisMaddock that the simpler fix is best. Personally, I'd expect to see the legacy failure message under the original message with a blank line separating, i.e. 2 newlines rather than a space added.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs]: I would like to see two newlines as well.
