### PR TITLE
Fix spurious kill failure

### LINKED ISSUE #2398: NUnit CI spurious failures, NUnit.Framework.Internal.ThreadUtilityTests.Kill
Too frequently I see NUnit's CI fail due to the below failure:
>1) Failed : NUnit.Framework.Internal.ThreadUtilityTests.Kill
  Native message pump was not able to be interrupted to enable a managed thread abort.
  Expected: True
  But was:  False
   at NUnit.Framework.Internal.ThreadUtilityTests.AbortOrKillThreadWithMessagePump(Boolean kill)

as seen [here](https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-ci-04352-pr-2379#L1233).

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2398 

So what I'm measuring is that when the CPU is under load, timers get around ten times slower to execute callbacks. Can't think of any mitigations for CPU load except a sufficiently long timeout. When the CPU is under load, what else is there?
We don't ever expect failures from this test, so how long can you tolerate waiting for results from CI? I say we make this a 15 second timeout and reopen #2398 if it comes back. Sound good?

### CODE REVIEW

**Comment by jnm2** [comment]
@rprouse Wheeler says he's seeing this in many CI failures so this may stabilize things.

File: src/NUnitFramework/tests/Internal/ThreadUtilityTests.cs [hunk 1]
```diff
@@ -33,10 +34,28 @@ public void AbortOrKillThreadWithMessagePump(bool kill)
...
+                // All this number does is manage how long we can tolerate waiting for a build if a bug
+                // is introduced and the thread never aborts.
+                const int waitTime = 15000;
+
+                Assert.That(thread.Join(waitTime), "Native message pump was not able to be interrupted to enable a managed thread abort.");
             }
         }
 
+        [Platform("Win")]
+        [Test, Explicit("For diagnostic purposes; slow")]
```
Comment (CharliePoole) [inline src/NUnitFramework/tests/Internal/ThreadUtilityTests.cs]: I'm OK with this being here so long as it's explicit. I'd actually prefer it to move to our integration tests, whenever we set some up in a separate repo. I may end up creating something.

File: src/NUnitFramework/tests/TestUtilities/StressUtility.cs [hunk 2]
```diff
@@ -0,0 +1,102 @@
+﻿using System;
```
Comment (mikkelbu) [inline src/NUnitFramework/tests/TestUtilities/StressUtility.cs]: We have forgot a copyright notice here

Comment (jnm2) [reply src/NUnitFramework/tests/TestUtilities/StressUtility.cs]: Oh, thank you!

**Comment by jnm2** [comment]
Updated with headers.
