### PR TITLE
Handle Exceptions thrown during discovery, such as in Custom Attributes

### LINKED ISSUE #4096: NUnit.Framework 3.13.2 introduced a breaking change that conceals problems with tests
Before NUnit.Framework 3.13.2 running an assembly compiled from the following code 

```
[TestFixture]
public class BrokenTestClass
{
  [Test, Invalid] public void Test() { }
}

public class InvalidAttribute : Attribute
{
  public InvalidAttribute() => throw new InvalidProgramException();
}
```
would issue the `An exception was thrown while loading the test` twice:
 - once inside the xml returned from `ITestEventListener.Explore`,
 - and the second time inside a `<test-suite type="TestFixture" ... />` event for `NUnit.Engine.ITestEventListener`.

The new behavior broke R#/Rider test runner in that a broken test class no longer gets a clear indication of a problem, marking such test as inconclusive instead.

More importantly, the new behavior broke NUnit's own runner in that it no longer reports such errors, making problems of this nature very difficult to notice. For this reason over a 1000 tests weren't running in our CI over a past week without us knowing.

Below is the output of `nunit3-console` running an assembly with broken tests:
```
Copyright (c) 2022 Charlie Poole, Rob Prouse
Wednesday, April 13, 2022 3:49:53 PM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    c:\Users\jetbrains\source\repos\Tests.Sandbox\Sandbox.NUnit3\bin\Debug\net35\Sandbox.NUnit3.dll


Run Settings
    DisposeRunners: True
    WorkDirectory: C:\Users\jetbrains\Documents\59\bin\net35
    ImageRuntimeVersion: 2.0.50727
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    TargetRuntimeFramework: net-2.0
    NumberOfTestWorkers: 16

Test Run Summary
  Overall result: Passed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2022-04-13 13:49:53Z
    End time: 2022-04-13 13:49:53Z
    Duration: 0.510 seconds

Results (nunit3) saved as TestResult.xml
```

### LINKED ISSUE #4107: Incorrect type specified for Values attribute fails unrelated tests
With the following tests in test container, I expect one test to pass, and another to fail because of the incorrect type of the variable with ValuesAttribute.
```
    [Test]
    public void ThisOnePasses()
    {
    }

    [Test]
    public void ThisOneFails([Values("apple")] int value)
    {
    }
```

For the different NUnit package versions, behaviour is different.

3.10.0 - console message is ok, test report is correct.

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  nunit-sample -> /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll
Test run for /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed ThisOneFails("apple") [15 ms]
  Error Message:
   System.ArgumentException : Object of type 'System.String' cannot be converted to type 'System.Int32'.
  Stack Trace:
     at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)

Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration:  - /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (net6.0)
```

3.13.1 - console message is ok, test report is incorrect (no test actually run).
```
  Determining projects to restore...
  All projects are up-to-date for restore.
  nunit-sample -> /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll
Test run for /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Setup failed for test fixture nunit_sample.Tests
An exception was thrown while loading the test.
System.ArgumentException: apple is not a valid value for Int32. (Parameter 'value')
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at NUnit.Framework.Internal.ParamAttributeTypeConversions.TryConvert(Object value, Type targetType, Object& convertedValue)
   at NUnit.Framework.Internal.ParamAttributeTypeConversions.GetData(Object[] data, Type targetType)
   at NUnit.Framework.Internal.ParamAttributeTypeConversions.ConvertData(Object[] data, Type targetType)
   at NUnit.Framework.ValuesAttribute.GetData(IParameterInfo parameter)
   at NUnit.Framework.Internal.Builders.ParameterDataSourceProvider.GetDataFor(IParameterInfo parameter)
   at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite)
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase(IMethodInfo method, TestSuite suite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
No test is available in /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

3.13.2, 3.13.3 - console message is misleading, test report is incorrect (no test actually run).

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  nunit-sample -> /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll
Test run for /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #4096 
Fixes #4107

Tests with Exceptions are Marked As Invalid and show up as an Error.
Fixtures with Exceptions are non-runnable and don't show up with `dotnet test`.

One alternative option would be to make a special fixture with one runable method that fails.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs [hunk 1]
```diff
@@ -114,11 +114,9 @@ public TestSuite BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
             }
             catch (Exception ex)
             {
-                var fixture = new TestFixture(typeInfo);
```
Comment (manfred-brands) [inline src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs:117]: This call throws again, defeating the catching above.
Therefore I added a new constructor that create an invalid fixture.

Comment (stevenaw) [reply src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs:117]: Hm. It says I marked this as resolved, but I have no recollection of doing that 🤔

File: src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs [hunk 2]
```diff
@@ -105,36 +106,45 @@ public Test BuildFrom(IMethodInfo method, Test? parentSuite)
...
+                return builders.Count > 0 && method.GetParameters().Length > 0 || tests.Count > 0
+                    ? BuildParameterizedMethodSuite(method, tests)
+                    : BuildSingleTestMethod(method, parentSuite);
+            }
+            catch (Exception ex)
             {
-                foreach (var test in attr.BuildFrom(method, parentSuite))
-                    tests.Add(test);
+                var testMethod = new TestMethod(method, parentSuite);
+                testMethod.MakeInvalid("An exception was thrown while loading the test." + Environment.NewLine + ex.ToString());
```
Comment (stevenaw) [inline src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs:133]: nitpick/question: For both `TestMethod` and `TestFixture` in the file above, this method is defined on a base class, `Test`. `Test.MakeInvalid` currently only has one overload, which takes a string. Is it worth adding another which can take in both a string and an Exception?

```csharp
public abstract class Test {
  // Should this overload be public or internal? Not sure
  public void MakeInvalid(string reason, Exception ex) {
    // Something happens here, probably just building the message from "reason" and "ex"
  }
}
```
 It seems like we have to handle this scenario a few times within this PR

File: src/NUnitFramework/testdata/AttributeThrowingExceptionFixture.cs [hunk 3]
```diff
@@ -0,0 +1,87 @@
+// ***********************************************************************
```
Comment (stevenaw) [inline src/NUnitFramework/testdata/AttributeThrowingExceptionFixture.cs:1]: Even though the new file template hasn't been updated in the 3.13 branch, I think we've started using the new condensed file header for any new files in this branch too, to simplify when porting things to 4.0.
It should be copyable from another newer file, like `ArrayHelper`

https://github.com/nunit/nunit/blob/v3.13-dev/src/NUnitFramework/framework/Internal/ArrayHelper.cs#L1

**Review by stevenaw — APPROVED** [review]
Thanks @manfred-brands ! Great that this could be fixed so simply.
Two minor nitpicks/ suggestions. I also would appreciate a second review from someone else

File: src/NUnitFramework/testdata/AttributeThrowingExceptionFixture.cs (hunk 3 above)
Comment (manfred-brands) [reply src/NUnitFramework/testdata/AttributeThrowingExceptionFixture.cs:1]: I wasn't sure what the procedure was for adding files to v3. Updated the headers.

File: src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs (hunk 2 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs]: Overload added.
Also split the StackTrace from the Message, setting separate StackTrace property.
Updated test.

**Comment by manfred-brands** [comment]
Thanks @stevenaw, changes made.

**Comment by stevenaw** [comment]
Very cool, thanks @manfred-brands ! Looks great to me 👍

**Comment by manfred-brands** [comment]
Is there anything blocking this from being merged in?

**Comment by stevenaw** [comment]
@manfred-brands I'd been hoping to get a second pair of eyes on it since this is a part of the codebase I'm less familiar with, but perhaps it could also be merged as-is.
@mikkelbu @rprouse are either of you available to do a review?

**Review by rprouse — APPROVED** [review]
Sorry for the delay. This looks good. For anyone else reviewing, ignore whitespace, it is much easier to read.

File: src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs [hunk 4]
```diff
@@ -105,36 +106,45 @@ public Test BuildFrom(IMethodInfo method, Test? parentSuite)
...
-        /// </summary>
-        /// <param name="method">The method for which a test is to be built.</param>
-        /// <param name="tests">The list of test cases to include.</param>
-        private Test BuildParameterizedMethodSuite(IMethodInfo method, IEnumerable<TestMethod> tests)
+/// <summary>
+/// Builds a ParameterizedMethodSuite containing individual test cases.
+/// </summary>
+/// <param name="method">The method for which a test is to be built.</param>
+/// <param name="tests">The list of test cases to include.</param>
+private Test BuildParameterizedMethodSuite(IMethodInfo method, IEnumerable<TestMethod> tests)
```
[the remark this answers is not in the document]
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs:147]: Thanks @mikkelbu. I completely agree, this was accidentally and when looking in gitextensions with ignore spaces, it doesn't show up!

**Comment by manfred-brands** [comment]
Cherry pick into master depends on #4053

**Comment by manfred-brands** [comment]
This is ready for merge into v3.13-dev now.

**Comment by stevenaw** [comment]
Thanks @manfred-brands ! LGTM 🎉
