### PR TITLE
Performance improvements comparing equivalence of large collections

### LINKED ISSUE #2598: Is.Not.EquivalentTo is extremely slow
Just updated my tests from NUnit 2.4.8 to 3.9.0 and noticed that tests have started running too long.
And here is a synthetic test with allows me to reproduce the problem:

> [Test]
> public void TestEquivalent()
> {
> 	byte[] data = new byte[0x80000 + 7];
> 	byte[] encrypted = new byte[0x80000 + 7];
> 	encrypted[0] = 2;
> 	encrypted[1] = 3;
> 
> 	var watch = Stopwatch.StartNew();
> 	Assert.That(encrypted, Is.Not.EquivalentTo(data));
> 	watch.Stop();
> 	Debug.WriteLine($"Takes: {watch.ElapsedMilliseconds} milliseconds");
> }
> 

It used to work fast (with version 2.4.8), but now it takes 123116 milliseconds to run on my computer. In real test when two arrays contain completely different values, it takes about 22 minutes to run. Any idea why is it so?

### LINKED ISSUE #2799: CollectionAssert.AreEquivalent is extremely slow
```csharp
var lines1 = new List<string> { };
var lines2 = new List<string> { };

for (int i = 0; i < 10000; i++)
{
  lines1.Add(i.ToString());
  lines2.Add(i.ToString());
}

CollectionAssert.AreEquivalent(lines1, lines2);
```

Verification of 10000 string elements takes 10 seconds. Verification of 100k elements may take more than 30 minutes (cannot wait until it finishes). This behavior takes a place in NUnit **3.10** and not reproducible in **3.9**

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #2799
See #2598 and #3825

When comparing equivalence of large collections, we found that removing from the end of a collection is faster to fix #2598, but this makes comparing two collections in the same order O(n^2).

This PR maintains that fix, but sorts the collections if possible to keep the time as close to O(n) as possible.

For this to work, the types in the collection must implement `IComparable` and the collection must be strongly typed so that we know that every item in the collection is the same type.

I do not use `IComparable<T>` and sort using `IList<T>.Sort()` because it is difficult to get an `IEnumerable` into an `IList<T>`. I took the easy route and use `ArrayList.Sort()`.

### CODE REVIEW

File: src/NUnitFramework/framework/Constraints/Numerics.cs [hunk 1]
```diff
@@ -39,6 +39,7 @@ public static bool IsFloatingPointNumeric(Object obj)
             {
                 if (obj is System.Double) return true;
                 if (obj is System.Single) return true;
+                if (obj is System.Decimal) return true;
```
Comment (rprouse) [inline src/NUnitFramework/framework/Constraints/Numerics.cs:42]: Unrelated. I was using `IsNumeric` originally and noticed that we missed this.

File: src/NUnitFramework/framework/Constraints/CollectionTally.cs [hunk 2]
```diff
@@ -28,18 +29,33 @@ public CollectionTallyResult(List<object> missingItems, List<object> extraItems)
...
-                    new List<object>(_missingItems),
-                    new List<object>(_extraItems));
+                var missingItems = new List<object>(_missingItems.Count);
+                foreach (var o in _missingItems)
+                    missingItems.Add(o);
+
+                List<object> extraItems = new List<object>();
+                if(_sorted)
+                {
+                    for (int index = _extraItems.Count - 1; index >= 0; index--)
```
Comment (rprouse) [inline src/NUnitFramework/framework/Constraints/CollectionTally.cs:46]: All of the extra backwards iterations of collections is extra complexity but the only way I could not revert the performance gains @mikkelbu made fixing #2598

File: src/NUnitFramework/framework/Internal/Extensions/IEnumerableExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+namespace NUnit.Framework.Internal.Extensions
+{
+    internal static class IEnumerableExtensions
+    {
+        public static bool IsSortable(this IEnumerable collection)
+        {
+            if (collection is null)
+                return false;
+
+            if (collection is StringCollection)
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Extensions/IEnumerableExtensions.cs:16]: I think this is the only non-generic built in collection that is strongly typed?

File: src/NUnitFramework/tests/Constraints/CollectionEqualsTests.cs [hunk 4]
```diff
@@ -41,6 +41,15 @@ public void CanMatchAnArrayWithACollection()
             Assert.That(array, Is.EqualTo(collection));
         }
 
+        [Test]
+        public void CollectionsInDifferentOrderArNotEqual()
+        {
+            IList expected = new List<int> { 1, 2, 3 };
+            IList actual = new List<int> { 3, 2, 1 };
+
+            Assert.That(actual, Is.Not.EqualTo(expected));
```
Comment (rprouse) [inline src/NUnitFramework/tests/Constraints/CollectionEqualsTests.cs:50]: Just checking that sorting did not change behaviour.

File: src/NUnitFramework/framework/Constraints/CollectionTally.cs [hunk 5]
```diff
@@ -28,18 +29,33 @@ public CollectionTallyResult(List<object> missingItems, List<object> extraItems)
...
+                {
+                    extraItems.AddRange(_extraItems);
+                }
+
+                return new CollectionTallyResult(missingItems, extraItems);
             }
         }
 
-        private readonly List<object> _missingItems = new List<object>();
+        private readonly ArrayList _missingItems = new ArrayList();
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Constraints/CollectionTally.cs:58]: Why this change

File: src/NUnitFramework/framework/Constraints/CollectionTally.cs [hunk 6]
```diff
@@ -28,18 +29,33 @@ public CollectionTallyResult(List<object> missingItems, List<object> extraItems)
...
         public CollectionTallyResult Result
         {
             get
             {
-                return new CollectionTallyResult(
-                    new List<object>(_missingItems),
-                    new List<object>(_extraItems));
+                var missingItems = new List<object>(_missingItems.Count);
+                foreach (var o in _missingItems)
+                    missingItems.Add(o);
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Constraints/CollectionTally.cs:41]: Couldn't this be `missingItems.AddRange(_missingItems);` ?

File: src/NUnitFramework/framework/Constraints/CollectionTally.cs [hunk 7]
```diff
@@ -28,18 +29,33 @@ public CollectionTallyResult(List<object> missingItems, List<object> extraItems)
...
+
+                List<object> extraItems = new List<object>();
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Constraints/CollectionTally.cs:43]:
```suggestion
                List<object> extraItems = new List<object>(_extraItems.Count);
```

**Review by mikkelbu — APPROVED** [review]
LGTM and definitely an improvement

File: src/NUnitFramework/framework/Constraints/CollectionTally.cs (hunk 5 above)
Comment (mikkelbu) [reply src/NUnitFramework/framework/Constraints/CollectionTally.cs:58]: I should have read the description before reviewing

> I do not use IComparable<T> and sort using IList<T>.Sort() because it is difficult to get an IEnumerable into an IList<T>. I took the easy route and use ArrayList.Sort().

File: src/NUnitFramework/framework/Constraints/CollectionTally.cs (hunk 6 above)
Comment (mikkelbu) [reply src/NUnitFramework/framework/Constraints/CollectionTally.cs:41]: Probably not, since `_missingItems` is an `ArrayList`
