### PR TITLE
#2798 - Show actual count on Has.Exactly(x).Items

### LINKED ISSUE #2798: [Request] Show actual count value when test fail on Has.Exactly(x).Items
When I test that a enumeration have the correct count of members, so it do it with

```csharp
    /// <summary>
    /// Represents a PCAN filter mode
    /// </summary>
    public enum PeakCanMode : byte
    {
        /// <summary>
        /// Mode is Standard (11-bit identifier)
        /// </summary>
        PcanModeStandard = 0x_00,

        /// <summary>
        /// Mode is Extended (29-bit identifier)
        /// </summary>
        PcanModeExtended = 0x_02
    }
```

```csharp
      ///<summary>
      /// Test that the enumeration have the correct count of elements
      ///</summary>
      [Test]
      [Description("Test that the enumeration have the correct count of members")]
      public void HaveTheCorrectMemberCount()
          => Assert.That(Enum.GetNames(typeof(PeakCanMode)), Has.Exactly(3).Items);
```

When the count is wrong i get
> Meldung:   Expected: exactly 3 items
>   But was:  < "PcanModeStandard", "PcanModeExtended" >

but it would be nicer, when I would get
> Meldung:   Expected: exactly 3 items
>   But was:  actual 2 items < "PcanModeStandard", "PcanModeExtended" >

Yes I know, I can add a extra message as error description with the count, but i think it would be nicer
```csharp
      ///<summary>
      /// Test that the enumeration have the correct count of elements
      ///</summary>
      [Test]
      [Description("Test that the enumeration have the correct count of members")]
      public void HaveTheCorrectMemberCount()
          => Assert.That(Enum.GetNames(typeof(PeakCanMode)),
                         Has.Exactly(3).Items);
                         $"Actual {Enum.GetNames(typeof(EsaDeviceCommand)).Length} items");

```

### PR DESCRIPTION
**Pull request by TobiasSekan**
Fixes #2798

### CODE REVIEW

**Comment by mikkelbu** [comment]
Hi @TobiasSekan. I've just edited your description such that this PR auto-closes #2798 when it is merged to master.

File: src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs [hunk 1]
```diff
@@ -296,6 +294,18 @@ private void WriteExpectedLine(object expected, Tolerance tolerance)
         private void WriteActualLine(ConstraintResult result)
         {
             Write(Pfx_Actual);
+
+            // Write the actual item count, when ActualValue is a collection
+            if (result.Name == "ExactCount" && result.ActualValue is IEnumerable)
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs]: So that every possible constraint doesn't end up putting code in this shared location, we use custom constraint results for this type of thing. In other words, you'd create a private sealed class `ExactCountConstraint.ExactCountConstraintResult`, override `WriteActualValueTo`, and use it [here](https://github.com/nunit/nunit/blob/d411123f1c705cc7ad147c67d2420d97b0706626/src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs#L86). Have you tried that?

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs]: @TobiasSekan Emphasizing @jnm2 's point...

`TextMessageWriter` knows how to put out a message in text form based on what the constraint asked to have done. Constraints know what the `IMessageWriter` interface can do and call the appropriate methods. The message writer doesn't know anything about constraints and shouldn't. It only varies what is put out based on the particular type of output. So, a hypothetical `HtmlMessageWriter` would put put different characters for the same call from what a `TextMessageWriter` does.

A constraint, like `ExactCountConstraint` decides what it's output will look like. If you examine constraint code in NUnit, you will see that many different kinds of output are produced. Some constraints do this by direct use of the message writer, while others do it by creating a custom constraint result, as suggested by @jnm2. A custom result is needed when the output is significantly different from the standard or particularly complex.

I suggest you look at the code for various constraints, especially those that output lists of collection elements to see how we do it and modify the `ExactCountConstraint` output, leaving `TextMessageWriter` as it is.

**Comment by TobiasSekan** [comment]
Hello,

I haven't notice this, I have search for a possibility to override the result, but I have only found the `Display` setter.

I currently not happy with the for-loop over the array object, but I have not idea for a better solution to count the element inside a none generic `IEnumerable`

File: src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs [hunk 2]
```diff
@@ -102,6 +101,8 @@ public override string Description
                 return _itemConstraint != null ? PrefixConstraint.FormatDescription(descriptionPrefix, _itemConstraint) : descriptionPrefix;
             }
         }
+
+
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs]: Would you please remove these blank lines? (A habit I've gotten into is to view the diff before I commit so that I don't accidentally add things like this.)

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+        /// </summary>
+        /// <param name="writer">The writer on which the actual value is displayed</param>
+        public override void WriteActualValueTo(MessageWriter writer)
+        {
+            var elementList = _actualValue as IEnumerable;
+            if (elementList == null)
+            {
+                writer.Write("no items");
+                return;
+            }
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: One benefit of making this class private nested is that you would then have an absolute guarantee that `_actualValue` is an instance of `IEnumerable`. If you keep the class internal, I'd ask that you put `ConstraintUtils.RequireActual<IEnumerable>(actualValue, nameof(actualValue));` in the *constructor*.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+{
+    /// <summary>
+    /// Contain the result of matching a <see cref="ExactCountConstraint"/> against an actual value.
+    /// </summary>
+    public sealed class ExactCountConstraintResult : ConstraintResult
+    {
+        /// <summary>
+        /// The actual value to which the Constraint was applied.
+        /// </summary>
+        private readonly object _actualValue;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: Redundant since the base constructor sets the `ActualValue` property to the same value.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+                writer.Write("no items");
+                return;
+            }
+
+            var writeCounter  = 0;
+            var stringBuilder = new StringBuilder();
+
+            stringBuilder.AppendFormat(itemCounter > 1 ? "{0} items <" : "{0} item <", itemCounter);
+
+            foreach (var element in (IEnumerable)_actualValue)
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: Maybe use `elementList` instead of a second cast?

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+            }
+
+            if (itemCounter == 0)
+            {
+                writer.Write("no items");
+                return;
+            }
+
+            var writeCounter  = 0;
+            var stringBuilder = new StringBuilder();
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: It's more efficient and simpler code to read if you write directly to the writer (which may already be wrapping a StringBuilder) than to start a buffer here.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+
+            stringBuilder.AppendFormat(itemCounter > 1 ? "{0} items <" : "{0} item <", itemCounter);
+
+            foreach (var element in (IEnumerable)_actualValue)
+            {
+                writeCounter++;
+                stringBuilder.AppendFormat(writeCounter != itemCounter ? " \"{0}\"," : " \"{0}\" >", element);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: It's more efficient and simpler code to read if you write directly to the writer (which is already doing its own buffering) than to introduce the string builder. This should be `writer.Write(format, element);`.

**Comment by jnm2** [comment]
> I currently not happy with the for-loop over the array object, but I have not idea for a better solution to count the element inside a none generic IEnumerable

If you're not happy, you *could* add `using System.Linq;` and use `enumerable.Cast<object>().Count()`. That has the optimization of using `ICollection<>.Count` if available, too, so it's both simpler and faster.
However, the loop as you have it is also fine with me.

File: src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs [hunk 8]
```diff
@@ -21,9 +21,7 @@
 // WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 // ***********************************************************************
 
-using System;
 using System.Collections;
-using System.Globalization;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs]: Please amend this change too so that your PR doesn't show up in the history of this file.

File: src/NUnitFramework/framework/Constraints/ConstraintResult.cs [hunk 9]
```diff
@@ -1,4 +1,4 @@
-﻿// ***********************************************************************
+// ***********************************************************************
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ConstraintResult.cs]: Please revert and amend so that your PR doesn't show up in the history of this file.

**Comment by jnm2** [comment]
@CharliePoole Good catch, thanks!

**Comment by jnm2** [comment]
I'd say not! What's a good alternative?

**Comment by CharliePoole** [comment]
Here's a straw man to start with...

If the test being made (nested constraint) is equality just say 
    Expected n1 items equal to whatever but was  n2 items.

For any other test (greater than, etc.) say the same thing but then follow with the actual values, possibly on multiple lines, but don't list more than some hard-coded number.

File: src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs (hunk 8 above)
Comment (TobiasSekan) [reply src/NUnitFramework/framework/Internal/Execution/TextMessageWriter.cs]: Oh :roll_eyes: , i forgot that, my used plug-in, **Power Commands for VS** automatic remove unused **using** on save

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 10]
```diff
@@ -0,0 +1,68 @@
+using System.Collections;
+using System.Text;
+
+namespace NUnit.Framework.Constraints
+{
+    /// <summary>
+    /// Contain the result of matching a <see cref="ExactCountConstraint"/> against an actual value.
+    /// </summary>
+    public sealed class ExactCountConstraintResult : ConstraintResult
```
[the remark this answers is not in the document]
Comment (TobiasSekan) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: :+1: -> internal
**private** is impossible for all objects on-top level of a namespace

File: src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs (hunk 2 above)
Comment (TobiasSekan) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs]: :+1:

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs (hunk 3 above)
Comment (TobiasSekan) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: :+1:

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs (hunk 7 above)
Comment (TobiasSekan) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: :+1:

**Comment by TobiasSekan** [comment]
@CharliePoole I can't use the original counter, because he only count the matched objects

```csharp
        public override ConstraintResult ApplyTo<TActual>(TActual actual)
        {
            var enumerable = ConstraintUtils.RequireActual<IEnumerable>(actual, nameof(actual));

            int count = 0;
            if (_itemConstraint == null)
            {
                foreach (object item in enumerable)
                    count++;
            }
            else
            {
                foreach (object item in enumerable)
                    if (_itemConstraint.ApplyTo(item).IsSuccess)
                        count++;
            }

            return new ExactCountConstraintResult(this, actual, count == _expectedCount);
        }
```

**Comment by CharliePoole** [comment]
There are two paths, with and without an item constraint. In each path the actual count is known, even though it has a different meaning in each.

**Comment by CharliePoole** [comment]
Don't revert changes in a PR, instead use local reset or interactive rebate followed by a forced push. While we don't do forced pushed to master, we're OK with them on feature branches.

**Comment by TobiasSekan** [comment]
1. Is there a way to roll back to a commit of the PR on Github or should I close this PR and make a new PR? 
2. I will looking for using the counter until the next week

**Comment by CharliePoole** [comment]
Removing commits is very easy. Assuming you use command-line git, look at the help for the reset command. Examples:

Removing the last commit entirely, losing the changes...

    git reset --hard HEAD~1

Losing the last three commits...

    git reset --hard HEAD~3

Rolling back the last commit, but keeping the changes so that you can continue to revise

   git reset HEAD~1

Using reset to remove the __second-to-last commit__ only, keeping the last one...

    git log // write down the comment on the commit you want to keep
    git reset HEAD~1
    git stash // Save changes you want to re-commit
    git --hard reset HEAD~1 // Kill previous next-to-last, current last commit
    git stash pop // Get the changes back
    git commit -m "Comment you wrote down"

That last one can be done equally well (maybe even easier) using git rebase but IMO just using reset initially is a good way to get a grasp of how git commits work. Also, I think rebase takes a bit more effort to master.

Any of these would, of course, be followed by `git push -f`.

Any of these could be combined with changes to the code before re-commiting.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (jnm2) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: That's why I suggested private *nested*. 😉 I had in mind `ExactCountConstraint.ExactCountConstraintResult`. Not a problem though.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs (hunk 2 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs]: This fix looks like it might have been missed with the rest you did. I'm fan of rebasing/amending/squashing within a PR, so feel free to make your commits all nice and shiny if you feel like it.

**Comment by jnm2** [comment]
Just saw Charlie's very useful comments. I'm totally on board with what he's saying.

I'd add to that: `git commit --amend` combines your staged changes into the most recent commit rather than adding a new commit.
I find [interactive rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase) the easiest of all for everything else. You can change the order, squash things together, drop commits altogether, edit any commits, insert new commits, etc. For interactive rebase, you probably don't want the default editor which is vim. I like Notepad++ because of how fast it opens. Setup:

```
git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"
```

Recent installs of Git for Windows also offer to use Visual Studio Code as the editor. It's an Electron app and a bit slow to open for my taste, but still a solid option. Setup:

```
git config --global core.editor "code --new-window --wait"
```

**Comment by jnm2** [comment]
Just saw Charlie's very useful comments. I'm totally on board with what he's saying.

I'd add to that: `git commit --amend` combines your staged changes into the most recent commit rather than adding a new commit.
Besides a standalone `reset` command, I find [interactive rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase) the easiest of all for everything else. You can change the order, squash things together, drop commits altogether, edit any commits, insert new commits, etc. For interactive rebase, you probably don't want the default editor which is vim. I like Notepad++ because of how fast it opens. Setup:

```
git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"
```

Recent installs of Git for Windows also offer to use Visual Studio Code as the editor. It's an Electron app and a bit slow to open for my taste, but still a solid option. Setup:

```
git config --global core.editor "code --new-window --wait"
```

And, we appreciate the effort you're putting into this PR! Great stuff!

**Comment by TobiasSekan** [comment]
@jnm2 ping

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 11]
```diff
@@ -0,0 +1,62 @@
...
+        {
+            if (_elementList == null)
+            {
+                writer.Write("no items");
+                return;
+            }
+
+            writer.Write(_matchCount != 1 ? "{0} items <" : "{0} item <", _matchCount);
+
+            var writeCounter  = 1;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: I find the aligned `=` a little odd. The only problem I see is that when future contributors edit nearby, their editor will cause them grief by reformatting to remove the extra spaces and they'll have chose between painstakingly putting them back, or including changes over unrelated lines in the git blame history.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+
+            foreach (var element in _elementList)
+                writer.Write(writeCounter++ < _itemCount ? " \"{0}\"," : " \"{0}\" >", element);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: I apologize that this is only occurring to me just now; we try to respect the IEnumerable contract whose premise is that if you call GetEnumerator a second time, the sequence may have completely changed from the first enumeration. We try not to enumerate twice for the sake of correctness.

This is only for display purposes though, so I'm on the fence. @oznetmaster? @nunit/framework-team?

Comment (jnm2) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: It will drive logs on build servers though and may be the key to rare, hard-to-debug issue. I'm feeling less good about the double enumeration the more I think about real-world scenarios I've been in.

Comment (jnm2) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: @nunit/framework-team Final thought: maybe we should merge as-is and open an issue for adding cross-cutting double-enumeration-detecting tests. If we care about this, we should have tests that fail if we do double enumeration.

Comment (CharliePoole) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: As per my original comment, a constraint result should not re-enumerate the values.  It's supposed to __be__ a result, not __calculate__ one. The result is just an aggregation of data that can display itself in a meaningful way. The constraint initialized the result with the info needed, which I had understood to be the expected and actual counts.

Comment (CharliePoole) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: If we decided to display all the matching items , I missed that. It seems excessive but if we want to do it it's up to the constraint to save them.

Comment (jnm2) [reply src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: @CharliePoole I would like to see the elements printed out no matter what kind of constraint the element constraint is. But as you said, there might be thousands and we should certainly limit that.

@TobiasSekan Let's buffer the items into a list at the same time that we cound them, but stop adding to the list after there are already maybe ten items. Then pass that list to [`MsgUtils.FormatCollection`](https://github.com/nunit/nunit/blob/5c6413314bbbbbde29e2cdd7f851c4108554a2de/src/NUnitFramework/framework/Constraints/MsgUtils.cs#L145).

**Comment by TobiasSekan** [comment]
Should i add a additional information that only 10 items are shown, when there are more that 10 items?

**Comment by CharliePoole** [comment]
In other messages, we show that a list or a string is incomplete by use of `...`.

File: src/NUnitFramework/tests/Constraints/ExactCountConstraintTests.cs [hunk 13]
```diff
@@ -136,5 +136,50 @@ public void FailsWhenNotUsedAgainstAnEnumerable()
             TestDelegate act = () => Assert.That(notEnumerable, new ExactCountConstraint(1));
             Assert.That(act, Throws.ArgumentException.With.Message.Contains("IEnumerable"));
         }
+
+        [Test]
+        [Description("Test that the" + nameof(ExactCountConstraint) + "return all ten elements of the given list without a triple dot")]
```
Comment (jnm2) [inline src/NUnitFramework/tests/Constraints/ExactCountConstraintTests.cs]: This forms the string `Test that theExactCountConstraintreturn all…`. `return` should be `returns`, as in, "it returns."

Comment (CharliePoole) [reply src/NUnitFramework/tests/Constraints/ExactCountConstraintTests.cs]: Also note missing space.

**Comment by TobiasSekan** [comment]
Ping - need review :-)

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 14]
```diff
@@ -0,0 +1,88 @@
...
+{
+    /// <summary>
+    /// Contain the result of matching a <see cref="ExactCountConstraint"/> against an actual value.
+    /// </summary>
+    internal sealed class ExactCountConstraintResult : ConstraintResult
+    {
+        /// <summary>
+        /// The maximum count of list elements that are shown on a constrain result, when the constrain condition not match
+        /// </summary>
+        internal static int MaxDisplayCount = 10;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: `const`?

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 15]
```diff
@@ -0,0 +1,88 @@
...
+
+namespace NUnit.Framework.Constraints
+{
+    /// <summary>
+    /// Contain the result of matching a <see cref="ExactCountConstraint"/> against an actual value.
+    /// </summary>
+    internal sealed class ExactCountConstraintResult : ConstraintResult
+    {
+        /// <summary>
+        /// The maximum count of list elements that are shown on a constrain result, when the constrain condition not match
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: XML docs are optional on internal things, but here's some nitpicks if you'd like to add them:
- `constrain result` should be `constraint result`, probably?
- Isn't this the maximum count *always*, not the maximum count only when the constraint condition doesn't match?

File: src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs [hunk 16]
```diff
@@ -0,0 +1,88 @@
...
+        /// </summary>
+        internal static int MaxDisplayCount = 10;
+
+        /// <summary>
+        /// The list with all items of the <see cref="ExactCountConstraint"/>
+        /// </summary>
+        private readonly IEnumerable _elementList;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraintResult.cs]: No longer used, can be removed.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs [hunk 17]
```diff
@@ -69,21 +70,32 @@ public ExactCountConstraint(int expectedCount, IConstraint itemConstraint)
...
+                }
             }
             else
             {
-                foreach (object item in enumerable)
+                foreach (var item in enumerable)
+                {
                     if (_itemConstraint.ApplyTo(item).IsSuccess)
-                        count++;
+                        matchCount++;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs]: The loop is getting big enough that I'd suggest moving the `_itemConstraint == null` check into the loop so that there is only one loop.

File: src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs [hunk 18]
```diff
@@ -69,21 +70,32 @@ public ExactCountConstraint(int expectedCount, IConstraint itemConstraint)
...
+
+                    if (itemList.Count <= ExactCountConstraintResult.MaxDisplayCount)
+                        itemList.Add(item);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs]: I was confused for a while, so it might be good to add a comment saying that we intentionally add one item too many to trigger the ellipsis when we later on call `FormatCollection`.

**Comment by TobiasSekan** [comment]
ping @jnm2

**Comment by rprouse** [comment]
Thanks for your contribution.
