### PR TITLE
TestCaseSource unable to pass one element byte array

### LINKED ISSUE #1851: TestCaseSource unable to pass one element byte array
**NUnit version:**  3.5.0
**Runner**: NUnit3TestAdapter 3.4.1
**Environment**: Visual Studio 2015 Pro Update 1

I'm having troubles using one element byte array passed to NUnit test with `TestCaseSourceAttribute`.

How to reproduce:

```
public class Test
    {
        private static List<byte[]> _byteArrays = new List<byte[]>
        {
            new byte[] { 80 }, // - works fine with commented out
            new byte[] { 80, 75 },
            new byte[] { 80, 75, 03 }
        };

        [Test]
        [TestCaseSource("_byteArrays")]
        public void TestStuff(byte[] byteArray)
        {
            Assert.IsFalse(false);
        }
    }
```

When you run `TestStuff` it will attempt to test things in seperate tests like this:

nunit

It clearly seems that first element is treated as an `System.Byte` instead of `System.Byte[]`.

Error produced by NUnit tells it clearly:

> Result Message:System.ArgumentException : Object of type 'System.Byte' cannot be converted to type 'System.Byte[]'

Any ideas on fixing this?
Thanks!

### PR DESCRIPTION
**Pull request by StanEgo**
While working on #2104 I have also optimized TestCaseSourceAttribute and additionally check it against this issue. Looks like it is fixed.

Fixes #1851

### CODE REVIEW

File: src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs [hunk 1]
```diff
@@ -189,48 +189,29 @@ private IEnumerable<ITestCaseData> GetTestCasesFor(IMethodInfo method)
...
+                                var parameters = method.GetParameters();
+                                var argsNeeded = parameters.Length;
+                                if (argsNeeded > 0 && argsNeeded == array.Length && parameters[0].ParameterType != array.GetType())
                                 {
-                                    // Array is something like int[] - convert it to
-                                    // an object[] for use as the argument array.
                                     args = new object[array.Length];
-                                    for (int i = 0; i < array.Length; i++)
+                                    for (var i = 0; i < array.Length; i++)
                                         args[i] = array.GetValue(i);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs]: `array.CopyTo(args, 0);` is also an option.

File: src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs [hunk 2]
```diff
@@ -142,6 +142,12 @@ public void SourceMayReturnArgumentsAsIntArray(int n, int d, int q)
             Assert.AreEqual(q, n / d);
         }
 
+        [Test, TestCaseSource("MyArrayData")]
+        public void SourceMayReturnArrayForArray(int[] array)
+        {
+            Assert.That(true);
```
Comment (jnm2) [inline src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs]: `Assert.Pass();` or an empty method body are also options.
