### PR TITLE
DictionaryContainsKeyValuePairConstraint supports generic IDictionary

### LINKED ISSUE #3964: DictionaryContainsKeyValuePairConstraint doesn't work with `IDictionary<TKey, TValue>`
`DictionaryContainsKeyValuePairConstraint` fails when actual object implements only `IDictionary<TKey, TValue>`, but not `IDictionary`:

```csharp
[Test]
void Test()
{
    var dictionary = new TestDictionary();
    Assert.That(dictionary, new DictionaryContainsKeyValuePairConstraint(1, "hello"));
}

class TestDictionary : IDictionary<int, string>
{
    // Dictionary implementation
}

// Test fails with next error:
// 1) Error : NUnit.Framework.Constraints.DictionaryContainsKeyValuePairConstraintTests.ShouldCallContainsKeysMethodOnDictionary
// System.ArgumentException : Expected: IDictionary But was: TestDictionary (Parameter 'actual')
```

**NUnit version:** 3.13.2
**Runner:** NUnit3TestAdapter

It looks like the bug is here: https://github.com/nunit/nunit/blob/2c21bff1d8891c2df3cad1f5ed34551e1c4edb9e/src/NUnitFramework/framework/Constraints/DictionaryContainsKeyValuePairConstraint.cs#L43

### PR DESCRIPTION
**Pull request by louis-z**
- Adapt `DictionaryContainsKeyValuePairConstraint` so that it works with types that implement
  - `IDictionary<TKey, TValue>` but
  - not `IDictionary`
- For backward compatibility, keep throwing same exception with same message as before when a failures occurs

Fixes #3964

### CODE REVIEW

**Review by mikkelbu — COMMENTED** [review]
Looks good to me @louis-z. Thanks for the contribution. We will need one more review before merging this.

**Comment by louis-z** [comment]
> Looks good to me @louis-z. Thanks for the contribution. We will need one more review before merging this.

No problem, I was glad to help. 😉 
I just added an assertion to my test, to make sure that looking up a non-existent KVP also works.

File: src/NUnitFramework/framework/Constraints/DictionaryContainsKeyValuePairConstraint.cs [hunk 1]
```diff
@@ -40,12 +43,31 @@ public override string Description
...
+            {
+                foreach (var entry in dictionary)
+                    if (ItemsEqual(entry, _expected))
+                        return true;
+                return false;
+            }
+
+            // If 'actual' implements IDictionary<TKey, TValue>, construct an 'expected' KeyValuePair<TKey, TValue>
+            // and look it up by iterating using IEnumerable
+            if (actual.GetType().GetInterfaces().Any(i => i.FullName.StartsWith("System.Collections.Generic.IDictionary`2[")))
```
Comment (Dreamescaper) [inline src/NUnitFramework/framework/Constraints/DictionaryContainsKeyValuePairConstraint.cs:59]: I'd suggest smth like that instead:
```csharp
i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>)
```

Comment (louis-z) [reply src/NUnitFramework/framework/Constraints/DictionaryContainsKeyValuePairConstraint.cs]: That's a good idea. Just made the change. Thanks @Dreamescaper.

**Review by Dreamescaper — APPROVED** [review]
