### PR TITLE
Fix flakey schema tests

### LINKED ISSUE #2963: Flakey tests in FrameworkControllerTests
Several tests in FrameworkControllerTests have recently failed in a flaky manner on the CI builds. We need to look into why that is, and make a fix.

The failures don't appear to be platform-specific, here are a few sample failure messages:

```
Errors, Failures and Warnings
1) Failed : NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite("<filter/>")
  Expected: not null and String starting with "ID"
  But was:  "8601"
  at NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite (System.String filter) [0x00000] in <1df9fb68b85648378ea6dd2e640b0ed4>:0 
```
```
1) Failed : NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FilterCategory_ReturnsTests
  Expected: not null and String starting with "ID"
  But was:  "7680"
   at NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FilterCategory_ReturnsTests() in /home/travis/build/nunit/nunit/src/NUnitFramework/tests/Api/FrameworkControllerTests.cs:line 316
```
```
1) Failed : NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite("<filter/>")
  Expected: not null and String starting with "ID"
  But was:  "8508"
  at NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite (System.String filter) [0x00000] in <9278af9c5d3e455d8858b76816878cf6>:0 
```

As always, contributions welcome!

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2963 and #2986.

Removed the commit that touches FrameworkControllerTests; I didn't realize at first that those tests actually rely on changing `Test.IdPrefix` to `"ID"`.

### CODE REVIEW

File: src/NUnitFramework/tests/Api/SchemaTests.cs [hunk 1]
```diff
@@ -77,7 +78,7 @@ public static void TestResultSchemaMatches()
         {
             Assert.Multiple(() =>
             {
-                var controller = new FrameworkController("mock-assembly", null, new Dictionary<string, string>());
+                var controller = new FrameworkController("mock-assembly", Test.IdPrefix, new Dictionary<string, string>());
```
Comment (CharliePoole) [inline src/NUnitFramework/tests/Api/SchemaTests.cs]: Well, duh! Good fix!

**Comment by CharliePoole** [comment]
Whoops! I missed that. `FrameworkControllerTests` has to test that the ids start with `Test.Prefix`.

**Comment by OmicronPersei** [comment]
LGTM!
