### PR TITLE
Handling of native exceptions, to attempt to catch C++ errors …

### LINKED ISSUE #2091: When a native exception of corrupted state is thrown, nunit test thread crashes and the nunit-console process hangs
When using NUnit in C++/CLI and the state is somehow corrupted (unrecoverable errors), the nunit thread that runs the test crashes. The nunit-console thread that is waiting on the operation to complete, never exits the wait and therefore hangs the whole process.

Maybe using NUnit for C++/CLI is not supported, but we have a lot of them.

I have made a quick fix like this in NUnit.Framework.Internal.Reflect in Reflect.cs:
```
[HandleProcessCorruptedStateExceptions] //put here to handle native corrupt state exceptions. 
        public static object InvokeMethod( MethodInfo method, object fixture, params object[] args )
        {
            if(method != null)
            {
                try
                {
                    return method.Invoke(fixture, args);
                }
#if !PORTABLE && !NETSTANDARD1_6
                catch (System.Threading.ThreadAbortException)
                {
                    // No need to wrap or rethrow ThreadAbortException
                    return null;
                }
#endif
                catch (TargetInvocationException e)
                {
                    throw new NUnitException("Rethrown", e.InnerException);
                }
                catch (Exception e)
                {
                    throw new NUnitException("Rethrown", e);
                }
#pragma warning disable 1058
                catch
#pragma warning restore 1058
                {
                    throw new NUnitException("Rethrown", new Exception("Unknown Native exception thrown."));
                }
            }

            return null;
        }
```

### PR DESCRIPTION
**Pull request by endrih**
Fixes #2091 . It is useful for cases when people are using NUnit in C++/CLI projects and a native exception of corrupt state occurs that crashes the testing thread. When the testing thread crashes, NUnit hangs as a result.

### CODE REVIEW

**Comment by jnm2** [comment]
Tip: you can edit the initial PR comment to say "Fixes #2091" or "Closes #2091" ([doc](https://help.github.com/articles/closing-issues-using-keywords/)) so that GitHub closes the issue when this PR is merged.

**Comment by endrih** [comment]
Do I need to do anything else for this pull request so that it is merged into main? (it is the first time I do it here, so I don't know how the full process goes)

**Comment by CharliePoole** [comment]
The fixes phrase should be in a comment, as I edited it, not the title.

@jnm2 approved the PR. It's waiting for a second team approval to be merged.

File: src/NUnitFramework/framework/Internal/Reflect.cs [hunk 1]
```diff
@@ -24,7 +24,11 @@
 using System;
 using System.Collections;
 using System.Collections.Generic;
+using System.ComponentModel;
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Internal/Reflect.cs]: Major nit pick :). Is this necessary?

**Comment by mikkelbu** [comment]
Merged. Thanks for the contribution @endrih 👍 .

File: src/NUnitFramework/framework/Internal/Reflect.cs (hunk 1 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Reflect.cs]: Nice spot! I just had a thought– maybe we should leave some time for the contributor to respond if there are questions before merging? :D

Comment (mikkelbu) [reply src/NUnitFramework/framework/Internal/Reflect.cs]: Actually, I did not find this important enough to hold back the PR, and perhaps I should just have ignored it :)

**Comment by jnm2** [comment]
This PR has never had any effect because https://github.com/nunit/nunit/pull/1775 added `[assembly: AllowPartiallyTrustedCallers]` and the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=netframework-4.8) say this means that `[HandleProcessCorruptedStateExceptions]` is ignored:

> The HandleProcessCorruptedStateExceptionsAttribute attribute is ignored when it is encountered in partially trusted or transparent code, because a trusted host should not allow an untrusted add-in to catch and ignore these serious exceptions.

The NUnit hang is due to NUnit Framework not being able to catch such exceptions. See https://github.com/nunit/nunit/issues/3295#issuecomment-507503500.
