### PR TITLE
Change TestAssembly to only take in assembly name, clean up the usage of path and name

### LINKED ISSUE #2898: AssemblyPath contains invalid charaters
When running test on UWP, we ran into an ArgumentException (Illegal characters in path) during BuildTestAssembly in DefaultTestAssemblyBuilder.cs. It seems to be complaining about assemblyPath, which is "\<unknown\>" instead of the real assembly path. Here are the related codes:
https://github.com/nunit/nunit/blob/e94c6d9cd4655c63c514ce354f7e8d451dc0118a/src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs#L83
https://github.com/nunit/nunit/blob/e94c6d9cd4655c63c514ce354f7e8d451dc0118a/src/NUnitFramework/framework/Internal/AssemblyHelper.cs#L56
This issue was introduced in NUnit 3.7. Prior to 3.7, it calls `AssemblyHelper.GetAssemblyName(assembly).FullName` to get the assemblyPath, which works fine. Now, it all uses `Assembly.GetAssemblyPath(assembly)`. According to [.NET API](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.module.fullyqualifiedname?view=netframework-4.7.2#System_Reflection_Module_FullyQualifiedName), `FullyQualifiedName` for the module might be "\<unknown\>" in certain situations. Switching back to GetAssemblyName simply fixes the problem here.

I may be wrong, but it seems to me that the only use of assemblyPath is to get the name of the assembly later. So why not just getting the name instead of the path here?

### PR DESCRIPTION
**Pull request by jrjrguo**
The motivation of this change is to fix #2898 . The assemblyPath of an assembly might be <unknown> when running uwp tests. The fix is to use the assemblyName instead in those cases.
The main improvement is to TestAssembly so that it only takes in assembly name, since that's the only thing it actually uses. It was a bit misleading before, which is probably why assemblyPath and assemblyName are a little misused in multiple classes. Now the caller should only pass in name to TestAssembly.

### CODE REVIEW

File: src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs [hunk 1]
```diff
@@ -81,42 +81,46 @@ public ITest Build(Assembly assembly, IDictionary<string, object> options)
...
+                : AssemblyHelper.GetAssemblyName(assembly).FullName;
+
+            return Build(assembly, assemblyName, options);
         }
 
         /// <summary>
         /// Build a suite of tests given the filename of an assembly
         /// </summary>
-        /// <param name="assemblyName">The filename of the assembly from which tests are to be built</param>
+        /// <param name="assemblyNameOrPath">The filename or path of the assembly from which tests are to be built</param>
```
Comment (jnm2) [inline src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs]: I think this should actually say `the assembly name or filename` or `the name or location of the assembly`.

File: src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs [hunk 2]
```diff
@@ -81,42 +81,46 @@ public ITest Build(Assembly assembly, IDictionary<string, object> options)
 #endif
 
             string assemblyPath = AssemblyHelper.GetAssemblyPath(assembly);
-            return Build(assembly, assemblyPath, options);
+            string assemblyName = assemblyPath.IndexOfAny(Path.GetInvalidPathChars()) == -1
```
Comment (jnm2) [inline src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs]: I'm almost happier if we specially recognize `<Unknown>` inside `AssemblyHelper.GetAssemblyPath` and return null.

If there are invalid path characters for any other reason, wouldn't we'd want to know about it right away and not just treat it as though it was the result of a call to `Assembly.ManifestModule.FullyQualifiedName` returning its documented `<Unknown>` value?

File: src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs [hunk 3]
```diff
@@ -39,25 +39,25 @@ public class TestAssembly : TestSuite
...
         /// <summary>
         /// Initializes a new instance of the <see cref="TestAssembly"/> class
-        /// specifying the Assembly and the path from which it was loaded.
+        /// specifying the Assembly and the name of the assembly.
         /// </summary>
         /// <param name="assembly">The assembly this test represents.</param>
-        /// <param name="path">The path used to load the assembly.</param>
-        public TestAssembly(Assembly assembly, string path)
-            : base(path)
+        /// <param name="name">The name of the assembly.</param>
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs]: To be more direct about the fact that this parameter just controls a display name, could we say, "The desired name for the test suite?"

File: src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs [hunk 4]
```diff
@@ -81,42 +81,46 @@ public ITest Build(Assembly assembly, IDictionary<string, object> options)
...
-                testAssembly = new TestAssembly(assemblyName);
+                testAssembly = new TestAssembly(Path.GetFileName(assemblyNameOrPath));
                 testAssembly.MakeInvalid(ExceptionHelper.BuildMessage(ex, true));
             }
 
             return testAssembly;
         }
 
-        private TestSuite Build(Assembly assembly, string assemblyPath, IDictionary<string, object> options)
+        private TestSuite Build(Assembly assembly, string assemblyName, IDictionary<string, object> options)
```
Comment (jnm2) [inline src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs]: I'm thinking this would be most clear as `string suiteName`, and `suiteName` should also be the name of the `BuildTestAssembly` parameter.

File: src/NUnitFramework/tests/Internal/SetUpFixtureTests.cs [hunk 5]
```diff
@@ -16,7 +16,8 @@ namespace NUnit.Framework.Internal
     [TestFixture]
     public class SetUpFixtureTests
     {
-        private static readonly string testAssembly = AssemblyHelper.GetAssemblyPath(typeof(NUnit.TestData.SetupFixture.Namespace1.SomeFixture).GetTypeInfo().Assembly);
+        private static readonly string ASSEMBLY_PATH = AssemblyHelper.GetAssemblyPath(typeof(NUnit.TestData.SetupFixture.Namespace1.SomeFixture).GetTypeInfo().Assembly);
+        private static readonly string ASSEMBLY_NAME = System.IO.Path.GetFileName(ASSEMBLY_PATH);
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/SetUpFixtureTests.cs]: Assembly name isn't the same thing as assembly filename, but either way I'm thinking `SUITE_NAME` is what we're really testing.

File: src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs [hunk 6]
```diff
@@ -39,25 +39,25 @@ public class TestAssembly : TestSuite
...
 
         /// <summary>
         /// Initializes a new instance of the <see cref="TestAssembly"/> class
-        /// for a path which could not be loaded.
+        /// specifying the name of the assembly.
         /// </summary>
-        /// <param name="path">The path used to load the assembly.</param>
-        public TestAssembly(string path) : base(path)
+        /// <param name="name">The name of the assembly.</param>
+        public TestAssembly(string name) : base(name)
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs]: I'd almost ask for this to be `suiteName` too for full clarity, but it seems more consistent to align with the base class's parameter name and property.

**Comment by jnm2** [comment]
@jrjrguo This is super, thanks for working on it! We like to ask that the PR comment contains the GitHub keyword "Fixes #2898" or "Closes #2898" so that the issue is specially linked and [autoclosed](https://help.github.com/articles/closing-issues-using-keywords/).

File: src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs (hunk 2 above)
Comment (jrjrguo) [reply src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs]: Ah yes, that makes sense since <unknown> is a special case. I'll make the change to only handle <unknown>.

**Comment by jrjrguo** [comment]
@jnm2 I totally agree with your comments on renaming and comment phrasing. Keeping `name` in TestAssembly and renaming `assemblyName` to `suiteName` in BuildTestAssembly is a nice transition from name/path to a desired name. Let me know what do you think!

File: src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs [hunk 7]
```diff
@@ -39,25 +39,25 @@ public class TestAssembly : TestSuite
     {
         /// <summary>
         /// Initializes a new instance of the <see cref="TestAssembly"/> class
-        /// specifying the Assembly and the path from which it was loaded.
+        /// specifying the Assembly and the name of the assembly.
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs]: `and the name for the test suite` perhaps, to match the parameter documentation?

File: src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs [hunk 8]
```diff
@@ -39,25 +39,25 @@ public class TestAssembly : TestSuite
...
         {
             this.Assembly = assembly;
-            this.Name = Path.GetFileName(path);
+            this.Name = name;
         }
 
         /// <summary>
         /// Initializes a new instance of the <see cref="TestAssembly"/> class
-        /// for a path which could not be loaded.
+        /// specifying the name of the assembly.
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Tests/TestAssembly.cs]: This constructor is specifically used when there is no Assembly object because the load failed. Maybe a way to keep reflecting that would be `specifying a suite name for an assembly which failed to load.` or something similar?

**Comment by jnm2** [comment]
@jrjrguo That's the plan! ℹ See https://github.com/nunit/nunit/issues/2898: 

image

Some of our regular reviewers are unusually busy right now.

**Comment by jrjrguo** [comment]
Awesome, thanks guys!
