### PR TITLE
Test on .NET 5 and fix crash in RuntimeFramework

### LINKED ISSUE #3565: .NET 5 issue with PlatformAttribute
On .NET 5 Preview 4 exception occurred when using PlatformAttribute.

```
An exception was thrown while loading the test.
System.ArgumentException: Unknown framework version 5.5 (Parameter 'version')
   at NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion(Version version) in D:\a\1\s\src\NUnitFramework\framework\Internal\RuntimeFramework.cs:line 235
   at NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(Version version) in D:\a\1\s\src\NUnitFramework\framework\Internal\RuntimeFramework.cs:line 226
   at NUnit.Framework.Internal.RuntimeFramework..ctor(RuntimeType runtime, Version version) in D:\a\1\s\src\NUnitFramework\framework\Internal\RuntimeFramework.cs:line 177
   at NUnit.Framework.Internal.RuntimeFramework.<>c.<.cctor>b__33_0() in D:\a\1\s\src\NUnitFramework\framework\Internal\RuntimeFramework.cs:line 145
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)--- End of stack trace from previous location
---
   at System.Lazy`1.CreateValue()   at System.Lazy`1.get_Value()
   at NUnit.Framework.Internal.RuntimeFramework.get_CurrentFramework() in D:\a\1\s\src\NUnitFramework\framework\Internal\RuntimeFramework.cs:line 261
   at NUnit.Framework.Internal.PlatformHelper..ctor() in D:\a\1\s\src\NUnitFramework\framework\Internal\PlatformHelper.cs:line 66
   at NUnit.Framework.PlatformAttribute..ctor(String platforms) in D:\a\1\s\src\NUnitFramework\framework\Attributes\PlatformAttribute.cs:line 37
```

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #3565

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/RuntimeFramework.cs [hunk 1]
```diff
@@ -380,33 +387,41 @@ private static bool IsNetCore()
...
         {
-            return Enum.GetNames( typeof(RuntimeType)).Any( item => item.ToLower() == name.ToLower() );
+            return Enum.GetNames(typeof(RuntimeType)).Contains(name, StringComparer.OrdinalIgnoreCase);
+        }
+
+        private static string GetShortName(RuntimeType runtime, Version version)
+        {
+            return runtime == RuntimeType.NetFramework || (runtime == RuntimeType.NetCore && version.Major >= 5)
+                ? "Net"
+                : runtime.ToString();
```
Comment (ChrisMaddock) [inline src/NUnitFramework/framework/Internal/RuntimeFramework.cs:414]: This is to maintain backwards compatibility, right?

I actually tried to work out if it would matter, and from what I can see, this property is only ever set, and never used. But this fits with the minimal-change idea. 🙂

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/RuntimeFramework.cs:414]: I think this change is demanded by the tests. `net5.0` is `.NETCoreApp` while `net4.8` is `.NETFramework`, in terms of how the .csproj SDK works, and our platform includes/excludes should be consistent with that.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/RuntimeFramework.cs:414]: You could be right though that the tests could be changed without confusing our users.
