### PR TITLE
Fix and/or remove some analyzer warnings from the tests

### LINKED ISSUE #5182: Remove unnecessary NUnit analyzer suppressions from latest analyzer package
A new version of the analyzers has been released which includes support for some features added in version 4.5 of the framework. The framework tests have been updated to use the new analyzers, however there are some now-unnecessary suppressions still in place

### PR DESCRIPTION
**Pull request by stevenaw**
Fixes #5182 

The impact of these changes reduced significantly after I'd noticed we already updated the analyzers in the 4.6 branch, however I wanted to continue on the with changes to apply some fixers or remove suppressions where applicable.

This is by no means an exhaustive fix. It was initially intended to focus on the `NUnit1029` changes within the 4.12.0 analyzers release, however I've applied a few other fixers in the related files as I found them.

### CODE REVIEW

File: src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs [hunk 1]
```diff
@@ -111,9 +110,9 @@ public void SourceCanBeStaticField(string source)
         }
 
         private static readonly object[] StaticField =
-            {
+            [
                 new object[] { "StaticField" }
-            };
+            ];
```
Comment (mikkelbu) [inline src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs]: Should these be unindented 4 spaces?

Comment (mikkelbu) [reply src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs]: Sorry about the diff - it looks quite odd (I tried to add a suggestion, but that was just as odd)
image

Comment (stevenaw) [reply src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs]: I agree this looks a bit odd, including the existing formatting. I can collapse this to a single line as it's just a single-element array if it helps readability

**Comment by stevenaw** [comment]
Thanks for your feedback and approval @mikkelbu . I'm going to go ahead and merge as I've fixed the formatting and the tests continue to pass.
