### PR TITLE
Resolve filter parsing issues

### LINKED ISSUE #4651: After upgrade from version 3.14.0 to 4.* running multiple test categories in parentheses separated with 'OR' stopped working
**Versions of lib**
.NET 6, NUnit 4.1.0 with NUnit3TestAdapter 4.5.0 and Microsoft.NET.Test.Sdk 17.9.0.

**Command to execute tests**
`dotnet test "testingnunit.dll" --verbosity d --filter "(TestCategory=TestsA&TestCategory!=TestsB)|(TestCategory=TestsC)"`

**How to reproduce**
1. Create a project called testingnunit with the provided example class in it. Build the project.
2. Run the test command, no tests will be found when running with NUnit version 4.0.0 or later.
Output is "**No test matches the given testcase filter**".
image
4. If you downgrade NUnit to version 3.14.0 and run the test command it finds the tests. TestInA and TestInC are exectued, TestInB is excluded as expected.
image

**How to mitigate the problem when running with NUnit 4.1.0**
Run dotnet test for each filter within parentheses. 
First run `dotnet test "testingnunit.dll" --verbosity d --filter "(TestCategory=TestsA&TestCategory!=TestsB)"`, and then run `dotnet test "testingnunit.dll" --verbosity d --filter "(TestCategory=TestsC)"`

**Code example**
```csproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
      <PackageReference Include="NUnit" Version="4.1.0" />
      <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>
</Project>
```

```csharp
using NUnit.Framework;

namespace TestingNunit;

[TestFixture, Category("TestsA")]
public class TestsA
{
    [Test]
    public void TestInA()
    {
        Assert.Pass();
    }
}

[TestFixture, Category("TestsB")]
public class TestsB
{
    [Test]
    public void TestInB()
    {
        Assert.Fail();
    }
}

[TestFixture, Category("TestsC")]
public class TestsC
{
    [Test]
    public void TestInC()
    {
        Assert.Pass();
    }
}
```

### PR DESCRIPTION
**Pull request by stevenaw**
Fixes #4651 #4589

First commit is just to establish a baseline failing CI run with the two known scenarios. Second commit fixes the underlying issue.

### CODE REVIEW

**Comment by stevenaw** [comment]
This is ready for review

File: src/NUnitFramework/tests/Internal/Filters/TestFilterXmlTests.cs [hunk 1]
```diff
@@ -2,6 +2,8 @@
 
 using NUnit.Framework.Internal;
 using NUnit.Framework.Internal.Filters;
+using NUnit.Framework.Tests.TestUtilities;
+//using NUnit.Framework.Tests.TestUtilities;
```
Comment (manfred-brands) [inline src/NUnitFramework/tests/Internal/Filters/TestFilterXmlTests.cs:6]: Remove 
```suggestion
```

File: src/NUnitFramework/framework/Interfaces/TNode.cs [hunk 2]
```diff
@@ -169,6 +169,13 @@ public static TNode FromXml(string xmlText)
                         }
                     }
                 }
+                else if (reader.NodeType == XmlNodeType.EndElement)
+                {
+                    if (reader.Depth < parents.Count)
+                    {
+                        parents.Pop();
```
Comment (manfred-brands) [inline src/NUnitFramework/framework/Interfaces/TNode.cs:176]: Does this mean that the code that 'Pops' in lines 153-157 can be removed?

**Review by manfred-brands — COMMENTED** [review]
I have some questions

File: src/NUnitFramework/framework/Interfaces/TNode.cs (hunk 2 above)
Comment (stevenaw) [reply src/NUnitFramework/framework/Interfaces/TNode.cs:176]: Good point! I recall that code being hit, but it was before having added my own changes. I'll try and check this out tonight to confirm if it can be removed.

**Review by manfred-brands — APPROVED** [review]
Looks good now.

**Comment by stevenaw** [comment]
Thanks @manfred-brands !
