### PR TITLE
Compare records by properties when requested

### LINKED ISSUE #4836: PropertiesComparer doesn't work well with records
```csharp
record C1
{
    public string Name { get; set; }
    public int[] Collection { get; set; }
}

var v1 = new C1 { Name = "1", Collection = [1, 2, 3] };
var v2 = new C1 { Name = "1", Collection = [1, 2, 3] };

Assert.That(v1, Is.EqualTo(v2).UsingPropertiesComparer());
```

The assertion above fails, even thouht the same code works fine if I replace "record" with "class".
I assume that the issue is that record is IEquatable, therefore comparer doesn't attempt to compare it by properties.

I would suggest to ignore IEquatable for records in case `UsingPropertiesComparer` is used, and still compare it property by property.

### PR DESCRIPTION
**Pull request by Dreamescaper**
Fixes #4836 .

If CompareProperties is true, and actual value is record type, I ignore compiler-generated Equals methods, and force it to compare by properties instead.

In order to check that provided type is record, I verify that Equals method has CompilerGeneratedAttribute. Not sure if there's a better way.

I wanted to add a test for class with primary constructor, therefore I increased LangVersion to 12. Let me know if that causes any issues.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/TypeHelper.cs [hunk 1]
```diff
@@ -387,5 +388,16 @@ internal static string FullName(this Type type)
         {
             return type.FullName ?? throw new InvalidOperationException("No name for type: " + type);
         }
+
+        private static readonly Type[] EqualsObjectParameterTypes = { typeof(object) };
+
+        internal static bool IsRecord(this Type type)
```
Comment (manfred-brands) [inline src/NUnitFramework/framework/Internal/TypeHelper.cs:394]: Suggest to rename to `HasCompilerGeneratedEquals`

File: src/NUnitFramework/tests/Assertions/AssertThatTests.cs [hunk 2]
```diff
@@ -655,6 +664,8 @@ public void TestPropertyFailureSecondLevel()
              */
         }
 
+        private record Record(string Name, int[] Collection);
```
Comment (manfred-brands) [inline src/NUnitFramework/tests/Assertions/AssertThatTests.cs:667]: I would like an example of a `record` where the user overrides `Equals`.
E.g. To use Case insensitive comparison of `Name`.
```csharp
private sealed record Person(string Name)
{
    public bool Equals(Person? other)
    {
        return string.Equals(Name, other?.Name, System.StringComparison.OrdinalIgnoreCase);
    }

    public override int GetHashCode()
    {
        return Name.GetHashCode(System.StringComparison.OrdinalIgnoreCase);
    }
}
```

File: src/NUnitFramework/framework/Internal/TypeHelper.cs [hunk 3]
```diff
@@ -387,5 +388,16 @@ internal static string FullName(this Type type)
...
+        {
+            // Check if Equals method has CompilerGenerated attribute
+            var equalsMethod = type.GetMethod(nameof(type.Equals), BindingFlags.Instance | BindingFlags.Public,
```
Comment (manfred-brands) [inline src/NUnitFramework/framework/Internal/TypeHelper.cs:397]: This tests for `Equals(object)`. It would be better to check for `Equals(T)`. See my `Person` record class. It defined `Equals(Person)` but not `Equals(object)` as the generated version is fine as it defers to `Equals(Person)`.

File: src/NUnitFramework/tests/Internal/TypeHelperTests.cs [hunk 4]
```diff
@@ -84,5 +84,53 @@ private class Generic<T>
...
+                return obj is ClassWithOverriddenEquals other && other.Name == Name;
+            }
+
+            public override int GetHashCode()
+            {
+                return 539060726 + EqualityComparer<string?>.Default.GetHashCode(Name ?? string.Empty);
+            }
+        }
+
+        private record class RecordClass(string Name);
```
Comment (manfred-brands) [inline src/NUnitFramework/tests/Internal/TypeHelperTests.cs:125]: Please add a record class overriding `Equals<T>`.

File: src/NUnitFramework/framework/Internal/TypeHelper.cs (hunk 3 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/TypeHelper.cs:397]: This is only relevant if the class has reference value properties (or an ImmutableArray).
Only for records where the default generated implementation would be wrong.

File: src/NUnitFramework/framework/Internal/TypeHelper.cs (hunk 1 above)
Comment (manfred-brands) [reply src/NUnitFramework/framework/Internal/TypeHelper.cs:394]: Or `HasNonValueCompilerGeneratedEquals`

**Review by manfred-brands — CHANGES_REQUESTED** [review]
We should assume that the owner of the class knows best. If it explicitly implements `Equals(T)` it should be called regardless of properties comparer selection.

Also for 90% of record classes which only contain _value_ like properties the generated code is just fine.

File: src/NUnitFramework/Directory.Packages.props [hunk 5]
```diff
@@ -30,7 +30,7 @@
     <PackageVersion Include="DotNetAnalyzers.DocumentationAnalyzers" Version="1.0.0-beta.59" />
     <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.10.0" />
     <PackageVersion Include="NUnit.Analyzers" Version="4.3.0" />
-    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.507" />
+    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
```
Comment (Dreamescaper) [inline src/NUnitFramework/Directory.Packages.props:33]: Older version complained about collection initializers

**Comment by Dreamescaper** [comment]
I've updated the PR per your suggestions, thanks!

**Review by manfred-brands — APPROVED** [review]
Thanks @Dreamescaper, looks good now.
