### PR TITLE
 Use longer BusyExecIdle to avoid CI failures 

### LINKED ISSUE #2831: Regular "BusyExecIdle after 200 milliseconds delay" CI failures
This is responsible for the last couple dozen times I read through the AppVeyor logs to figure out why a branch was failing to build. Always seems to be net35.

```
1) Failed : NUnit.Framework.Internal.Execution.TestWorkerTests.BusyExecuteIdleEventsCalledInSequence
  Expected: "BusyExecIdle" after 200 milliseconds delay
  But was:  <string.Empty>
   at NUnit.Framework.Internal.Execution.TestWorkerTests.BusyExecuteIdleEventsCalledInSequence() in C:\projects\nunit\src\NUnitFramework\tests\Internal\TestWorkerTests.cs:line 67
```

Can we change this to `10_000`? If it succeeds it's instantaneous. If it fails, all we care about is not hanging for minutes on end.

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2831

### CODE REVIEW

File: src/NUnitFramework/tests/Internal/TestWorkerTests.cs [hunk 1]
```diff
@@ -56,15 +56,20 @@ public void BusyExecuteIdleEventsCalledInSequence()
...
 
-            _queue.Enqueue(work);
-            _worker.Start();
-            _queue.Start();
+                _queue.Enqueue(work);
+                _worker.Start();
+                _queue.Start();
 
-            Assert.That(() => sb.ToString(), Is.EqualTo("BusyExecIdle").After(200));
+                if (!countdown.Wait(10000)) Assert.Fail("Timed out.");
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/TestWorkerTests.cs]: If I had just changed `After`, we would have an unnecessary 10 second wait on success. (I also avoid [Timeout] on tests when possible because thread aborts introduce inherent unreliability.)

Comment (ChrisMaddock) [reply src/NUnitFramework/tests/Internal/TestWorkerTests.cs]: Would this work using the polling functionality of DelayedConstraint? (E.g. After(10000,200))

Comment (jnm2) [reply src/NUnitFramework/tests/Internal/TestWorkerTests.cs]: I wasn't aware of that. Probably! Should  I try it?

Comment (jnm2) [reply src/NUnitFramework/tests/Internal/TestWorkerTests.cs]: Seems to work great, thanks!
