### PR TITLE
Null guard in BuildMessage

### LINKED ISSUE #2450: NullReferenceException in ExceptionHelper.BuildMessage on Mono
When executing the tests in [this project](https://github.com/Pomona/Pomona) with NUnit.ConsoleRunner version 3.7 (and NUnit version 3.8.1), it currently fails in Mono with a `NullReferenceException`:

```c#
System.NullReferenceException: Object reference not set to an instance of an object
  at NUnit.Framework.Internal.ExceptionHelper.BuildMessage (System.Exception exception, System.Boolean excludeExceptionNames) [0x00009] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.TestResult.RecordException (System.Exception ex) [0x000aa] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork () [0x00032] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread () [0x0007b] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.WorkItem.Execute () [0x000c4] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch (NUnit.Framework.Internal.Execution.WorkItem work, NUnit.Framework.Internal.Execution.ParallelExecutionStrategy strategy) [0x00039] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch (NUnit.Framework.Internal.Execution.WorkItem work) [0x00008] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren () [0x000a7] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork () [0x000cb] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread () [0x0007b] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.WorkItem.Execute () [0x000c4] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc () [0x00079] in <d0c69b98d4da4342a70f9b139b717b6d>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
```

I've tried to do a custom build of NUnit locally and drop in the `.pdb`, but I don't get line numbers out so I'm probably not twisting the right knobs. Looking at [the method](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/ExceptionHelper.cs#L79), it's not very complicated:

```c#
public static string BuildMessage(Exception exception, bool excludeExceptionNames=false)
{
    StringBuilder sb = new StringBuilder();
    if (!excludeExceptionNames)
        sb.AppendFormat("{0} : ", exception.GetType());
    sb.Append(GetExceptionMessage(exception));

    foreach (Exception inner in FlattenExceptionHierarchy(exception))
    {
        sb.Append(Environment.NewLine);
        sb.Append("  ----> ");
        if (!excludeExceptionNames)
            sb.AppendFormat("{0} : ", inner.GetType());
        sb.Append(GetExceptionMessage(inner));
    }

    return sb.ToString();
}
```

Since `BuildMessage` is at the top of the stack, the problem can't be within `GetExceptionMessage()` or `FlattenExceptionHierarchy()`, sot he only obvious problem here is if `exception` is `null` and `excludeExceptionNames` is `false`, which will cause `exception.GetType()` to blow up.

I can submit a PR that preforms some `null` checks on the code, but would like some advice from you guys first.

### PR DESCRIPTION
**Pull request by asbjornu**
This PR adds `null` guards in `ExceptionHelper.BuildMessage()` and `TestResult.RecordException()` and avoids using `InnerException` if it is null.

This fixes #2450, or at least makes an honest attempt to fix it, although there's no unit test here proving the problem described in that issue as I'm unable to reproduce it as of yet. If you have any great ideas on how to reproduce the problem, please let me know and I'll add a unit test to the PR.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
The fix looks good. 👍 

With your fix in place - am I right that you should be seeing the exception recorded in the TestResult.xml? From that, is it possible to see exactly what the exception is, i.e. if it's something like a `TargetInvocationException` with null InnerException?

Once we find that out, could we then have a simple test that you can pass such an exception into `TestResult.RecordException()` and it produces the expected message without crashing?

My concern is that this appears to be a peculiarity of mono - and without a unit test in place, future changes could easily refactor and break this functionality.

**Comment by asbjornu** [comment]
@ChrisMaddock: I haven't executed the test with my update yet, simply because I don't really know what to do to get my fix in. After running `./build.sh` I get a `bin` folder with lots of stuff in it, but there's no clear correlation between the folders in there and those that were created by the NUnit NuGet package. I've tried copying the contents of the `bin/Debug/net-4.5` folder into `packages/NUnit.3.8.1/lib/net45`, recompiling and running the tests again, but that has seemingly no effect; the test still throw `NullReferenceException`.

**Comment by mikkelbu** [comment]
@asbjornu What if you use the files from https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-ci-04460-pr-2453/artifacts. Does that change anything?

**Comment by ChrisMaddock** [comment]
@asbjornu - you can build your own NuGet package using build.sh. 🙂 

First do `./build.sh -t Build` and then `./build.sh -t Package`. Or however you'd normally pass those params in bash - sorry, I'm a Windows kid!

**Comment by ChrisMaddock** [comment]
Or just get the package from the CI build as @mikkelbu said. That works too! 😄

File: src/NUnitFramework/framework/Internal/ExceptionHelper.cs [hunk 1]
```diff
@@ -78,6 +78,8 @@ public static void Rethrow(Exception exception)
         /// <returns>A combined message string.</returns>
         public static string BuildMessage(Exception exception, bool excludeExceptionNames=false)
         {
+            Guard.ArgumentNotNull(exception, "exception");
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/ExceptionHelper.cs]: Please use `nameof(exception)` now. =)

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 2]
```diff
@@ -495,37 +495,39 @@ public void SetResult(ResultState resultState, string message, string stackTrace
...
         /// Set the test result based on the type of exception thrown
         /// </summary>
-        /// <param name="ex">The exception that was thrown</param>
-        public void RecordException(Exception ex)
+        /// <param name="exception">The exception that was thrown</param>
+        public void RecordException(Exception exception)
         {
-            if (ex is NUnitException || ex is TargetInvocationException)
-                ex = ex.InnerException;
+            Guard.ArgumentNotNull(exception, "exception");
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs]: Good check. `nameof` here also please.

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 3]
```diff
@@ -542,27 +544,27 @@ public void RecordException(Exception ex)
...
         /// </summary>
-        /// <param name="ex">The exception that was thrown</param>
+        /// <param name="exception">The exception that was thrown</param>
         /// <param name="site">The FailureSite to use in the result</param>
-        public void RecordException(Exception ex, FailureSite site)
+        public void RecordException(Exception exception, FailureSite site)
         {
-            if (ex is NUnitException)
-                ex = ex.InnerException;
+            if (exception is NUnitException)
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs]: I think we should add `&& exception.InnerException != null` here too, and throw ArgumentNullException at the top of the method for `exception`.

@nunit/framework-team Does anyone know why we aren't unwrapping `TargetInvocationException` too like we do in the other `RecordException` overload?

**Comment by jnm2** [comment]
I second ChrisMaddock's request for a test that fails before the change and succeeds after. If you run into problems with that, I can try to help.

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs (hunk 3 above)
Comment (ChrisMaddock) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs]: I'm pretty sure I added the TargetInvocationException line - and most likely missed that the code was duplicated. I wonder if I can de-duplicate?

@CharliePoole will be happy with this, as we've written the duplicate code first, and are removing it second! 😄 😉

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs]: De-duping sounds good!

**Comment by asbjornu** [comment]
Upgrading to the downloaded NuGet package (thanks for the tip, @mikkelbu!) makes the [`ApplyChanges_IsSuccessful` test](https://github.com/Pomona/Pomona/blob/develop/tests/Pomona.UnitTests/Patch/DeltaTests.cs#L78) and a few other tests throw the following:

```c#
NUnit.Framework.Internal.NUnitException : Rethrown
  at NUnit.Framework.Internal.Reflect.InvokeMethod (System.Reflection.MethodInfo method, System.Object fixture, System.Object[] args) [0x0002a] in <54dd783801a04556814e44c5d83f8a66>:0
  at NUnit.Framework.Internal.MethodWrapper.Invoke (System.Object fixture, System.Object[] args) [0x00006] in <54dd783801a04556814e44c5d83f8a66>:0
  at NUnit.Framework.Internal.Commands.TestMethodCommand.RunNonAsyncTestMethod (NUnit.Framework.Internal.TestExecutionContext context) [0x00011] in <54dd783801a04556814e44c5d83f8a66>:0
  at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod (NUnit.Framework.Internal.TestExecutionContext context) [0x0001f] in <54dd783801a04556814e44c5d83f8a66>:0
  at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00000] in <54dd783801a04556814e44c5d83f8a66>:0
  at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork () [0x0000d] in <54dd783801a04556814e44c5d83f8a66>:0
```

Interestingly, a new failure has now also surfaced. [This test](https://github.com/Pomona/Pomona/blob/develop/tests/Pomona.SystemTests/Linq/ExtendedResourceClientTests.cs#L27) and quite a few others is causing the following exception:

```c#
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.TypeInitializationException : The type initializer for 'Pomona.Common.Proxies.ITestParentClientResource_ExtendedResourceBase`1' threw an exception.
  ----> System.Reflection.AmbiguousMatchException : Ambiguous match found.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at Pomona.Common.Proxies.RuntimeProxyFactory.Create (System.Type proxyBase, System.Type proxyTarget) [0x00018] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.Common.ExtendedResources.ExtendedResourceMapper.CreateClientSideResourceProxy (Pomona.Common.ExtendedResources.ExtendedResourceInfo userTypeInfo, System.Object wrappedResource) [0x00024] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.Common.ExtendedResources.ExtendedResourceMapper.MapResult (System.Object result, System.Type serverType, System.Type extendedType) [0x0003a] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.Common.ExtendedResources.ExtendedResourceMapper.WrapResource (System.Object serverResource, System.Type serverType, System.Type extendedType) [0x00000] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.Common.ClientTypeMapper.WrapResource (System.Object serverResource, System.Type serverType, System.Type extendedType) [0x00000] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.Common.ExtendedResources.ExtendedResourceExtensions.Wrap[TOriginal,TExtended] (TOriginal resource) [0x0000f] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.SystemTests.Linq.ExtendedResourceClientTests.Patch_SetOverlayedComplexProperty_ToNull_IsSuccessful () [0x0002d] in <859d6206e613478d8b4468be505726f1>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
--TargetInvocationException
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00014] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at Pomona.Common.Proxies.RuntimeProxyFactory`2[TProxyBase,T].Create () [0x00000] in <72dd24ed3fe341058226d6737979890b>:0
  at Pomona.Common.Proxies.RuntimeProxyFactory.Create[TProxyBase,T] () [0x00000] in <72dd24ed3fe341058226d6737979890b>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
--TypeInitializationException
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
--AmbiguousMatchException
  at System.RuntimeType.GetField (System.String name, System.Reflection.BindingFlags bindingAttr) [0x0006b] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.RuntimeType.GetField (System.Reflection.FieldInfo fromNoninstanciated) [0x00025] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Reflection.Emit.FieldBuilder.RuntimeResolve () [0x0000b] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at System.Reflection.Emit.ModuleBuilder.RuntimeResolve (System.Object obj) [0x00030] in <ab2f5ad0f8c84dfe97dfd6a06a64cf44>:0
  at Pomona.Common.Proxies.ITestParentClientResource_ExtendedResourceBase`1..cctor () [0x00000] in <5769049a25a8447986d3bb1f4909906b>:0
```

The last one seems to be related to #2423, since there's an `AmbiguousMatchException` and proxy in there. So I'll focus on the first problem, although I'd like #2423 merged so I can try that out to see if it helps Pomona's tests on Mono as well.

Since the `NullReferenceException` seems to have been caused by a `TargetInvocationException` somehow, how should I best move forward to create a test for this?

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs (hunk 3 above)
Comment (asbjornu) [reply src/NUnitFramework/framework/Internal/Results/TestResult.cs]: Is there any reason why `RecordException(Exception)` does not directly invoke `RecordException(Exception, FailureSite)` or the other way around? I can tackle that in this PR if you can tell me why much of the functionality inside the methods are duplicated in the first place. 😃

**Comment by asbjornu** [comment]
@jnm2, @ChrisMaddock: I'm currently halted on this due to missing answers to my above questions and findings. It would be highly appreciated if you could provide your wisdom so I can proceed. 😃

**Comment by jnm2** [comment]
Hey sorry, thanks for the ping. The `AmbiguousMatchException` is thrown by the type initializer for `Pomona.Common.Proxies.ITestParentClientResource_ExtendedResourceBase` (are you emitting a static constructor?) so I don't see any way it could be connected to #2423 which deals exclusively with NUnit's `PropertyConstraint`. Though I would like to see #2423 merged too. 😁

**Comment by jnm2** [comment]
As to the second question, all we have to do is provoke the original error so that the NRE happens *before* your changes and then assert that NRE doesn't happen so that your changes make the test start passing. To do that we need a minimal repro of the NRE bug. I'll see what that might take.

**Comment by jnm2** [comment]
The proper unit test for the NRE is no more complex than directly calling `NUnit.Framework.Internal.ExceptionHelper.BuildMessage` and pass it an NUnitException (and also a TargetInvocationException) with no inner exception. No exception should be thrown.

**Comment by jnm2** [comment]
As far as an integration test for the NRE which involves more moving parts, that's only valuable to catch parts that the unit test cannot catch. It's not a bad idea in case ExceptionHelper is not the only place a problem could occur, but it may also not be worth the effort.

**Comment by jnm2** [comment]
Looks like Mono allows you to throw a `null` exception object- either that, or a non-exception object was thrown and Mono safe-cast it instead of [wrapping it](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception).

**Comment by jnm2** [comment]
I'm totally failing to find any way to get Cake to run our tests on Mono in Windows, so...

**Comment by jnm2** [comment]
And running NUnit.Console on Mono manually never shows progress for either 32-bit or 64-bit for ten minutes. I suspect they've hung?

**Comment by jnm2** [comment]
Using the mono docker script it gets a little further, but always hangs after printing this test name: `NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingTestFixture`. Are we broken on th elatest release of mono?

**Comment by ChrisMaddock** [comment]
@asbjornu - Sorry. Please ping any time, I tend to drown under notifications from nunit a little! 😄 

This is a good stack trace! 😄 NUnitException should always have an inner exception - imo, it's a bug if it doesn! Looking at your trace - it looks like mono must be throwing a TargetInvocationException with no inner exception [on this line](https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Internal/Reflect.cs#L215). On windows, I believe there's always an InnerException for a TargetInvocationException - I don't use mono enough to know what's normal.

Therefore I suggest a few fixes!
1. On the line above - if the TargetInvocationException's innerexception is null, we should pass the TargetInvocationException itself into NUnitException - rather than the null InnerException.
2. [This fix](https://github.com/nunit/nunit/pull/2453/files#diff-cb5398a3c804f3f457c99595afb549a7R503) to Record Exception - which you've already done!

For tests, I'd suggest:
1. Tests that `BuildMessage()` produce a sensible message when passed either an NUnitException or TargetInvocationException with no inner exception. (The former, we'd never expect to happen - but we should still do something sensible if it does!)
2. Tests that [Reflect.InvokeMethod()](https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Internal/Reflect.cs#L200) will throw an NUnitException with the TargetInvocationException as it's inner exception, if the MethodInfo invoked throws a TargetInvocationException with NullReferenceException. It should be possible to manually build a methodinfo to do that, I believe.

> Interestingly, a new failure has now also surfaced. This test and quite a few others is causing the following exception:

This looks like a totally different method. Could you try running your tests against the [current master build](https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-dev-04480/artifacts)? I wonder if we've broken something. 😞 

> Are we broken on the latest release of mono?

According to Travis's understanding of 'latest mono' - no, but I see that's a few versions behind the actual latest release. It's more than likely - new mono releases have quite often exposed problems before. 😞

**Comment by CharliePoole** [comment]
Mono uses "latest" to mean the latest stable build. You shouldn't normally run against anything newer than that.

**Comment by jnm2** [comment]
@asbjornu We've made a lot of changes and we're on Mono 5.2.0 (soon Mono 5.4.1). If you've run out of time or interest, would you like a team member to take over?

**Comment by asbjornu** [comment]
@jnm2: Thanks for the ping. I've not lost interest, but time is indeed a problem. As I haven't been programming much of late and probably won't be for a while either, it might be best if someone else takes over this one. I've rebased my changes on the latest master and force pushed, so it should be in good shape to move forward.

**Comment by jnm2** [comment]
@asbjornu No problem. Thanks for getting us here!

@nunit/framework-team I changed the label until a team member picks this up.

**Comment by jnm2** [comment]
It's been half a year. I'm going to pull this one through.

File: src/NUnitFramework/framework/Guard.cs [hunk 4]
```diff
@@ -39,7 +39,7 @@ internal static class Guard
         public static void ArgumentNotNull(object value, string name)
         {
             if (value == null)
-                throw new ArgumentNullException("Argument " + name + " must not be null", name);
+                throw new ArgumentNullException(name, "Argument " + name + " must not be null");
```
Comment (jnm2) [inline src/NUnitFramework/framework/Guard.cs]: 😬

**Comment by jnm2** [comment]
@nunit/framework-team Please review!

/cc @asbjornu

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 5]
```diff
@@ -584,6 +551,49 @@ public void RecordTearDownException(Exception ex)
...
+        {
+            Guard.ArgumentNotNull(ex, nameof(ex));
+
+            if ((ex is NUnitException || ex is TargetInvocationException) && ex.InnerException != null)
+                return ex.InnerException;
+
+            return ex;
+        }
+
+        private struct ExceptionResult
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs]: This is much cleaner. I think we need to do more of this. 👍

File: src/NUnitFramework/tests/Internal/Results/TestResultApiTests.cs [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+            foreach (var method in RecordExceptionMethods)
+            foreach (var result in TestResults)
+            {
+                Assert.That(
+                    () => method.Invoke(result, null),
+                    Throws.ArgumentNullException.With.Property("ParamName").EqualTo("ex"));
+            }
+        }
+
+
```
[the remark this answers is not in the document]
Comment (jnm2) [reply src/NUnitFramework/tests/Internal/Results/TestResultApiTests.cs]: Huh. Does it ever bug you when people double-space between sentences? I've noticed that no professional typography uses double spaces, but I still see people using it. Maybe because that was the recommendation back in the monospace era (no kerning)?
