### PR TITLE
Issue #196: Compare DateTimeOffsets including the offset in the comparison

### LINKED ISSUE #196: Compare DateTimeOffsets including the offset in the comparison
This came from a bug in our code where someone had used "Convert.ToDateTime" when they should have used "DateTimeOffset.Parse"; but the unit test passed, indicating that there was no problem. Here is some code to replicate the issue.

			DateTime localDateTime = new DateTime(2014, 1, 30, 12, 34, 56);
			TimeSpan localTimeOffsetFromUtc = new TimeSpan(6, 15, 0);
			DateTimeOffset expected = new DateTimeOffset(localDateTime, localTimeOffsetFromUtc);

			string value = new XAttribute("x", expected).Value;
			DateTimeOffset actual = Convert.ToDateTime(value); // They should have used DateTimeOffset.Parse

			Assert.That(actual, Is.EqualTo(expected)); // Expect this to fail because (for example) the DateTime and Offset values are different (but this assertion passes!). For example, the next two asserts will fail.
			Assert.That(actual.DateTime, Is.EqualTo(expected.DateTime));
			Assert.That(actual.Offset, Is.EqualTo(expected.Offset));

### PR DESCRIPTION
**Pull request by voloda**
There is a lot of comments in the issue #196 notes and I am not familiar with DateTimeOffset so hopefully I got this correctly.

One thing I realized - if implemented this way it will not support Tolerance property. On the other hand I am a bit unsure how that could be supported if both parts will be used in comparison.

Fixes #196.

### CODE REVIEW

**Comment by CharliePoole** [comment]
I assumed that you would return false if the offsets were different and otherwise return the result of comparing just as a DateTime. Tolerance would only apply if the offsets matched.

However, I've never used DateTimeOffset myself, so let's wait for some other input. I'd like to see a comment from @RichardReeves, who made the request and from one more person in the @nunit/core-team.

**Comment by oznetmaster** [comment]
I do use DateTimeOffset.

 

This is tricky.  What if the offsets are different, but the time+offset of each is the same.  Are they then the same?

**Comment by oznetmaster** [comment]
Thinking about it more, it seems to me that two DateTimeOffset are equal if DateTimeOffset.UtcDateTime+DateTimeOffset.Offset are the same for both.

 

That would mean that Tolerance should always be applied, but to that sum.

**Comment by CharliePoole** [comment]
@oznetmaster That makes a lot of sense to me and I'm pretty sure we already do it. @RichardReeves originated the request because he wanted a special way to compare DTOs that would essentially require _exact_ equality - same UTC and same TZ. See the discussion on issue #196.

**Comment by oznetmaster** [comment]
This is confusing.

 

I definitely see that two DTO’s that have the same UtcDateTime value represent the same time point.  The offset only maps them to a specific time zone.

 

Even Tolerance should seemingly be applied only to the UtcDateTime value of the DTO.

 

I am not sure about the efficacy of ever automatically using the Offset of the DTO for assertions.  I would think that if the Offset was important to the test, then it should be used specifically in the assertion?

**Comment by oznetmaster** [comment]
I am still having a problem with this :(

Why is this any better then just comparing the DTO and then comparing the DTO.Offset, in the same assertion?  Why special case this?

I am sure there are similar situation related to DateTime (like comparing DateTime.Kind).

I actually see no reason for this.

**Comment by CharliePoole** [comment]
@oznetmaster We agree we should be doing as you say. EqualConstraint on DTOs should be interpreted as stating that the two represent the same point in  time. I thought we were doing that, but if not, let's file a bug.

However, some applications are not testing the time value but that the same time is recorded in the same way in two different places. You are suggestion that two asserts be used.

We got this request back in August and had a lot of discussion about it. We said we would do it through a modifier. I hesitate to go back on that now without a good reason, but I'd like to hear from others. Did we make a mistake in agreeing to do this?

**Comment by CharliePoole** [comment]
@oznetmaster Re-reading your comment, I'm not sure I understand "comparing the DTO and then comparing the DTO.Offset, in the same assertion." How would you do that - i.e. what syntax?

**Comment by oznetmaster** [comment]
For instance:

 

Assert.That (dto1 == dto2 && dto1.Offset == dto2.Offset, Is.True);

 

Or

 

Assert.IsTrue (dto1 == dto2 && dto1.Offset == dto2.Offset);

**Comment by CharliePoole** [comment]
I see... I was trying to think of a way using EqualTo. My assumption (but only that) is that the requestor wants a single assert that will give an intelligent message. That's why I'm hoping he will comment here. 

Like you I don't see a strong need for this. I would do something like...

Assert.That(dto1, Is.EqualTo(dto2));
Assert.That(dto1.Offset, Is.EqualTo(dto2.Offset));

in order to get an appropriate error message.

Let's wait for others to comment.

**Comment by oznetmaster** [comment]
If we are going to do this, then we should do the same for DateTime, like WithSameKind.

 

But I still do not see the need.  My solution is a single assert with a single method.

**Comment by oznetmaster** [comment]
If we are going to do this, then we should do the same for DateTime, like WithSameKind.

 

But I still do not see the need.  My solution is a single assert with a single message.

**Comment by oznetmaster** [comment]
It seems like this could be a case for a custom constraint?

**Comment by RichardReeves** [comment]
Wow... loads of things to respond to... let me try to cover them all...

Issue #196 shows the evolution of my thought process, from the inital knee-jerk "surely that's a bug with NUnit" through the understanding of what's going on, to a proposed solution using an actual coded example (which we're now using at our company).

@voloda: I'm not expert in the NUnit functionality, but looking at the changesets, it looks like the change that has been made made would make the "Equal" constraint for DateTimeOffsets fail if the Offset is different for the two DateTimeOffsets being compared. I don't think that's the right solution, and this is the key point:

*Key point* Microsoft decided that when you compare two DateTimeOffsets, it will consider them to be equal if the UtcDateTime value is the same. Just to be clear, I'm talking about the equality operator for DateTimeOffsets in Microsoft.Net, nothing to do with NUnit. For example if you wrote "if (dateTimeOffset1 == dateTimeOffset2)" in C#. I would argue that this was a mistake by Microsoft - the DateTimeOffset object offers a "UtcDateTime" property. So if I wanted to *just* compare the UtcDateTime of two operands (and ignore the offsets), then I could do that by comparing the value of that property for the two operands. I suspect that the Microsoft developers thought "well, when you are comparing two DateTimeOffsets, you are really only interested in whether they represent the same point in time (e.g. for sorting purposes)"; and they just ignored the Offset. And in most cases, they are probably right; but I think that was a mistake. They could have offered something similar to "string.Compare", which allows you to specify what you consider equality to be. But they didn't. NUnit is called that because it is a testing framework for Microsoft.Net. So I would expect NUnit's Equality check to be consistent with what I would see with "==" in C#. And it is (in the currently released version). So this is really just a learning point for developers about how DateTimeOffset equality works; and that we need a way of phrasing what we need in NUnit if we need something different.

@voloda said "if implemented this way it will not support Tolerance property". That's because the tolerance can only be applied where one value is being compared with another (and I think that's what @voloda was saying). In this case, there are two values: the UtcDateTime and the Offset. You *cannot* combine these into a single value (it would be like trying to combine x- and y-coordinates: they might look like the same type, but they have different purposes), and therefore the tolerance cannot be applied. However, you could theoretically apply a tolerance to one or the other, or both (I'm not sure how...).

@oznetmaster said "I am not sure about the efficacy of ever automatically using the Offset of the DTO for assertions.  I would think that if the Offset was important to the test, then it should be used specifically in the assertion?". Yes. Exactly. And that what what my solution proposes; but I don't think that is what has been done. And I think that's what @oznetmaster then picked up on in his next points, in particular he mentions the fact that DateTime comparisons suffer a similar issue for "Kind" (which I also mention in my original post, along with a solution for that, using a similar approach); so I appreciate his support, if that could be implemented as well

@CharliePoole said "EqualConstraint on DTOs should be interpreted as stating that the two represent the same point in time. I thought we were doing that, but if not, let's file a bug." Don't worry, that's exactly what the released version does; but I'm not sure that's what this proposed fix does.

@CharliePoole said "I'm not sure I understand "comparing the DTO and then comparing the DTO.Offset, in the same assertion." How would you do that - i.e. what syntax?" to which @oznetmaster offered a solution. I would also refer you back to the original proposal, for which the syntax is:

			Assert.That(value1, Is.EqualTo(value2).WithSameOffset());

and the example code that I gave (for DateTimeOffset) gives a suitable error message. It's only the example code for DateTime's Kind that does not give a helpful error message (I don't know how to do that).

In case it helps, here is a very basic scenario explaining what we are trying to test - it may help you visualise our problem. We have a DateTimeOffset value, and we are storing it in a (MS SQL) database. We also have code to retrieve the value. We need to test that if we store and retrieve a DateTimeOffset, that we get the same value back. Notice that if we just test for equality of the "before" and "after" value, then any loss of the Offset (for example, if they just saved the Utc value) would not be noticed, and the test would pass; even though the Offset was different. Given the key point above, we accept that
			Assert.That(value1, Is.EqualTo(value2));
should not be changed to support this (which I think is what *has* been done in this changeset) but that (as @CharliePoole suggested) we need a modifier so that if we care about it, we can still test it in a single assertion, for example:
			Assert.That(value1, Is.EqualTo(value2).WithSameOffset());

There is a similar case for the DateTime. All of our DateTimes are stored in the database as UTC value. By default, when they are read from the database (with MS Enterprise Library Data block) they arrive with Kind = "Unknown". But the Kind is important to us: if the Kind is not set to Utc, then we won't get the right value when we call ToLocalTime() on it. So we need our tests to ensure that the Kind coming out is the same that went it; which we don't get with the comparison of DateTimes. Again, this is consistent with Microsoft: it ignores the Kind. For example, if you understand what "Kind" means, then it might surprise you that this Assert Fail gets called:
			DateTime utcDateTime = new DateTime(2014, 1, 30, 12, 34, 56, DateTimeKind.Utc);
			DateTime localDateTime = new DateTime(2014, 1, 30, 12, 34, 56, DateTimeKind.Local);
			if (localDateTime == utcDateTime)
			{
				Assert.Fail();
			}
Hope this helps
Richard

**Comment by CharliePoole** [comment]
@RichardReeves Thanks for the response. I think you made your case (again). I had forgotten that you previously talked about database testing.

I think that the tests are key here:

1. Summarizing: we need to make sure that our EqualsConstraint passes whenever the MS == operator would return true, and fails when it would fail. Sounds like a good place to add a [Theory]. 

2. We also need to ensure that two values with different Offsets always fail, even if the DT values are equal and even if the UTC values are equal. Another theory.

3. We need to ensure that two values with the same UTC and same Offset always pass. Yet another! 

4. We'll also want tests to ensure that the failing cases give intelligent messages.

This has moved out of what I would have called an 'easyfix' but not too far. :-)

@voloda Are you OK with that? Can you start by ensuring that we have tests for the above, even if they are currently failing? Are you familiar with using theories? If not, I can post an example.

@oznetmaster As I said, I think @RichardReeves has made his case here. Because it's a narrow use case, it makes sense to require the extra keystrokes to modify the comparison. The default should remain as strictly comparing the UTC time and should always match what C# calls equality.

@rprouse You were part of the original discussion. Do you agree that persisting in this direction makes sense?

Eventually, we should create an issue and do the same thing for DateTime's Kind.

**Comment by rprouse** [comment]
There is a whole bunch of text here, so let me summarize to make sure we are all on the same page. I think that what @RichardReeves is asking for is the following.

1. Ensure that `Assert.That(value1, Is.EqualTo(value2))` for two DateTimeOffsets works the same as `if( value1 == value2 )` in .NET. This means that equality should just apply to the same point in time (UTC values are equal).
2. Add a modifier to `EqualConstrain` for `DateTimeOffset` called `WithSameOffset` that modifies equality to also take into account the offset. If this is called, then UTC must be equal and the offset must be equal.
3. Tolerance should be applied to the UTC point in time when determining equality.

If this is what everyone else is saying, then I agree :+1: 

As @oznetmaster says, our support for `DateTime.Kind` should probably be the same. For equality, it should behave the same as .NET and we could add a `WithSameKind` to the equality constraint.

My only issue is that we are adding so many different modifiers to `EqualConstraint`, many of which are very type specific. I wonder if we should instead add overloads to `Is.EqualTo` for these types and return a `DateTimeEqualConstraint` and a `DateTimeOffsetEqualConstraint` to that we can tack the modifiers on those?

**Comment by CharliePoole** [comment]
@rprouse That's it exactly. I also agree with you on the non-type-safe proliferation of modifiers to EqualC0nstraint. Let's look at doing some refactoring there, but not as a part of this issue. I think there's some thought needed to decide if we should just refactor on the constraint side or if we also need to add overloads of the "classic" asserts - which I'd rather not do.

**Comment by voloda** [comment]
@CharliePoole Theories are new concept to me - see the updated PR whether I used them correctly

@rprouse Could you please check test cases whether they match your expectation. In particular I am not confident about the UTC comparison.

In general I agree that WithSameOffset and other modifiers are a bit confusing since they apply based on various internal datatypes evaluations.

**Comment by CharliePoole** [comment]
It looks like you got caught up in the bad merge we just did. Wait till it's reverted and then re-synch with master.

**Comment by voloda** [comment]
@CharliePoole I rebased it onto fresh master and it seems to be passing - please check that theories are what you expect it and are written in correct way

File: src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs [hunk 1]
```diff
@@ -180,6 +180,79 @@ public void ErrorIfTicksPrecedesWithin()
...
+            {
+                Assume.That(value1 != value2);
+
+                Assert.That(value1, Is.Not.EqualTo(value2));
+            }
+
+            [Theory]
+            public void PositiveEqualityTestWithTolerance(DateTimeOffset value1, DateTimeOffset value2)
+            {
+                Assume.That((value1 - value2).Duration() <= new TimeSpan(0, 1, 0));
```
Comment (CharliePoole) [inline src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs]: What if value2 > value1? Do you need some sort of abs function for TimeSpans?

**Comment by CharliePoole** [comment]
The implementation and tests look good with the only exception being the comment I made about value2 > value1. As it stands, you are excluding those cases.

File: src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs (hunk 1 above)
Comment (voloda) [inline src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs]: According to [MSDN](https://msdn.microsoft.com/en-us/library/system.timespan.duration%28v=vs.110%29.aspx) the Duration() method should return absolute value already so we should be good. Btw. I took that from original implementation of Tolerance support

Comment (CharliePoole) [inline src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs]: In that case I'm ok work it. Anyone else?

**Comment by CharliePoole** [comment]
@nunit/core-team Looking for a second committer review in order to merge.
