### PR TITLE
Issue5178 generic array parameter

### LINKED ISSUE #5178: Passing IEnumerable<object> from TestCaseSource to a generic method seems to break in some cases
Issue Repro : https://github.com/nunit/nunit.issues/tree/main/Issue5178

I've noticed that code like the following can fail on upgrade from NUnit 4.4 -> 4.5.1 with the message "Too many arguments provided, provide at most 1 arguments."

Changing the method from generic to non-generic and from `IEnumerable<T>`  -> `IEnumerable<object>` permits the test to pass again. The code sample was found in a fellow OSS project, https://github.com/ClosedXML/ClosedXML

```diff
[TestCaseSource(nameof(ArraySources))]
-public void SampleMethod<T>(IEnumerable<T> data)
+public void SampleMethod(IEnumerable<object> data)
{
    Assert.Pass();
}

private static IEnumerable<object> ArraySources
{
    get
    {
        yield return new int[][]
        {
                new[] {1, 2, 3},
                new[] {4, 5, 6}
        };
        yield return new List<List<double>> { new List<double> { 1.0, 2.0, 3.0 } };
        yield return (new int[][]
        {
                new[] {1, 2, 3},
                new[] {4, 5, 6}
        }).AsEnumerable();
        yield return new Array[]
        {
                Array.CreateInstance(typeof(decimal), 5),
                Array.CreateInstance(typeof(decimal), 5),
        };
    }
}
```

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #5178 

See discussion in issue.
There is a new match on generic argument and when the method only expects a single argument, don't unpack.

### CODE REVIEW

File: src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs [hunk 1]
```diff
@@ -313,6 +313,37 @@ private static IEnumerable<TestCaseData> NoCommonBaseClassData()
...
+            where T : notnull
+            => Assert.That(data.GetType(), Is.EqualTo(typeof(int[][])));
+
+        [TestCaseSource(nameof(IntegerArrays))]
+        public static void MethodWithSingleParameter(int i)
+        {
+        }
+
+        [TestCaseSource(nameof(IntegerArrays))]
+        public static void MethodWithThreeParameters(int i, int j, int k)
```
Comment (stevenaw) [inline src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs:338]: Thanks for adding all the test coverage.

I'm curious to test this and the above on 4.4 to compare. I had thought the array would only unpack if it's an `object[]`. I can likely try that later this afternoon for me. I'm not against this behaviour; I'd just be curious if we're introducing a new behaviour.

Comment (manfred-brands) [reply src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs:338]: 4.4 according to the code snippet you put in the issue, unpacks if the array length matches the number of parameters. There is no test on object at all.

Comment (stevenaw) [reply src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs:338]: Hm. I just quickly tested and you are right. I recall seeing an `object[]` check elsewhere but it doesn't seem to affect this as this test passes on 4.4 as well

File: src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs [hunk 2]
```diff
@@ -313,6 +313,37 @@ private static IEnumerable<TestCaseData> NoCommonBaseClassData()
...
+        [TestCaseSource(nameof(ArraySources))]
+        public static void GenericNestedArray<T>(IEnumerable<T> data) => Assert.That(data.GetType(), Is.EqualTo(typeof(int[][])));
+
+        [TestCaseSource(nameof(ArraySources))]
+        public static void GenericWithArraySource<T>(T data)
+            where T : notnull
+            => Assert.That(data.GetType(), Is.EqualTo(typeof(int[][])));
+
+        [TestCaseSource(nameof(IntegerArrays))]
+        public static void MethodWithSingleParameter(int i)
```
Comment (stevenaw) [inline src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs:333]: There was a bit of discussion in the issue about this, where you mentioned

> This fails as well because ShouldUnpackArrayAsArguments returns true and it creates a test case with 3 arguments.
IN 4.4.0 this, imho correctly says: Object of type 'System.Int32[]' cannot be converted to type 'System.Int32'.

I agreed with you and with the 4.4 behaviour. Did we want this to fail now again?

Comment (manfred-brands) [reply src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs:333]: It does now, see my added test.

Comment (stevenaw) [reply src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs:333]: Ah. I had missed that this was in `testdata`.
Ok thanks @manfred-brands . I don't think I have any other questions or concerns. I'll do a final review when I can get to a computer this afternoon
