### PR TITLE
Failing stack length test now shows stack trace

### LINKED ISSUE #2446: CI failure in mono Warning tests
Just seen a new mono CI failure I haven't seen before - .NET 4.0 build only. It's flakey - it went away on a rebuild.

https://travis-ci.org/nunit/nunit/jobs/276500189

```
1) Failed : NUnit.Framework.Assertions.WarningTests.StackTracesAreFiltered("WarningAfterAwaitTaskDelay",3)
  Expected: less than or equal to 3
  But was:  5
  at NUnit.Framework.Assertions.WarningTests.StackTracesAreFiltered (System.String methodName, System.Int32 maxLineCount) [0x000ac] in <c07632bf29c04487b0d0b138c27780c6>:0 
```

@jnm2 - would you mind taking a look? I know you did some work here recently 🙂

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2446 for now.

### CODE REVIEW

File: src/NUnitFramework/tests/Assertions/WarningTests.cs [hunk 1]
```diff
@@ -283,9 +284,19 @@ public static void StackTracesAreFiltered(string methodName, int maxLineCount)
...
+            var lines = warningStackTrace.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries);
 
-            Assert.That(lineCount, Is.LessThanOrEqualTo(maxLineCount));
+            if (maxLineCount < lines.Length)
+            {
+                Assert.Fail(
+                     $"Expected the number of lines to be no more than {maxLineCount}, but it was {lines.Length}:" + Environment.NewLine
+                     + Environment.NewLine
+                     + string.Concat(lines.Select((line, i) => $" {i + 1}. {line.Trim()}" + Environment.NewLine))
+                     + "(end)");
```
Comment (CharliePoole) [inline src/NUnitFramework/tests/Assertions/WarningTests.cs]: Why not just use three- or four-argument form of assert?

**Comment by mikkelbu** [comment]
And we already got the error on Travis (see https://travis-ci.org/nunit/nunit/jobs/278646567)

```
1) Failed : NUnit.Framework.Assertions.WarningTests.StackTracesAreFiltered("WarningAfterAwaitTaskDelay",3)
Expected the number of lines to be no more than 3, but it was 5:
 1. at NUnit.TestData.WarningFixture+<WarningAfterAwaitTaskDelay>c__async0.MoveNext () [0x00000] in <6d572c18933f4f05a3ecdb365102bc1a>:0
 2. at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <e7f885eed4414fa7a0b0299cf28ef84f>:0
 3. at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <e7f885eed4414fa7a0b0299cf28ef84f>:0
 4. at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <e7f885eed4414fa7a0b0299cf28ef84f>:0
 5. at NUnit.TestData.WarningFixture.WarningAfterAwaitTaskDelay () [0x00000] in <6d572c18933f4f05a3ecdb365102bc1a>:0
(end)
  at NUnit.Framework.Assertions.WarningTests.StackTracesAreFiltered (System.String methodName, System.Int32 maxLineCount) [0x00110] in <d8d4ba8d678f415aa46a1929f660baed>:0 
```

File: src/NUnitFramework/tests/Assertions/WarningTests.cs (hunk 1 above)
Comment (jnm2) [reply src/NUnitFramework/tests/Assertions/WarningTests.cs]: Hey, I'm not familiar with that. What would that look like?

**Comment by jnm2** [comment]
Cool! Looks like bumping to 5 is what we want. I'll add that to this PR

File: src/NUnitFramework/tests/Assertions/WarningTests.cs (hunk 1 above)
Comment (CharliePoole) [reply src/NUnitFramework/tests/Assertions/WarningTests.cs]: You can do

```C#
Assert.That(lines.Length,
            Is.LessThanOrEqualTo(maxLineCount), 
            $"Expected the number of lines to be no more than {maxLineCount}, but it was {lines.Length}:" 
               + Environment.NewLine
               + Environment.NewLine
               + string.Concat(lines.Select((line, i) => $" {i + 1}. {line.Trim()}" + Environment.NewLine))
               + "(end)");
```

The message is constructed before the call. Usually efficiency is not a great concern in assert messages but if you are concerned you can use a lambda returning a string.

Comment (jnm2) [reply src/NUnitFramework/tests/Assertions/WarningTests.cs]: Ah, using `Assert.That`. I chose not to use it because I wanted the stack after the expected number of lines message and didn't want the message repeated in two places.

**Comment by jnm2** [comment]
PR now completely addresses #2446.

**Comment by CharliePoole** [comment]
Weird! I approved this once although I added a comment. Do approvals disappear after you make changes?

**Comment by jnm2** [comment]
@CharliePoole yes, they disappear if you rebase so that the commit hash you approved no longer exists. I accidentally indented by five spaces instead of four and amended that commit before pushing the second commit.
