### PR TITLE
Eliminate spurious AssertionResults from Assert.Throws

### LINKED ISSUE #1914: Extra AssertionResult entries in TestResults
There are a few situations where spurious AssertionResult entries are created in the result:

1. Assert.Throws or ThrowsConstraint when the code executed by the delegate argument includes asserts. The second-level asserts may leave failure and warning entries in the result that is being used for the top level test.

2. Executing code that causes an AssertionException and then catches it. This is done in some of our NUnit tests and it's a "trick" used by some users. The failure represented by the exception is added to the result before we can catch it.

3. Any Assert that takes a delegate could theoretically do the same thing if there were Asserts in the code executed. However, this is something of a pathological situation, since there isn't much reason to use Asserts in such delegates.

To resolve this, all such "second level" code should be executed in an isolated context and should apply to a separate result, which is ignored by the top-level code.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #1914 

This fixes the problem of second-level asserts, run under Assert.Throws or ThrowsConstraint, leaving AssertionResults for their failures in the current result. I've verified manually that the output of our test run doesn't include any `<assertion>` elements.

### CODE REVIEW

File: src/NUnitFramework/tests/Assertions/LowTrustFixture.cs [hunk 1]
```diff
@@ -61,7 +61,12 @@ public void AssertEqualityInLowTrustSandBox()
             });
         }
 
-        [Test, Platform(Exclude="Mono,MonoTouch", Reason= "Mono does not implement Code Access Security")]
+        //[Test, Platform(Exclude="Mono,MonoTouch", Reason= "Mono does not implement Code Access Security")]
+        // TODO: This test fails to run correctly when Assert.Throws
+        // attempts to create an isolated TestExecutionContext.
+        // The TestExecutionContext class would have to be modified
+        // in order to allow chaining of contexts across a 
+        // remoting boundary.
```
Comment (rprouse) [inline src/NUnitFramework/tests/Assertions/LowTrustFixture.cs]: @CharliePoole do you think this is something that we should continue to support? Should an issue be created?

Comment (CharliePoole) [inline src/NUnitFramework/tests/Assertions/LowTrustFixture.cs]: I thought of a way to fix it so I will create an issue. We used to have a request for attributing tests to run in a separate domain, but I think we got rid of it. We also have a few issues around user-created AppDomains ( #42 and #71 ) which may have a similar cause to this. I'll put details in the issue.
