### PR TITLE
Issue 670

### LINKED ISSUE #670: Failing Tests in TeamCity Build
2 tests are currently failing the TeamCity build

https://teamcity.jetbrains.com/project.html?projectId=NUnit_NUnit3_BuildAndTest

NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoEqual
NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual 

```cs
System.ArgumentException : The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoEqual()
```

I believe this happens because the teamcity agent running the test is a service account with no My Documents folder.

### PR DESCRIPTION
**Pull request by michal-franc**
Fixes #670 

The tests that were using TestDirectory probably were always ignored due to an issue in TestDirectory creation.

### CODE REVIEW

File: src/NUnitFramework/tests/TestUtilities/TestDirectory.cs [hunk 1]
```diff
@@ -42,6 +42,7 @@ public TestDirectory()
             Assume.That(_testDir.Exists, Is.False, _testDir + " should not already exist");
 
             _testDir.Create();
+            _testDir.Refresh();
             Assume.That(_testDir.Exists, Is.True, "Failed to create test dir " + _testDir);
```
Comment (CharliePoole) [inline src/NUnitFramework/tests/TestUtilities/TestDirectory.cs]: I no longer recall why this is an assumption and not an assertion. Check that we catch any failure someplace else.

**Comment by CharliePoole** [comment]
Looks good. Appveyor failure appears unrelated - I restarted it.

File: src/NUnitFramework/tests/TestUtilities/TestDirectory.cs (hunk 1 above)
Comment (rprouse) [inline src/NUnitFramework/tests/TestUtilities/TestDirectory.cs]: I think these are assumptions because we are not testing creating a test directory, that is just setup for another test. So, if say we don't have permissions to create the directory, then that other test hasn't failed, we just haven't met the prerequisites for running that test. Pretty fine line though, it could be either way :smile:

**Comment by rprouse** [comment]
Looks good to me too and CI is now passing. Merging.
