### PR TITLE
Fix for failure to retry when tests have no setup and teardown

### LINKED ISSUE #2325: Retry attribute doesn't retry the test.
I've already used assert.true(), but it doesn't retry the test.

```c#
[Test, Order(2)]
[Retry(3)]
public void Login()
{
    step.BasicActions.LoginAndOpenPart15038(_driver);
    Assert.True(false == _driver.Url.Contains("login.html"));
}
```

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2325

(The fourth commit is an example of the TestCommand API being a little unsettling for me. I wonder if there's a way to make it less magical in the future.)

### CODE REVIEW

**Comment by rprouse** [comment]
☹️ 

1) Failed : NUnit.Framework.Assertions.CollectionAssertTest.PerformanceTests(System.Collections.Generic.List`1[System.Double])
Elapsed time of 153.3003ms exceeds maximum of 100ms

**Comment by jnm2** [comment]
@rprouse 

> ☹️

This is happening on basically every other run this evening. At least we're about to turn it into a warning.

**Comment by jnm2** [comment]
@ChrisMaddock, @CharliePoole: Would you like to review this drastically simpler fix?

File: src/NUnitFramework/framework/Attributes/RetryAttribute.cs [hunk 1]
```diff
@@ -91,7 +91,15 @@ public override TestResult Execute(TestExecutionContext context)
 
                 while (count-- > 0)
                 {
-                    context.CurrentResult = innerCommand.Execute(context);
+                    try
+                    {
+                        context.CurrentResult = innerCommand.Execute(context);
+                    }
+                    catch (Exception ex)
```
Comment (CharliePoole) [inline src/NUnitFramework/framework/Attributes/RetryAttribute.cs]: Nice... I think I'd add a comment here. Something like "All inner commands, including those created by users, are supposed to handle exceptions themselves, but in case they don't we catch it here."

Of course, some of our own commands are not handling exceptions correctly as we know. But that's for a redesign, IMO.

Comment (CharliePoole) [reply src/NUnitFramework/framework/Attributes/RetryAttribute.cs]: I approved, so it's a suggestion. :smile:

Further suggestion would be to do it if more work is likely to wait a while rather than happening soon. I'm being cagey as I know I won't be doing it. 😈

Comment (jnm2) [reply src/NUnitFramework/framework/Attributes/RetryAttribute.cs]: I'm just not looking forward to waiting for CI all over again, but that's not a good reason not to add it! 😆

**Comment by jnm2** [comment]
Ready for review of comment commit.

**Comment by jnm2** [comment]
I could always review it myself just to merge it but that could enter grey area. =D

**Comment by CharliePoole** [comment]
I personally prefer the grey area. 😄

**Comment by rprouse** [comment]
@jnm2 for these "Approved with suggestions" and minor fixes, feel free to re-approve and merge yourself. I've been considering turning off the dismiss reviews because of this, but I would like to keep it on for non-team members 🙍‍♂️

**Comment by jnm2** [comment]
👂
