### PR TITLE
Catch potential exceptions from launching debugger

### LINKED ISSUE #2191: System.Reflection.TargetInvocationException with nunit3-console --debug on Mono
Attempting to run `nunit3-console --debug` 3.6.1 on Mono causes it to break due to the following error:
```
$ mono nunit3-console.exe --debug --inprocess ../../../SS14.UnitTesting/bin/Debug/SS14.UnitTesting.dll
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: MacOSX 16.5.0.0
  CLR Version: 4.0.30319.42000

Test Files
    ../../../SS14.UnitTesting/bin/Debug/SS14.UnitTesting.dll

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented.
  at System.Diagnostics.Debugger.Launch () [0x00000] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun (NUnit.Framework.Interfaces.ITestListener listener) [0x000c1] in <a136915bdafc4f7db46d0b0a906d5367>:0
  at NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync (NUnit.Framework.Interfaces.ITestListener listener, NUnit.Framework.Interfaces.ITestFilter filter) [0x0006f] in <a136915bdafc4f7db46d0b0a906d5367>:0
  at NUnit.Framework.Api.NUnitTestAssemblyRunner.Run (NUnit.Framework.Interfaces.ITestListener listener, NUnit.Framework.Interfaces.ITestFilter filter) [0x00000] in <a136915bdafc4f7db46d0b0a906d5367>:0
  at NUnit.Framework.Api.FrameworkController.RunTests (System.Web.UI.ICallbackEventHandler handler, System.String filter) [0x0001d] in <a136915bdafc4f7db46d0b0a906d5367>:0
  at (wrapper remoting-invoke-with-check) NUnit.Framework.Api.FrameworkController:RunTests (System.Web.UI.ICallbackEventHandler,string)
  at NUnit.Framework.Api.FrameworkController+RunTestsAction..ctor (NUnit.Framework.Api.FrameworkController controller, System.String filter, System.Object handler) [0x00006] in <a136915bdafc4f7db46d0b0a906d5367>:0
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <ffb99659fc1c47faa4d5f883014d08aa>:0
   --- End of inner exception stack trace ---


Server stack trace:
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00014] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00095] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Activator.CreateInstance (System.String assemblyString, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo, System.Threading.StackCrawlMark& stackMark) [0x00077] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Activator.CreateInstance (System.String assemblyName, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo) [0x00016] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.AppDomain.CreateInstance (System.String assemblyName, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityAttributes) [0x0000e] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at (wrapper remoting-invoke-with-check) System.AppDomain:CreateInstance (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at System.AppDomain.CreateInstanceAndUnwrap (System.String assemblyName, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityAttributes) [0x00000] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at (wrapper remoting-invoke-with-check) System.AppDomain:CreateInstanceAndUnwrap (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at (wrapper xdomain-dispatch) System.AppDomain:CreateInstanceAndUnwrap (object,byte[]&,byte[]&,string,string,bool)

Exception rethrown at [0]:
  at (wrapper xdomain-invoke) System.AppDomain:CreateInstanceAndUnwrap (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at (wrapper remoting-invoke-with-check) System.AppDomain:CreateInstanceAndUnwrap (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject (System.String typeName, System.Object[] args) [0x00000] in <7b0953727751470ab10f0e0b547b85ae>:0
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run (NUnit.Engine.ITestEventListener listener, System.String filter) [0x00030] in <7b0953727751470ab10f0e0b547b85ae>:0
  at NUnit.Engine.Runners.DirectTestRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x0002b] in <7b0953727751470ab10f0e0b547b85ae>:0
  at NUnit.Engine.Runners.AbstractTestRunner.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <7b0953727751470ab10f0e0b547b85ae>:0
  at NUnit.Engine.Runners.MasterTestRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00085] in <7b0953727751470ab10f0e0b547b85ae>:0
  at NUnit.Engine.Runners.MasterTestRunner.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <7b0953727751470ab10f0e0b547b85ae>:0
  at NUnit.ConsoleRunner.ConsoleRunner.RunTests (NUnit.Engine.TestPackage package, NUnit.Engine.TestFilter filter) [0x000d2] in <b0ef9cac03db4431890fe739906a4c7b>:0
  at NUnit.ConsoleRunner.ConsoleRunner.Execute () [0x000b6] in <b0ef9cac03db4431890fe739906a4c7b>:0
  at NUnit.ConsoleRunner.Program.Main (System.String[] args) [0x001bf] in <b0ef9cac03db4431890fe739906a4c7b>:0
```

Remove the `--debug` flag and everything works.

@ChrisMaddock determined on Gitter that it's caused by a bug in Mono: https://bugzilla.xamarin.com/show_bug.cgi?id=30489

### PR DESCRIPTION
**Pull request by ChrisMaddock**
In addition to the NotImplementedException thrown by mono, also catches SecurityExceptions, as per [MSDN docs](https://msdn.microsoft.com/en-us/library/system.diagnostics.debugger.launch(v=vs.110).aspx).

Fixes #2191

### CODE REVIEW

File: src/NUnitFramework/framework/Api/NUnitTestAssemblyRunner.cs [hunk 1]
```diff
@@ -296,7 +296,23 @@ private void StartRun(ITestListener listener)
...
+#if !(NETSTANDARD1_3 || NETSTANDARD1_6)
+                catch (SecurityException)
+                {
+                    TopLevelWorkItem.Test.MakeInvalid("System.Security.Permissions.UIPermission is not set to start the debugger.");
+                }
+#endif
+                //System.Diagnostics.Debugger.Launch() not implemented on mono
+                catch (NotImplementedException)
+                {
+                    TopLevelWorkItem.Test.MakeInvalid("Debugger unavailable on this platform.");
```
Comment (CharliePoole) [inline src/NUnitFramework/framework/Api/NUnitTestAssemblyRunner.cs]: You are making the test assembly invalid but what you really want is to make the result of the assembly invalid. This currently works, because we try to continue running and discover that the assembly is invalid, but it may not continue tl work correctly in the future. I think we actually need to mark the current (top level) __result__ as invalid and return without starting the run.

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole - see revised commit. That produces results xml more like what I'd expect too!
