### PR TITLE
Set culture on tests where comparing case of US English strings

### LINKED ISSUE #3414: Azure pipelines are failing on Linux
Between Friday 1st and Saturday 2nd Azure pipelines have started failing on Linux. Examining the logs the it seems that we have started using a new linux kernel in Ubuntu (from 4.15... to 5.0...). I have tried to verify this on https://github.com/microsoft/azure-pipelines-image-generation, but I cannot find the details.
EDIT: Apparently, we are now using Ubuntu 18.04 and not 16.04 - https://github.com/microsoft/azure-pipelines-image-generation/issues/506#issuecomment-548918601.

Before - https://nunit.visualstudio.com/NUnit/_build/results?buildId=2244
```
Runtime Environment
   OS Version: Linux 4.15.0.1059 
  CLR Version: 4.0.30319.42000
```
After - https://nunit.visualstudio.com/NUnit/_build/results?buildId=2253
```
Runtime Environment
   OS Version: Linux 5.0.0.1020 
  CLR Version: 4.0.30319.42000
```

Strangely this makes some of our test fail (all seem related to casing)
```
Errors, Failures and Warnings

1) Failed : NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentHonorsUsing
  Expected: True
  But was:  False

2) Failed : NUnit.Framework.Constraints.ContainsConstraintTests.HonorsIgnoreCaseForString
  Expected: True
  But was:  False

3) Failed : NUnit.Framework.Constraints.DictionaryContainsKeyConstraintTests.UsingIsHonored
  Expected: dictionary containing key "HELLO"
  But was:  < ["Hello", "World"], ["Hola", "Mundo"] >

4) Failed : NUnit.Framework.Constraints.DictionaryContainsValueConstraintTests.UsingIsHonored
  Expected: dictionary containing value "UNIVERSE"
  But was:  < ["Hello", "World"], ["Hi", "Universe"], ["Hola", "Mundo"] >

5) Failed : NUnit.Framework.Constraints.EqualConstraintTests+UsingModifier.UsesProvidedLambda_StringArgs
  String lengths are both 5. Strings differ at index 0.
  Expected: "HELLO"
  But was:  "hello"
  -----------^

6) Failed : NUnit.Framework.Constraints.EqualConstraintTests+UsingModifier.UsesProvidedPredicateForItemComparison
  Expected and actual are both <System.String[3]>
  Values differ at index [0]
  String lengths are both 4. Strings differ at index 0.
  Expected: "yeti"
  But was:  "YETI"
  -----------^

7) Failed : NUnit.Framework.Constraints.SamePathOrUnderTest_Windows.SucceedsWithGoodValues("C:\\Folder1\\Folder2")
  Expected: Path under or matching "C:\folder1\folder2"
  But was:  "C:\Folder1\Folder2"

8) Failed : NUnit.Framework.Constraints.SamePathOrUnderTest_Windows.SucceedsWithGoodValues("C:\\FOLDER1\\.\\junk\\..\\Folder2")
  Expected: Path under or matching "C:\folder1\folder2"
  But was:  "C:\FOLDER1\.\junk\..\Folder2"

9) Failed : NUnit.Framework.Constraints.SamePathOrUnderTest_Windows.SucceedsWithGoodValues("C:\\FOLDER1\\.\\junk\\..\\Folder2\\temp\\..\\Folder3")
  Expected: Path under or matching "C:\folder1\folder2"
  But was:  "C:\FOLDER1\.\junk\..\Folder2\temp\..\Folder3"

10) Failed : NUnit.Framework.Constraints.SamePathTest_Windows.RootPathEquality
  Expected: Path matching "C:\junk\..\"
  But was:  "c:\"

11) Failed : NUnit.Framework.Constraints.SamePathTest_Windows.SucceedsWithGoodValues("C:\\Folder1\\File.TMP")
  Expected: Path matching "C:\folder1\file.tmp"
  But was:  "C:\Folder1\File.TMP"

12) Failed : NUnit.Framework.Constraints.SamePathTest_Windows.SucceedsWithGoodValues("C:\\FOLDER1\\.\\folder2\\..\\File.TMP")
  Expected: Path matching "C:\folder1\file.tmp"
  But was:  "C:\FOLDER1\.\folder2\..\File.TMP"

13) Failed : NUnit.Framework.Constraints.SubPathTest_Windows.SucceedsWithGoodValues("C:\\FOLDER1\\.\\junk\\..\\Folder2\\temp\\..\\Folder3")
  Expected: Subpath of "C:\folder1\folder2"
  But was:  "C:\FOLDER1\.\junk\..\Folder2\temp\..\Folder3"

14) Failed : NUnit.Framework.Constraints.SubstringConstraintTestsIgnoringCase.SucceedsWithGoodValues("Hello")
  Expected: String containing "hello", ignoring case
  But was:  "Hello"

15) Failed : NUnit.Framework.Constraints.SubstringConstraintTestsIgnoringCase.SucceedsWithGoodValues("HellO there")
  Expected: String containing "hello", ignoring case
  But was:  "HellO there"

16) Failed : NUnit.Framework.Constraints.SubstringConstraintTestsIgnoringCase.SucceedsWithGoodValues("I said HELLO")
  Expected: String containing "hello", ignoring case
  But was:  "I said HELLO"
```
and
```
Errors, Failures and Warnings

1) Failed : NUnitLite.Tests.CommandLineTests.InvalidResultSpecRecordsError
  Expected: exactly one item String containing "invalid output spec", ignoring case
  But was:  0 items < "Do not provide a file name when running a self-executing test.
    Invalid entry: test.dll", "Invalid output spec: userspecifed.xml;format=nunit2;format=nunit3." >
```

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #3414 (Pending Azure CI run on PR!).

An OS upgrade on Azure changed the default culture our tests ran in from en-US to en-US-POSIX. Our tests shouldn't be sensitive to this sort of change. 🙂

### CODE REVIEW

File: src/NUnitFramework/tests/Constraints/CollectionEquivalentConstraintTests.cs [hunk 1]
```diff
@@ -157,7 +157,7 @@ public void EquivalentHonorsUsing()
             ICollection set2 = new SimpleObjectCollection("z", "Y", "X");
 
             Assert.That(new CollectionEquivalentConstraint(set1)
-                .Using<string>((x, y) => StringUtil.Compare(x, y, true))
+                .Using<string>((x, y) => StringComparer.InvariantCultureIgnoreCase.Compare(x, y))
```
Comment (ChrisMaddock) [inline src/NUnitFramework/tests/Constraints/CollectionEquivalentConstraintTests.cs]: This is just testing the Using, and doesn't need to be doing anything culture-sensitive anyway.

File: src/NUnitFramework/tests/Constraints/PathConstraintTests.cs [hunk 2]
```diff
@@ -28,7 +28,7 @@ namespace NUnit.Framework.Constraints
     /// <summary>
     /// Summary description for PathConstraintTests.
     /// </summary>]
-    [TestFixture]
+    [TestFixture, Platform("Win")]
```
Comment (ChrisMaddock) [inline src/NUnitFramework/tests/Constraints/PathConstraintTests.cs]: The tests in this class looked like they should be windows/linux specific anyway. Given the OS's have different rules around path case-sensitivity, making these tests OS specific seemed like the more sensible option.
