### PR TITLE
Fix date on Ignored and Explicit Tests

### LINKED ISSUE #2339: Wrong date format in Ignored TestFixtures
@alexamz commented on [Mon Jul 31 2017](https://github.com/nunit/nunit-console/issues/274)

Hi all,

First of all, many thanks to all the contributors to this great and useful project!

We have problems with the start-time and end-time dates in Ignored TestFixtures.
We are using the last version of the NUnit console, the 3.7.0.

This is an example of a test-case header in the xml generated by NUnit Console with a wrong formatted date:

>     <test-case id="0-1071" name="AfterStart_AClientMayConnect" fullname="Port.TCP.UnitTests.TcpServerFactoryTests.AfterStart_AClientMayConnect" methodname="AfterStart_AClientMayConnect" classname="Port.TCP.UnitTests.TcpServerFactoryTests" runstate="Runnable" seed="604943940" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">

On this example we can see that start-time and end-time dates have a wrong date  value "0001-01-01 00:00:00Z ". I would expect to have the date of the execution even if they are skipped. Moreover, if you try to publish these dates to TFS API it will fail because of the date value.

This issue is very easy to reproduce , just adding a [Ignore("some ignore reasons")] on a [TextFixture]. And running Nunit Console to generate the xml result output.

Many thanks!

Have a nice day

---

@ChrisMaddock commented on [Mon Jul 31 2017](https://github.com/nunit/nunit-console/issues/274#issuecomment-319094815)

The code for this lives in the NUnit Framework. I'll move this issue over, and comment further over there. 🙂

### LINKED ISSUE #3724: Test start and end time should end with Z
The test start and end time are UTC and should be formatted as such so that they are parsed as UTC by the engine and runners. This causes problems in the Adapter with Explicit tests that are set to `DateTime.MinTime`. They are getting parsed as local which makes the date negative throwing an exception. 

See nunit/nunit3-vs-adapter#811

```
<NUnitTestEvent>
<test-case id='0-1001' name='ExplicitTest' fullname='NUnit3VSIssue811.Explicit.ExplicitTest' methodname='ExplicitTest' classname='NUnit3VSIssue811.Explicit' runstate='Runnable' seed='1980958818' result='Skipped' label='Explicit' site='Parent' start-time='0001-01-01T00:00:00.0000000' end-time='0001-01-01T00:00:00.0000000' duration='0.000000' asserts='0' parentId='0-1000'>
   <reason>
      <message><![CDATA[OneTimeSetUp: https://github.com/nunit/nunit3-vs-adapter/issues/811]]></message>
   </reason>
</test-case>
</NUnitTestEvent>
```

### PR DESCRIPTION
**Pull request by rprouse**
Continues the work started by @Poimen in ##3706 superseding that PR.

Fixes #2339
Fixes #3724

This fixes the Unit Tests for the fix completed by @Poimen, adds additional tests and fixes a bug in the NUnit2 result writer that these changes exposed.

The unit tests cover the changes but I've also tested by examining the test results and manually verifying the start/end/duration of ignored and explicit tests.

### CODE REVIEW

File: src/NUnitFramework/mock-assembly/MockAssembly.cs [hunk 1]
```diff
@@ -113,12 +113,12 @@ public static void Main(string[] args)
         [Category("FixtureCategory")]
         public class MockTestFixture
         {
-            public const int Tests = 10;
-            public const int Suites = 1;
+            public const int Tests = 13;
+            public const int Suites = 2;
```
Comment (rprouse) [inline src/NUnitFramework/mock-assembly/MockAssembly.cs:117]: Adds three tests with the test cases below and one additional suite because the test cases form a suite.

File: src/NUnitFramework/nunitlite.tests/NUnit2XmlOutputWriterTests.cs [hunk 2]
```diff
@@ -113,7 +113,7 @@ public void TestResults_AssemblyPathIsCorrect()
         [TestCase("errors", MockTestFixture.Failed_Error)]
         [TestCase("failures", MockTestFixture.Failed_Other)]
         [TestCase("inconclusive", MockTestFixture.Inconclusive)]
-        [TestCase("not-run", MockTestFixture.Skipped+MockTestFixture.Failed_NotRunnable-MockTestFixture.Skipped_Explicit)]
+        [TestCase("not-run", MockTestFixture.Skipped+MockTestFixture.Failed_NotRunnable)]
```
Comment (rprouse) [inline src/NUnitFramework/nunitlite.tests/NUnit2XmlOutputWriterTests.cs:116]: This didn't match the code but happened to pass.

File: src/NUnitFramework/nunitlite/OutputWriters/NUnit2XmlOutputWriter.cs [hunk 3]
```diff
@@ -89,7 +89,7 @@ private void InitializeXmlFile(ITestResult result)
             xmlWriter.WriteAttributeString("total", summary.TestCount.ToString());
             xmlWriter.WriteAttributeString("errors", summary.ErrorCount.ToString());
             xmlWriter.WriteAttributeString("failures", summary.FailureCount.ToString());
-            var notRunTotal = summary.SkipCount + summary.FailureCount + summary.InvalidCount;
+            var notRunTotal = summary.IgnoreCount + summary.ExplicitCount + summary.SkipCount + summary.InvalidCount;
```
Comment (rprouse) [inline src/NUnitFramework/nunitlite/OutputWriters/NUnit2XmlOutputWriter.cs:92]: The old code didn't make sense to me. Why are failed tests not run? This seems more correct to me.

**Review by rprouse — COMMENTED** [review]
Adding a few notes to help with reviewing. The first three files were changed by @Poimen, most of the remainder are my changes.

File: src/NUnitFramework/nunitlite/OutputWriters/NUnit2XmlOutputWriter.cs (hunk 3 above)
Comment (OsirisTerje) [reply src/NUnitFramework/nunitlite/OutputWriters/NUnit2XmlOutputWriter.cs:92]: The ResultSummary class has a method called ```NotRunCount``` which looks like:  
```
 public int NotRunCount
        {
            get { return InvalidCount + SkipCount + IgnoreCount + ExplicitCount;  }
        }
```
Seems like the same as is expressed here. Perhaps better to use that?

Comment (rprouse) [reply src/NUnitFramework/nunitlite/OutputWriters/NUnit2XmlOutputWriter.cs]: Good idea @OsirisTerje, I made the change.

File: src/NUnitFramework/framework/Internal/TestExecutionContext.cs [hunk 4]
```diff
@@ -213,6 +214,18 @@ private set
         /// </summary>
         public long StartTicks { get; set; }
 
+        /// <summary>
+        /// The current duration of the test taken
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Internal/TestExecutionContext.cs:218]: This sounds odd. Should this be `The current duration of the test` ?

File: src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs [hunk 5]
```diff
@@ -208,6 +208,55 @@ public void TestSuite_HasValidEndTimeAttribute()
...
+            string endTimeStr = RequiredAttribute(testCase, "end-time");
+
+            Assert.That(startTimeStr, Does.EndWith("Z"), "Explicit start-time is not UTC");
+            Assert.That(endTimeStr, Does.EndWith("Z"), "Explicit end-time is not UTC");
+
+            Assert.IsTrue(DateTime.TryParse(startTimeStr, out var startTime));
+            Assert.IsTrue(DateTime.TryParse(endTimeStr, out var endTime));
+
+            Assert.That(startTime, Is.InRange(testRunStartTime, testRunEndTime), "Explicit test cases should be set to approximately the start time of test suite");
+            Assert.That(endTime, Is.InRange(testRunStartTime, testRunEndTime), "Explicit test cases should be set to approximately the start time of test suite");
```
Comment (mikkelbu) [inline src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs:257]: Should this be the end time?
```suggestion
            Assert.That(endTime, Is.InRange(testRunStartTime, testRunEndTime), "Explicit test cases should be set to approximately the end time of test suite");
```
or perhaps `The end time of explicit test cases should be set to approximately the end time of test suite` (and similar change for start time.

File: src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs [hunk 6]
```diff
@@ -208,6 +208,55 @@ public void TestSuite_HasValidEndTimeAttribute()
...
+                Assert.IsTrue(DateTime.TryParse(startTimeStr, out var startTime));
+                Assert.IsTrue(DateTime.TryParse(endTimeStr, out var endTime));
+
+                Assert.That(startTime, Is.InRange(testRunStartTime, testRunEndTime), "Ignored test cases should be set to approximately the start time of test suite");
+                Assert.That(endTime, Is.InRange(testRunStartTime, testRunEndTime), "Ignored test cases should be set to approximately the start time of test suite");
+            }
+        }
+
+        [Test]
+        public void ExplicitTest_HasValidEndTimeAttribute()
```
Comment (mikkelbu) [inline src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs:237]:
```suggestion
        public void ExplicitTest_HasValidStartAndEndTimeAttributes()
```

File: src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs [hunk 7]
```diff
@@ -208,6 +208,55 @@ public void TestSuite_HasValidEndTimeAttribute()
             Assert.That(success, "{0} is an invalid value for end time", endTimeString);
         }
 
+        [Test]
+        public void IgnoredTestCases_HaveValidEndTimeAttribute()
```
Comment (mikkelbu) [inline src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs:212]:
```suggestion
        public void IgnoredTestCases_HaveValidStartAndEndTimeAttributes()
```

File: src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs [hunk 8]
```diff
@@ -208,6 +208,55 @@ public void TestSuite_HasValidEndTimeAttribute()
...
+        {
+            DateTime.TryParse(RequiredAttribute(topNode, "start-time"), out var testRunStartTime);
+            DateTime.TryParse(RequiredAttribute(topNode, "end-time"), out var testRunEndTime);
+
+            var testCaseNodes = suiteNode.SelectNodes("test-suite[@name='SkippedTest']/test-case");
+            Assert.That(testCaseNodes, Is.Not.Null);
```
Comment (mikkelbu) [inline src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs:218]: Should we also assert that Count is larger than 0 (otherwise this test could pass without actually checking the attributes).

File: src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs [hunk 9]
```diff
@@ -208,6 +208,55 @@ public void TestSuite_HasValidEndTimeAttribute()
...
+                string endTimeStr = RequiredAttribute(testCase, "end-time");
+
+                Assert.That(startTimeStr, Does.EndWith("Z"), "Ignored start-time is not UTC");
+                Assert.That(endTimeStr, Does.EndWith("Z"), "Ignored end-time is not UTC");
+
+                Assert.IsTrue(DateTime.TryParse(startTimeStr, out var startTime));
+                Assert.IsTrue(DateTime.TryParse(endTimeStr, out var endTime));
+
+                Assert.That(startTime, Is.InRange(testRunStartTime, testRunEndTime), "Ignored test cases should be set to approximately the start time of test suite");
+                Assert.That(endTime, Is.InRange(testRunStartTime, testRunEndTime), "Ignored test cases should be set to approximately the start time of test suite");
```
Comment (mikkelbu) [inline src/NUnitFramework/nunitlite.tests/NUnit3XmlOutputWriterTests.cs:232]: See comment below about wording the message differently

File: src/NUnitFramework/nunitlite.tests/TextUIReportTests.cs [hunk 10]
```diff
@@ -101,7 +101,13 @@ public void TestsNotRunTest()
                 "Tests Not Run\n\n" +
                 "1) Ignored : NUnit.Tests.Assemblies.MockTestFixture.IgnoreTest\n" +
                 "Ignore Message\n\n" +
-                "2) Explicit : NUnit.Tests.Assemblies.MockTestFixture.ExplicitTest\n\n"));
+                "2) Ignored : NUnit.Tests.Assemblies.MockTestFixture.SkippedTest(1)\n"+
+                "Ignore testcase\n\n"+
+                "3) Ignored : NUnit.Tests.Assemblies.MockTestFixture.SkippedTest(2)\n"+
+                "Ignore testcase\n\n"+
+                "4) Ignored : NUnit.Tests.Assemblies.MockTestFixture.SkippedTest(3)\n"+
+                "Ignore testcase\n\n"+
```
Comment (mikkelbu) [inline src/NUnitFramework/nunitlite.tests/TextUIReportTests.cs:109]: Are we here (implicitly) testing the ordering of attributes on a method? We often remind users that the attributes are unordered, so one cannot depend on the ordering. Should we use a TestCaseSource to make the ordering deterministic? (although this will be a bit more verbose)

**Review by mikkelbu — DISMISSED** [review]
Looks good. I have a handful of comments/suggestions/questions, but nothing major.

**Comment by rprouse** [comment]
All excellent suggestions @mikkelbu, thanks for a very thorough review. I've incorporated all of your suggestions.
