### PR TITLE
Issue 556

### LINKED ISSUE #556: Executed tests should always return a non-zero duration
Runners like the vs adapter get confused when a test runs in zero time. In the case of VS, the test is listed as not run, even if it succeeded or failed. We deal with this in the adapter by replacing the duration with the equivalent of a single tick.

It would be  desirable if NUnit returned a non-zero duration in all such cases. This could be the equivalent of a tick, or the lowest representable value in seconds, or some special value that the runner can interpret.

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #556 

This PR ensures that the minimum duration for test runs is 1 nanosecond and changes the TestResult.Duration from a TimeSpan to a double. It also fixes the bug where the XML report was being rounded to the nearest millisecond.

I included in this PR the `InternalsVisibleTo` changes from #600 because I wanted to test internal members of TestResult.

I've added unit tests and I also confirmed by checking the XML results. They are now accurate to 6 digits (nanoseconds).

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/Commands/MaxTimeCommand.cs [hunk 1]
```diff
@@ -62,12 +62,11 @@ public override TestResult Execute(TestExecutionContext context)
             TestResult testResult = innerCommand.Execute(context);
 
             long tickCount = Stopwatch.GetTimestamp() - startTicks;
-            double seconds = (double)tickCount / Stopwatch.Frequency;
-            testResult.Duration = TimeSpan.FromSeconds(seconds);
+            testResult.Duration = (double)tickCount / Stopwatch.Frequency;
```
Comment (CharliePoole) [inline src/NUnitFramework/framework/Internal/Commands/MaxTimeCommand.cs]: This should now be in seconds. Maybe a comment would help either here or below, where you convert to ms. When we used FromSeconds and TotalMilliseconds it was self-explanatory but I had to read this a few times to catch on.

File: src/NUnitFramework/tests/Attributes/OneTimeSetUpTearDownTests.cs [hunk 2]
```diff
@@ -229,7 +229,7 @@ public void HandleErrorInFixtureTearDownAfterErrorInTest()
             Assert.AreEqual(1, fixture.setUpCount, "setUpCount");
             Assert.AreEqual(1, fixture.tearDownCount, "tearDownCount");
 
-            Assert.AreEqual("One or more child tests had errors" + Env.NewLine + "TearDown : System.Exception : This was thrown from fixture teardown", result.Message);
+            Assert.AreEqual(TestResult.CHILD_ERRORS_MESSAGE + Env.NewLine + "TearDown : System.Exception : This was thrown from fixture teardown", result.Message);
```
Comment (CharliePoole) [inline src/NUnitFramework/tests/Attributes/OneTimeSetUpTearDownTests.cs]: This is out of scope for your change but it might be good to assert on the value of Result.FailureSite wherever we are asserting on CHILD_ERRORS_MESSAGE. We can get that at a later time though.

**Comment by CharliePoole** [comment]
Merge when you are ready. BTW, 6 digits after the decimal point is microseconds, nine would be nanoseconds. Unless you guys have a different meaning, that is. :-)

It's only relevant for the docs though.

File: src/NUnitFramework/tests/Attributes/OneTimeSetUpTearDownTests.cs (hunk 2 above)
Comment (rprouse) [inline src/NUnitFramework/tests/Attributes/OneTimeSetUpTearDownTests.cs]: Good idea, may as well get it done while I am in this code. Done.
