### PR TITLE
NullReferenceException with null arguments in TestFixtureAttribute

### LINKED ISSUE #1507: NullReferenceException when null arguments are used in TestFixtureAttribute
My team is in the process of trying to convert our unit tests from 2.6.4 to 3, and we ran into several errors while running the console runner (just using `nunit3-console.exe tests.dll`), similar to the following:

```
13) Invalid : Tests.Controls.Query.when_execute_is_clicked
An exception was thrown while loading the test.

System.NullReferenceException: Object reference not set to an instance of an object.
 at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.CheckTestFixtureIsValid(TestFixture fixture)
 at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
 at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext()
 at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)
```

This corresponds to the following test fixture and its constructor:
```
[TestFixture(null, "foo", "foo")]
[TestFixture("", "foo", "foo")]
[TestFixture("bar", "foo", "bar")]
public class when_execute_is_clicked : RefreshTestBase
{
    private string _selectedText;
    private string _query;
    private string _issuedQuery;

    public when_execute_is_clicked(string selectedText, string query, string issuedQuery)
    {
        _selectedText = selectedText;
        _query = query;
        _issuedQuery = issuedQuery;
    }
```

Judging by the code I see in master, it would appear the NRE is coming from [NUnitTestFixtureBuilder, line 229](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs#L229).

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #1507

Turned out to not be the easy fix I expected, but not too bad. I will explain the changes inline with the code.

### CODE REVIEW

File: src/Common/nunit/Compatibility/ReflectionExtensions.cs [hunk 1]
```diff
@@ -521,4 +474,72 @@ public static IList<Type> GetTypes(this Assembly asm)
...
+    /// </summary>
+    public static class AdditionalTypeExtensions
+    {
+        /// <summary>
+        /// Determines if the given <see cref="Type"/> array is castable/matches the <see cref="ParameterInfo"/> array.
+        /// </summary>
+        /// <param name="pinfos"></param>
+        /// <param name="ptypes"></param>
+        /// <returns></returns>
+        public static bool ParametersMatch(this ParameterInfo[] pinfos, Type[] ptypes)
```
Comment (rprouse) [inline src/Common/nunit/Compatibility/ReflectionExtensions.cs]: Most of this is just moved from within the PORTABLE block.

File: src/Common/nunit/Compatibility/ReflectionExtensions.cs [hunk 2]
```diff
@@ -521,4 +474,72 @@ public static IList<Type> GetTypes(this Assembly asm)
...
+        /// <param name="from"></param>
+        /// <returns></returns>
+        public static bool IsCastableFrom(this Type to, Type from)
+        {
+            if (to.IsAssignableFrom(from))
+                return true;
+            
+            // Look for the marker that indicates from was null
+            if (from == typeof(NUnitNullType) && to.GetTypeInfo().IsClass)
+                return true;
```
Comment (rprouse) [inline src/Common/nunit/Compatibility/ReflectionExtensions.cs]: This if block is the only change, checking if we found null in the parameter list by looking for the marker class since there is no typeof(null)

File: src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs [hunk 3]
```diff
@@ -215,18 +215,7 @@ private static void CheckTestFixtureIsValid(TestFixture fixture)
...
-
-                // Note: This could be done more simply using
-                // Type.EmptyTypes and Type.GetTypeArray() but
-                // they don't exist in all runtimes we support.
-                argTypes = new Type[args.Length];
-
-                int index = 0;
-                foreach (object arg in args)
-                    argTypes[index++] = arg.GetType();
+                Type[] argTypes = Reflect.GetTypeArray(fixture.Arguments);
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs]: Removed duplicate code

File: src/NUnitFramework/framework/Internal/Reflect.cs [hunk 4]
```diff
@@ -181,12 +183,15 @@ public static object Construct(Type type, object[] arguments)
...
-        private static Type[] GetTypeArray(object[] objects)
+        internal static Type[] GetTypeArray(object[] objects)
         {
             Type[] types = new Type[objects.Length];
             int index = 0;
             foreach (object o in objects)
-                types[index++] = o.GetType();
+            {
+                // NUnitNullType is a marker to indicate null since we can't do typeof(null) or null.GetType()
+                types[index++] = o == null ? typeof(NUnitNullType) : o.GetType();
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Reflect.cs]: Hack? Probably, but open to suggestions :smile:

Comment (CharliePoole) [inline src/NUnitFramework/framework/Internal/Reflect.cs]: What happens if we get a typed null like `(string)null`? Do we recognize that separately? Do we need to?

Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Reflect.cs]: Even if it is a typed null, in this case it still come in as a null parameter. Just to be sure, I added a typed null test and it works fine.

**Comment by danlyons-softek** [comment]
It may be worth adding some tests for `Nullable<T>` arguments, since `Nullable<T>` is itself a struct.

**Comment by rprouse** [comment]
I added tests where the constructor parameters are Nullable and it worked fine. Changes pushed to this PR.

**Comment by CharliePoole** [comment]
This doesn't affect the merging but did you figure out why we have this problem with fixtures but not methods?

**Comment by rprouse** [comment]
I did look at the difference between TestCase and TestFixture. TestCase works because there is only one method, so we just make sure the parameters can be converted to the target parameters. With TestFixture, we were using GetConstructor with types. It was different logic although it is nearly the same now since we get all constructors and check the types of each.

**Comment by rprouse** [comment]
Build failures are for the Nullable types. Not sure why it worked on my machine, I might have made a mistake. Looking at it.

**Comment by CharliePoole** [comment]
@rprouse That makes sense now that you explain it!

**Comment by rprouse** [comment]
Not sure what I did wrong before, but Nullable<T> was not working. I have pushed a fix.

**Comment by rprouse** [comment]
@CharliePoole, anything else that you would like to see in this PR, or can we merge?
