### PR TITLE
Initial tests of parallel execution, shift changing, etc.

### LINKED ISSUE #1239: NUnit3 sometimes hangs if SetUpFixtures are run in parallel
If I have multiple `SetUpFixture`s in the same namespace, and I enable parallelization at the Assembly level, NUnit 3.0.1 _sometimes_ hangs after running the `[OneTimeSetUp]` methods, before running the tests.

It happens with both the console runner and the Visual Studio test adapter.  In my case it remains hung for 24 hours (at which point our automated build tool kills the process.)

While debugging this issue, I added some trace statements and confirmed that both `[OneTimeSetUp]` methods ran and completed, but no `[Test]` methods were called.

The simplified code below reproduces it pretty reliably (but not every time!)  If you comment out the `Thread.Sleep()`, the problem goes away.  The problem also goes away if you turn off parallelization, or if parallelization is enabled with only a single `[SetUpFixture]`.

``` C#
using System;
using System.Threading;
using NUnit.Framework;

[assembly: Timeout(60000)]
[assembly: Parallelizable(ParallelScope.Children)]

namespace ParallelSetUpFixtures
{
    [SetUpFixture]
    public class FooSetUp
    {
        [OneTimeSetUp]
        public void FooSetUpMethod()
        {
            Console.WriteLine("FooSetUp");
        }
    }

    // [Parallelizable(ParallelScope.None)]  // if this line is uncommented, then NUnit will not hang
    [SetUpFixture]
    public class BarSetUp
    {
        [OneTimeSetUp]
        public void BarSetUpMethod()
        {
            Thread.Sleep(500); // if this line is commented out, then NUnit will not hang
            Console.WriteLine("BarSetUp");
        }
    }

    [TestFixture]
    public class MyTests
    {
        [Test]
        public void MyTest()
        {
            Console.WriteLine("MyTest");
        }
    }
}
```

Here is the command line I'm using:

```
nunit3-console.exe parallel_set_up_fixtures-w64r-16-3.dll --framework=4.5
```

While it is hung, I see three threads with NUnit code in the call stacks.  The other threads are just worker threads waiting for work.  Here are partial stack traces for the three NUnit threads:

```
    mscorlib.dll!System.Threading.WaitHandle.InternalWaitOne    Unknown
    mscorlib.dll!System.Threading.WaitHandle.WaitOne    Unknown
>   nunit.engine.dll!NUnit.Engine.Agents.RemoteTestAgent.WaitForStop Line 109   C#
    nunit-agent.exe!NUnit.Agent.NUnitTestAgent.Main Line 133    C#

    mscorlib.dll!System.Threading.WaitHandle.InternalWaitOne    Unknown
    mscorlib.dll!System.Threading.WaitHandle.WaitOne    Unknown
>   nunit.framework.dll!NUnit.Framework.Api.NUnitTestAssemblyRunner.WaitForCompletion Line 236  C#
    nunit.framework.dll!NUnit.Framework.Api.NUnitTestAssemblyRunner.Run Line 200    C#
    nunit.framework.dll!NUnit.Framework.Api.FrameworkController.RunTests Line 208   C#
    nunit.framework.dll!NUnit.Framework.Api.FrameworkController.RunTestsAction.RunTestsAction Line 404  C#

    // the size of queue is 0
>   nunit.framework.dll!NUnit.Framework.Internal.Execution.EventQueue.Dequeue Line 274  C#
    nunit.framework.dll!NUnit.Framework.Internal.Execution.EventPump.PumpThreadProc Line 208    C#
    mscorlib.dll!System.Threading.ExecutionContext.RunInternal  Unknown

```

### LINKED ISSUE #2364: Parallelizable attribute not invalidating invalid parallel scope combinations
I was looking through the ParallelizableAttribute.cs, and the changes made with https://github.com/nunit/nunit/pull/2264. I noticed that there is the functionality to invalidate tests with invalid parallel combinations in the ApplyToTest() method, but it does not appear to be actually invalidating them. Is this intentional? 

Using 3.7.1, 
I tested and was able to reproduce the hanging found in https://github.com/nunit/nunit/issues/2261 by placing [NonParallelizable] on the test fixture, and [Parallelizable(ParallelScope.Self)] on the test method. 

I placed [Parallelizable(ParallelScope.Fixture)] on a test method with no parallelization on the fixture, and the tests ran and passed normally without any parallelization.

Instead of invalidating the setting, it could potentially be useful. What are your thoughts on allowing ParallelScope.Fixtures for methods? It would be useful in the case where you would only like to run one particular test one at a time at the fixture level, but run the rest of the tests in the fixture at ParallelScope.Self. It allows for the specific test in the fixture to be isolated without affecting other fixtures in the way ParallelScope.None does.

### LINKED ISSUE #2395: NUnit 3.8+ does not finish running tests
There seems to be some kind of deadlock going on since NUnit 3.8.0 (I have tried 3.8.1 as well). My tests run fine but when all tests are done NUnit never completes the test run and one CPU remains maxed out until the process is killed.

I am experiencing the same problem with both the console runner and the runner in CodeRush for Roslyn.

I attached a debugger to nunit-agent.exe and this is how my threads look like while this is happening, thread 6488 in my screenshot is the one using all the CPU.

image

### LINKED ISSUE #2467: Test execution hangs when using [SetUpFixture] with NUnit 3.8.x
It hangs with console runner (3.7) and also with  R# (2017.2).

Here are the log files when using `--labels:before`:
[nunit_3_8_1.txt](https://github.com/nunit/nunit/files/1348973/nunit_3_8_1.txt)
[nunit_3_7.txt](https://github.com/nunit/nunit/files/1348974/nunit_3_7.txt)

When running in R# we see that tests from other namespace never start:
image

It seems related to `public class AssemblySetup` which has the attribute `[SetUpFixture]`.

### LINKED ISSUE #2471: Parametrized testcases not running in parallel
## Issue

I am trying to run several cases of a parametrized test in parallel. Here is the code I'm using:

```c#
class Dummy
{
    static TestCaseData Case(int i)
        => new TestCaseData(TimeSpan.FromSeconds(2)).SetName($"Case {i}");

    public static IEnumerable<TestCaseData> Cases()
        => Enumerable.Range(1, 5).Select(Case);

    [TestCaseSource(nameof(Cases)), Parallelizable]
    public void ItShouldSleep(TimeSpan t)
        => Thread.Sleep(t);
}
```

When I run this using the Visual Studio test runner, I can see the individual cases being executed one at a time, and the overall test run takes ~10 seconds. I would expect all the cases to be executed simultaneously on separate threads, and for the overall run to take ~2 seconds.

## Setup

I am using the following .NET Standard based csproj file alongside the code above:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="NUnit" Version="3.8.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>

</Project>
```

**NuGet packages:**
 - Microsoft.NET.Test.Sdk: v15.3.0
 - Microsoft.NETCore.App: v2.0.0
 - NUnit: v3.8.1
 - NUnit3TestAdapter: v3.8.0

**Visual Studio:**
 - NUnit 3 Test Adapter: 3.8.0.0
 - Visual Studio: 15.3.5

### LINKED ISSUE #2478: Attributes on SetUpFixture are not applied
Investigating parallel execution, I discovered that `ParallelizableAttribute` on a `SetUpFixture` has no effect on the test at all. In fact, aside from `SetUpFixtureAttribute` itself, attributes on a SetUpFixture have no effect at all!

Among other things, this probably explains some of our parallelization issues.

### PR DESCRIPTION
**Pull request by CharliePoole**
This PR is intended to collect fixes for a number of parallelism issues, particularly around use of SetUpFixtures but also with the handling of parallel and non-parallel TestFixtures and the smooth changing of shifts within the dispatcher.

The initial commit sets up some infrastructure and adds a few unit tests of the parallel dispatcher. Those tests are known to fail intermittently, just as user runs are failing intermittently in some cases.

The issues I hope to address in this PR include #1239, ~~#1905~~, #2364, #2388, #2467 and #2471. I'll add "Fixes" notations when I think any of them is fixed.

I'd like it if @nunit/framework-team members followed along and commented.

Fixes #1239 (needs review)
Fixes #2364
Fixes #2395
Fixes #2467
Fixes #2471
Fixes #2478

### CODE REVIEW

**Comment by CharliePoole** [comment]
The second commit removes saving and restoring of queues entirely from the dispatcher. This feature was added so that non-parallel fixtures containing parallel test cases could run in absolute isolation from other fixtures. The non-parallel fixture gets a complete set of queues all to itself.

I'm removing it so that it can be re-implemented in a cleaner way. It's possible to do this temporarily because our own tests don't present the situation for which the feature was designed - i.e. having a non-parallel fixture with parallel child tests.

**Comment by CharliePoole** [comment]
Fixes #2478 - a new issue found while debugging parallel SetUpFixtures

**Comment by jnm2** [comment]
Spotted a typo in the first commit message.

File: src/NUnitFramework/TestBuilder.cs [hunk 1]
```diff
@@ -60,51 +64,19 @@ public static TestSuite MakeFixture(object fixture)
...
-        }
-
         public static TestSuite MakeParameterizedMethodSuite(Type type, string methodName)
         {
             var suite = MakeTestFromMethod(type, methodName) as TestSuite;
             Assert.NotNull(suite, "Unable to create parameterized suite - most likely there is no data provided");
             return suite;
         }
 
-        public static TestSuite MakeParameterizedMethodSuite(object fixture, string methodName)
```
Comment (jnm2) [inline src/NUnitFramework/TestBuilder.cs]: The hard part with reviewing commits this big is that it seems like this refactor will be a very cross-cutting change, but I'm all for streamlining this API. 😃

File: src/NUnitFramework/TestBuilder.cs [hunk 2]
```diff
@@ -161,34 +133,45 @@ public static ITestResult RunTestCase(object fixture, string methodName)
...
         {
-            return ExecuteWorkItem(PrepareWorkItem(test, testObject));
+            return ExecuteWorkItem(CreateWorkItem(test, testObject));
         }
 
-        // NOTE: The following two methods are separate in order to support
-        // tests that need to access the WorkItem before or after execution.
+        public static CompositeWorkItem CreateWorkItem(Type type)
+        {
+            return CreateWorkItem(MakeFixture(type)) as CompositeWorkItem;
```
Comment (jnm2) [inline src/NUnitFramework/TestBuilder.cs]: Are we expecting consuming code to be tolerant of null returns? I prefer direct casts when possible because diagnosis at the call site is easier.

File: src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs [hunk 3]
```diff
@@ -66,17 +86,17 @@ public ParallelWorkItemDispatcher(int levelOfParallelism)
...
-                string name = string.Format("Worker#" + i.ToString());
+                string name = string.Format("ParallelWorker#" + i.ToString());
                 ParallelShift.Assign(new TestWorker(ParallelQueue, name));
             }
 
-            ParallelShift.Assign(new TestWorker(ParallelSTAQueue, "Worker#STA"));
+            ParallelShift.Assign(new TestWorker(ParallelSTAQueue, "ParallelSTAWorker"));
 
-            var worker = new TestWorker(NonParallelQueue, "Worker#STA_NP");
+            var worker = new TestWorker(NonParallelQueue, "NonParallelWorker");
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs]: This always confused me! I like the changes.

File: src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs [hunk 4]
```diff
@@ -244,41 +267,45 @@ private void RestoreQueues()
...
         private void OnEndOfShift(object sender, EventArgs ea)
         {
-            // This shift ended, so see if there is work in any other
-            // TODO: Temp fix - revisit later when object model is redesigned.
-            if (StartNextShift())
-                return;
-
-            if (_isolationLevel > 0)
-                RestoreQueues();
+            ShiftFinished?.Invoke(sender as WorkShift);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs]: Same thing. Can we direct-cast sender to `WorkShift` or at least throw an `ArgumentException`? Would seem to indicate abuse and safe casts create a secondary breach of expectations (raising ShiftFinished with a null WorkShift) while hiding the root cause.

File: src/NUnitFramework/framework/Internal/Execution/TestWorker.cs [hunk 5]
```diff
@@ -122,10 +122,19 @@ private void TestWorkerThreadProc()
...
                     _currentWorkItem.TestWorker = this;
 
+                    // During this Busy call, the queue state may be saved.
+                    // This gives us a new set of queues, which are initially 
+                    // empty. The intention is that only children of the current
+                    // executing item should make use of the new set of queues.
                     Busy(this, _currentWorkItem);
 
+                    // Because we execute the current item AFTER the queue state
+                    // is saved, it's children end up in the new queue set.
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/TestWorker.cs]: `it's` should be `its`

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs [hunk 6]
```diff
@@ -161,11 +161,11 @@ private void StartWorkers()
                 worker.Idle += (s, ea) =>
                 {
                     // Quick check first using Interlocked.Decrement
-                    if (Interlocked.Decrement(ref _busyCount) == 0)
+                    if (Interlocked.Decrement(ref _busyCount) == 0 && !HasWork)
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: Two concerns with `HasWork` outside a `lock`: 
 - In the worst case scenario, the current thread's view of `HasWork` is stale and never updates to become `false`, so the lock is never taken. We need a memory barrier like `Volatile.Read` or `Interlocked` which brings me to the next point:
 - Reading the `IList` can result in corrupted results (dirty read, tearing- I've observed this in practice) if the `IList` is being changed by another thread. Either we need an absolute guarantee that the `IList` is thread safe (which solves the first point as well), or we need to lock read as well as write access to it (which again solves the first point).

Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: Two concerns with `HasWork` outside a `lock`: 
 - In the worst case scenario, the current thread's view of the list memory behind `HasWork` is stale and never updates to become `false`, so the `if` branch is never executed. We need a memory barrier which brings me to the next point:
 - Reading the `IList` can result in corrupted results (dirty read, tearing- I've observed the weird internal exceptions caused by this in practice) if the `IList` is being changed by another thread. Either we need an absolute guarantee that the `IList` itself is a thread safe collection (which solves the first point as well), or we need to lock read access as well as write access to it (which again solves the first point).

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: And I see it's backed by a `List<>` which means we definitely can't read it without locking access.

File: src/NUnitFramework/tests/Attributes/TestOrderAttributeTests.cs [hunk 7]
```diff
@@ -27,18 +26,15 @@ public void CheckOrderIsCorrect()
...
         [Test]
         [TestCaseSource(nameof(Cases))]
-        public void CheckClassOrderIsCorrect(List<Type> candidateTypes)
+        public void CheckClassOrderIsCorrect(Type[] candidateTypes)
         {
-            var testSuite = TestBuilder.MakeFixture(candidateTypes);
+            var testSuite = new TestSuite("dummy").Containing(candidateTypes);
 
-            var work = TestBuilder.PrepareWorkItem(testSuite, null) as CompositeWorkItem;
+            var work = TestBuilder.CreateWorkItem(testSuite) as CompositeWorkItem;
```
Comment (jnm2) [inline src/NUnitFramework/tests/Attributes/TestOrderAttributeTests.cs]: Correct me if I'm wrong but my memory is that the return type of `TestBuilder.CreateWorkItem` is already `CompositeWorkItem` s othe `as` is redundant?

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 8]
```diff
@@ -0,0 +1,194 @@
...
+
+            dispatcher.ShiftFinished += (shift) =>
+            {
+                AddEvent("ShiftFinished " + shift.Name);
+            };
+
+            var workItem = TestBuilder.CreateWorkItem(_testSuite, context);
+
+            var run_complete = new ManualResetEvent(false);
+            workItem.Completed += (s, e) => { run_complete.Set(); };
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: (`(s, e) => run_complete.Set();` is an option too)

Comment (jnm2) [reply src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: Also `run_complete` should really be in a `using` statement because it holds unmanaged handles.

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 9]
```diff
@@ -0,0 +1,194 @@
...
+        public void AllTestsPassed()
+        {
+            if (_result.ResultState != ResultState.Success)
+                Assert.Fail(DumpEvents("Not all tests passed"));
+        }
+
+        [Test]
+        public void AllTestsRan()
+        {
+            if(_result.PassCount != _numCases)
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: Inconsistent spacing after the `if` keyword

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 10]
```diff
@@ -0,0 +1,194 @@
...
+                Assert.Fail(DumpEvents("Incorrect number of test cases"));
+        }
+
+        [Test]
+        public void OnlyOneShiftMayBeActive()
+        {
+            int count = 0;
+            foreach (var @event in _events)
+            {
+                if (@event.StartsWith("ShiftStarted") && ++count > 1)
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: I guess this is really not important for tests, but if this was shipping code, I'd yell about the missing `StringComparison.Ordinal` parameter because thread culture can wreck string comparisons.

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 11]
```diff
@@ -0,0 +1,194 @@
...
+                3);
+
+            yield return new TestFixtureData(
+                TestBuilder.MakeSuite("NUnit")
+                    .Containing(TestBuilder.MakeSuite("TestData")
+                        .Containing(TestBuilder.MakeSuite("ParallelExecutionData")
+                            .Containing(TestBuilder.MakeFixture(typeof(TestSetUpFixture))
+                                .Containing(typeof(TestFixture1), typeof(TestFixture2), typeof(TestFixture3))))),
+                3);
+        }
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: Neat!

**Comment by jnm2** [comment]
Sorry, gotta go but I'll be back.

**Comment by CharliePoole** [comment]
I initially worked on this with the idea of completely changing the structure of parallel execution. Test fixtures that needed to run in isolation would use an entirely new dispatcher, the old dispatcher would quiesce until the new one finished and the new dispatcher would get new work shifts, queues and workers.

This turned out to be very complex, requiring intercommunication among the dispatchers. After spending about 20 hours on it, I'm going back to the original design and trying to make it work. That is, `WorkItemQueue` maintains a stack of real queues under the covers. This is used to isolate non-parallel fixtures so that it's impossible for anything else to run at the same time. 

The current / continuing design is a bit ugly in my opinion, but it has been working and I think it's a better use of time to fix the bugs right now.

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs (hunk 10 above)
Comment (CharliePoole) [reply src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: I agree with both points. 😈

File: src/NUnitFramework/tests/Attributes/TestOrderAttributeTests.cs (hunk 7 above)
Comment (CharliePoole) [reply src/NUnitFramework/tests/Attributes/TestOrderAttributeTests.cs]: It returns `WorkItem` in this overload. But I'll look at the overloads again.

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs (hunk 6 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: This could be a source of some intermittent issues I'm seeing. I'll check.

BTW, this is far from done!

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: @jnm2 Thinking about this, I realized that I'm relying on the fact that the underlying list is never changed once set up. A lot of the parallel dispatcher code is like that...

* `ParallelWorkItemDispatcher` has fixed lists of shifts, queues and workers.
* `WorkShift` has a specific set of queues and workers.
* `WorkItemQueue` has a specific set of workers.

For that reason, I've played a little loose with locking. Maybe it would be better to use a collection that can't be updated at all, just in case.

**Comment by CharliePoole** [comment]
Merges are pulling in code that uses the old `TestBuilder` interfaces. I'll rebase again.

File: src/NUnitFramework/TestBuilder.cs (hunk 2 above)
Comment (CharliePoole) [reply src/NUnitFramework/TestBuilder.cs]: Different philosophy on my part for tests than for production code, I guess. In general, the return is used immediately and we get a null reference exception. I think it's probably six of one etc. unless the return is being held on to for a long time and then used later.

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs (hunk 6 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: Ah, and I'm so used to looking for `IReadOnlyList<>` to make an appearance for that guarantee... It would simplify my understanding of the code if there was a builder type. How much code would break if `WorkShift` stopped exposing the `IList<>` and made a defensive array copy of the list passed into the constructor, stored as a private readonly `WorkItemQueue[]` and an XML comment on it that it should be immutable? (Or we could even add a lightweight `ImmutableArray` to our BCL-like toolbox?)

So long as no thread mutates the `IList<>` after the first time another thread reads it, we don't need to lock access to it.

File: src/NUnitFramework/tests/Attributes/TestOrderAttributeTests.cs (hunk 7 above)
Comment (jnm2) [reply src/NUnitFramework/tests/Attributes/TestOrderAttributeTests.cs]: Taking another look, this does make sense. Though again I think the safe cast clouds intent, whichever way you look at it. But nbd.

**Comment by jnm2** [comment]
GitHub thinks a bunch of my comments are no longer relevant but they are. Should I delete and recomment?

**Comment by CharliePoole** [comment]
@jnm2 GitHub does that after a forced push and I just had to do two in a row. Wait till I fix the things you already pointed out - I can see them with a few extra clicks.

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs (hunk 6 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: Queues is only public for test purposes. Could easily be internal. I'll take a look at the other collections of queues, shifts and workers as well. This may be an easy fix.

File: src/NUnitFramework/TestBuilder.cs (hunk 2 above)
Comment (CharliePoole) [reply src/NUnitFramework/TestBuilder.cs]: I added a comment clarifying that the cast is guaranteed - WorkItem created from a TestSuite is always composite.

Comment (jnm2) [reply src/NUnitFramework/TestBuilder.cs]: In my mind, safe cast + "cast is guaranteed" comment can be refactored to direct cast and communicate precisely the same thing. But no big deal.

Comment (CharliePoole) [reply src/NUnitFramework/TestBuilder.cs]: Hmm... I don't think it communicates that. IT gives rise to the comment "How do you know this cast won't throw?" There's no satisfying everyone, I guess. 😄

Comment (CharliePoole) [reply src/NUnitFramework/TestBuilder.cs]: I changed the return type. Problem solved!

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs (hunk 6 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: For now, I'm only changing this to internal. In fact, determining whether a shift is really over is the key to a lot of our issues so I expect to be back in this bit of code in subsequent commits as I add tests for the various issues.

File: src/NUnitFramework/TestBuilder.cs (hunk 2 above)
Comment (jnm2) [reply src/NUnitFramework/TestBuilder.cs]: In either case you'd also have to explain _how_ you know it won't throw. But no big deal; I'm satisfied either way. Just exchanging viewpoints!

File: src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs [hunk 12]
```diff
@@ -244,41 +276,46 @@ private void RestoreQueues()
 
         private void OnEndOfShift(object sender, EventArgs ea)
         {
-            // This shift ended, so see if there is work in any other
-            // TODO: Temp fix - revisit later when object model is redesigned.
-            if (StartNextShift())
-                return;
+            ShiftFinished?.Invoke(sender as WorkShift);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs]: This one is production code. Can we direct-cast sender to `WorkShift` or at least throw an `ArgumentException`? Would seem to indicate abuse and safe casts create a secondary breach of expectations (raising ShiftFinished with a null WorkShift) while hiding the root cause.

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs [hunk 13]
```diff
@@ -248,6 +253,16 @@ public virtual void Execute()
 #endif
         }
 
+        private ManualResetEvent _completionEvent = new ManualResetEvent(false);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: `ManualResetEvent` is `IDisposable` and therefore the owning class should implement `IDisposable` and dispose it to free the kernel handles.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: The field should be `readonly` too.

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs [hunk 14]
```diff
@@ -177,6 +177,11 @@ public virtual ParallelExecutionStrategy ExecutionStrategy
                 return _executionStrategy.Value;
             }
         }
+
+        /// <summary>
+        /// Indicates whether this work item should use a separate dispatcher.
+        /// </summary>
+        public virtual bool IsolateChildTests { get; } = false;
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: We can save an autogenerated field per instance by doing `IsolateChildTests => false;` since we aren't setting `IsolateChildTests` in a constructor.

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 15]
```diff
@@ -0,0 +1,196 @@
...
+        public void AllTestsPassed()
+        {
+            if (_result.ResultState != ResultState.Success)
+                Assert.Fail(DumpEvents("Not all tests passed"));
+        }
+
+        [Test]
+        public void AllTestsRan()
+        {
+            if(_result.PassCount != _numCases)
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: Inconsistent spacing after the `if` keyword

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 16]
```diff
@@ -0,0 +1,196 @@
...
+                _events.Add(@event);
+        }
+
+        private string DumpEvents(string message)
+        {
+            var sb = new StringBuilder(message + NL);
+            foreach (string @event in _events)
+            {
+                sb.Append(@event);
+                sb.Append(NL);
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: `sb.AppendLine()`?

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 17]
```diff
@@ -0,0 +1,196 @@
...
+
+        private void AddEvent(string @event)
+        {
+            lock (_events)
+                _events.Add(@event);
+        }
+
+        private string DumpEvents(string message)
+        {
+            var sb = new StringBuilder(message + NL);
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: `new StringBuilder(message).AppendLine();`?

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs (hunk 16 above)
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: `new StringBuilder(message).AppendLine();`, and `sb.AppendLine(@event)` here? This would allow you to remove the `NL` declaration too.

File: src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs [hunk 18]
```diff
@@ -0,0 +1,196 @@
...
+using NUnit.TestData.ParallelExecutionData;
+using NUnit.TestUtilities;
+
+namespace NUnit.Framework.Internal.Execution
+{
+    [TestFixtureSource(nameof(GetParallelSuites))]
+    public class ParallelExecutionTests : ITestListener
+    {
+        private TestSuite _testSuite;
+        private int _numCases;
```
Comment (jnm2) [inline src/NUnitFramework/tests/Internal/Execution/ParallelExecutionTests.cs]: Both can be `readonly`.

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs (hunk 6 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: I got sidetracked talking about the list, but we still have a staleness issue checking `WorkItemQueue.IsEmpty`. We need locked access to that mutable state.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: [Just checked on it.](https://github.com/nunit/nunit/blob/0162e7c1d8640769be2714ea81a3002903f36617/src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs#L169-L179) No staleness issue because you're looking through an array (which I assume is also mot mutated once multiple threads see it) and each array item is a ConcurrentQueue.

Though on a new topic now, having more than one concurrency primitive in action makes me feel like everything is susceptible to race conditions. What happens if one of the queues gets an item added on a background thread right after `IsEmpty` returns false?

**Comment by jnm2** [comment]
Pulling the code.

**Comment by jnm2** [comment]
I'm trying to put hte whole picture together but I am feeling uneasy about things like this: Between checking `.HasWork` and returning the shift, another thread may cause `HasWork` to become false.

https://github.com/nunit/nunit/blob/0162e7c1d8640769be2714ea81a3002903f36617/src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs#L312-L318

The next thing that happens is that we call `shift.Start()` on a shift that has potentially just ended:

https://github.com/nunit/nunit/blob/0162e7c1d8640769be2714ea81a3002903f36617/src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs#L299-L304

Which starts a new thread and loops forever until it finds work which may never happen because the work ended between `HasWork` checking it and returning it:

https://github.com/nunit/nunit/blob/0162e7c1d8640769be2714ea81a3002903f36617/src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs#L273-L278

Am I missing something or could this cause the thread to busy-wait forever?

**Comment by jnm2** [comment]
All the busy waits I'm seeing could also be contributors to the CPU spikes.

File: src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs (hunk 12 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs]: Changing delegate to be type-safe.

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs (hunk 13 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: Good one!

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs (hunk 14 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: I don't love this syntax, especially when the property is virtual. IMO, the existing syntax is clearer to read and avoids confusion.

**Comment by CharliePoole** [comment]
@jnm2 Regarding HasWork, here's the logic that __should__ apply, unless there is a bug.

* Only one shift ends at a time, so when a shift has ended, no shift is running.
* We only call HasWork when no shift is running
* Since no shift is running, no thread can create more work.

Admittedly, there could be a problem here. However, I'm more suspicious of the correct detection of the end of the shift than I am of the checking logic. If a shift ends while some thread is still running, then all of the assumptions above can be wrong.

What I've done so far is merely creating an infrastructure for us to test all this stuff for real. As I add more test cases now, I'm hoping they will tell us more.

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs (hunk 14 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: This is theoretical but C# 7.0 allows `IsolateChildTests { get => false; }` as well, if you still want to use the `get` keyword without allocating a field.

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs [hunk 19]
```diff
@@ -300,9 +315,35 @@ public virtual void Cancel(bool force)
...
+        #region IDisposable Implementation
+
+        /// <summary>
+        /// Standard Dispose
+        /// </summary>
+        public void Dispose()
+        {
+            Dispose(true);
+            GC.SuppressFinalize(this);
+        }
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: I'm sorry; it crossed my mind if I should mention this originally because MSDN is out of date and misleads people. Real quick: since .NET 4.0 introduced the SafeHandle class, it's now an anti-pattern to use the `Dispose(bool)` pattern or to involve the finalizer. (The SafeHandle contains the finalizer logic and gets other special treatments. Any unmanaged resources (bare IntPtr handles) should go inside a SafeHandle class instead, and the SafeHandle, being itself a managed resource just gets disposed like any other managed object.)

Now I know we run on net35 and net20, but the same logic applies: the `WorkItem` class itself, and any subclass, will not and should not ever directly own bare unmanaged (IntPtr) handles. So as a safeguard we can remove everything except `public void Dispose() { _completionEvent.Dispose(); }`. (And we don't need the null check because the variable is readonly.)

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: ManualResetEvent on net35 and net20 already contains the finalizer logic too, so it would be redundant for the `WorkItem` class to have finalizer logic. It's already guaranteed to be disposed without `WorkItem` doing anything special.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: I know that this is counter to a lot of common practice, so it's understandable that you might want confirmation that I'm not crazy on this. 😀 This comes up a lot at dotnet/csharplang and I can loop in sharwell or someone.

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: @jnm2 I won't be changing this right away - it's also an anti-pattern to keep changing minor bits in code that is not yet even doing what it's supposed to do!!! I'll hold it in mind as I work on the next commit with actual functionality.

Based on what you are now saying, it sounds as if the initial code was correct and that WorkItem does not need to implement dispose. I understood that MRE basically took care of itself in different ways on each platform, so we didn't have to. I'm not in favor of implementing an empty Dispose "just in case". Or are you saying we need to implement and invoke DIspose solely for the purpose of getting the release done early?

Please give it some thought and answer at your leisure.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: > it's also an anti-pattern to keep changing minor bits in code that is not yet even doing what it's supposed to do!!!

Yes! :D

> Or are you saying we need to implement and invoke DIspose solely for the purpose of getting the release done early?

Yes, exactly. Deterministic release is always preferable to waiting for the garbage collector to finalize an object. One reason is that the garbage collector reacts to memory pressure but not to leaking handles so you can go for an arbitrarily large amount of time without a GC and yet still leaking kernel handles.

The finalization handling is a backstop, not a great one but a necessary one, and since it's built into ManualResetEvent we don't need to build it ourselves. But we'd prefer not to use the backstop.

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: Do we believe this to be true on all platforms, including Mono?

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: I checked Mono and it's using a SafeHandle. (https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/threading/eventwaithandle.cs)

If it's not true in a platform's BCL, it's a bug in the platform just as much as it would be a bug in NUnit if we used a bare IntPtr handle without encapsulating it in a SafeHandle class.

.NET Framework and .NET Core are identical. Mono has been incrementally replacing its BCL with .NET Core's BCL implementation. Xamarin and Unity use Mono's BCL.

Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: Sounds like the right way to go then. Ironic to be doing what was called bad practice for so long.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: This is over 3 years old, but may be relevant: http://www.mono-project.com/docs/advanced/safehandles/

**Comment by CharliePoole** [comment]
This now fixes #2395 

Restoring the queues was starting all queues, causing __everything__ to run in parallel.

**Comment by CharliePoole** [comment]
I feel like this is ready for a final review and merge. I imagine there is more to be done around parallel execution, but since this is getting pretty big I think we're better off to put it out there and fix further problems incrementally.

The parallel tests I created can be extended as needed to simulate parallel execution in other environments.

**Comment by rprouse** [comment]
I am going through these and writing repros for each of the issues to see if this PR fixes them. So far,

#1239 - I cannot reproduce on my machine, could be number of cores?
#2364 - Unit tests are enough
#2388 - Using the tests in the issue, this is **not fixed**, the given tests still fail with this code
#2395 - This looks to be a duplicate of #2388, so **likely won't be fixed**
#2467 - Confirmed to be a framework problem in 3.8.1 and **fixed** with this PR
#2471 - Confirmed **fixed**
#2478 - I think I've confirmed this by applying `Parallizable` to namespace `OneTimeSetup`s, mixing them with `TestContext.Progress.WriteLine` and `Thread.Sleep` and observing the behavior. Will also look in the code.

So, at this point, assuming the code review finds the same, all issues marked fixed except for #2388 and #2395 are fixed by this PR. We can treat those issues in a separate PR unless you feel they should be included in this PR @CharliePoole.

Code review to follow. I've done a quick pass, now doing a more detailed pass after reading and testing all the issues.

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs (hunk 19 above)
Comment (rprouse) [reply src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: @CharliePoole I don't think it is an issue since this is the way we have been doing it, but were you planning on updating this based on the comments?

File: src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs [hunk 20]
```diff
@@ -339,14 +339,60 @@ internal void Save()
         /// </summary>
         internal void Restore()
         {
-            Pause();
+            //Guard.OperationValid(State != WorkItemQueueState.Running, $"Attempted to restore state of {Name} while queue was running.");
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs]: Is this a valid guard? Should it be uncommented or deleted?

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs [hunk 21]
```diff
@@ -161,16 +170,18 @@ private void StartWorkers()
...
+                    {
                         lock (_syncRoot)
                         {
-                            // Check busy count again under the lock. If there is no work
-                            // try to restore any saved queues and end the shift.
+                            // Check again under the lock. If there is no work
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: @jnm2 said above,

> having more than one concurrency primitive in action makes me feel like everything is susceptible to race conditions. What happens if one of the queues gets an item added on a background thread right after IsEmpty returns false?

@jnm2 isn't this okay because we check `_busyCount` and `HasWork` again after getting the lock? The comment is pretty obvious, so what you are seeing is more subtle than that. Can you expand on your concern?

File: src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs [hunk 22]
```diff
@@ -242,49 +278,83 @@ private void RestoreQueues()
...
-            // TODO: Temp fix - revisit later when object model is redesigned.
-            if (StartNextShift())
-                return;
+            ShiftFinished?.Invoke(endingShift);
 
-            if (_isolationLevel > 0)
-                RestoreQueues();
+            WorkShift nextShift = null;
 
+#if false
```
[the remark this answers is not in the document]
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs]: Slipped through!

File: src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs (hunk 20 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs]: It's logically valid (in my mind) but breaks things if I use it. I think I'll keep it commented but add an explanation in front of it. At some point, someone will discover __why__ some queues end up running at a point where we are supposedly between shifts. My guess is that some other thread is getting in their and restarting things.

This is where I'd continue if I had time to do it by the way. We need one thread to detect end of shift and take care of starting next shift, restoring, etc. before any other shift tries to do the same. 

However, I think that overall this fixes a lot of things and is not any worse in the areas it doesn't fix.

File: src/NUnitFramework/framework/Internal/Execution/WorkShift.cs (hunk 21 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/WorkShift.cs]: I agree with both of you. I'm worried like @jnm2 and not seeing how it happens like @rprouse. 😄 

My observation is that things get in - it's rare but happens.

**Comment by CharliePoole** [comment]
I'll make the changes in the morning. This is far from perfect, but I think it's better than what we have and should be merged so that others can carry on from this point. In particular, the tests can be expanded and possibly the test mechanism improved.

BTW, if #2388 is not fixed, that would be because the simulation (that's what it is) of executing an assembly doesn't fully match the reality. I was hoping to avoid adding true assemblies that have to be loaded when we are working on unit tests. We need a set of tests that run out of actual assemblies to really test what happens with assembly-level attributes but I don't think they should be part of the framework tests.

That said, it may be better to improve the simulation so that we run more of the production code and less `TestBuilder` code. We may be able to inject a context right at the start with a particular (simulated) assembly-level attribute. If nobody else gets too it I may try to take it further in December.

**Comment by rprouse** [comment]
I agree that this is an improvement and something we should get in sooner than later. This is also getting huge, so it might be better to split out the remaining issues. I also agree that we need true test assemblies to test some of these things because our unit tests are not catching them. That is why I was suggesting some sort of integration tests that test some of these scenarios. Some of these issues are difficult to even test that way though. For some, I had to add in sleeps and watch the output before and after the fixes.

File: src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs]: Fixed

**Comment by CharliePoole** [comment]
I removed the fixes comment for #2388 based on your tests. However, I'm pretty sure that #2395 is fixed. It doesn't seem to be a duplicate of the other at all. According to the extract from the internal trace, multiple threads were running at the same time, when they should not have been. That is, the parallel and non-parallel workers were active simultaneously, which of course defeats their purpose.

I found this was due to an error in how the dispatcher restored queues when we switch from an isolated non-parallel situation back to the lower level parallel one. It was starting all the queues! I fixed this and I think it needs to be checked to see if there is more to fix. Best bet would be to merge and then encourage the reporter of the issue to try the dev build. Since we don't want anyone else to work on it until that is done, it seems best to close it as done.

**Comment by CharliePoole** [comment]
@rprouse I made the minor changes you requested. The only open question is whether this should really close #2395. I left that "fixes" in the description, but we can re-open it if it turns out I'm wrong.
