### PR TITLE
Correct inference of generic array

### LINKED ISSUE #3259: The type of an Array isn't inferred from properly
Using arrays of any dimension does not work in this example and ends up in the TestFixture failing to Set-up: ([System.IndexOutOfRangeException trace](https://gist.github.com/KoziLord/f781cb7ee748a69c2e40b0c480650ffd))
```CS
static object[] populateTestCases = new object[]
        {
            new object[] { new int[40], 10}
        };

        [Test, TestCaseSource(nameof(populateTestCases))]
        public void PopulateTest<T>(T[] array, T value)
        {
            foreach (var item in array)
                Assert.AreEqual(item, value);
        }
```

However using a List\<T> works fine: (The test compiles and behaves properly)
```CS
static object[] populateTestCases = new object[]
        {
            new object[] { new List<int>(40), 10}
        };

        [Test, TestCaseSource(nameof(populateTestCases))]
        public void PopulateTest<T>(List<T> array, T value)
        {
            foreach (var item in array)
                Assert.AreEqual(item, value);
        }
```

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes #3259

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/GenericMethodHelper.cs [hunk 1]
```diff
@@ -109,7 +109,9 @@ private void TryApplyArgType(Type parmType, Type argType)
             }
             else if (parmType.GetTypeInfo().ContainsGenericParameters)
             {
-                var genericArgTypes = parmType.GetGenericArguments();
+                var genericArgTypes = parmType.IsArray
+                    ? new[] { parmType.GetElementType() }
+                    : parmType.GetGenericArguments();
```
Comment (jnm2) [inline src/NUnitFramework/framework/Internal/GenericMethodHelper.cs]: This is good. Alternatively, we could fix the existing misnomer (arrays aren't technically generic) by using `parmType.GetElementType()` instead of `genericArgTypes[0]` below inside `if (argType.HasElementType)` and then moving the `var genericArgTypes` inside the `if argType.GetTypeInfo().IsGenericType ...`

**Comment by jnm2** [comment]
@mikkelbu The CI failure will be fixed if you rebase on https://github.com/nunit/nunit/pull/3258.

File: src/NUnitFramework/framework/Internal/GenericMethodHelper.cs (hunk 1 above)
Comment (mikkelbu) [reply src/NUnitFramework/framework/Internal/GenericMethodHelper.cs]: If I change it to
```csharp
                if (argType.HasElementType)
                {
                    ApplyArgType(parmType.GetElementType(), argType.GetElementType());
                }
                else if (argType.GetTypeInfo().IsGenericType && IsAssignableToGenericType(argType, parmType))
                {
                    var genericArgTypes = parmType.GetGenericArguments();
                    Type[] argTypes = argType.GetGenericArguments();

                    if (argTypes.Length == genericArgTypes.Length)
                        for (int i = 0; i < genericArgTypes.Length; i++)
                            TryApplyArgType(genericArgTypes[i], argTypes[i]);
                }
```
then two of existing tests fails
```
1) Error : NUnit.Framework.Internal.GenericMethodHelperTests.GetTypeArgumentsForMethodTests("MethodWithGenericEnumerableOfType",[Int32[]],[System.Int32])
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType(Type parmType, Type argType) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 131
   at NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType(Type parmType, Type argType) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 114
   at NUnit.Framework.Internal.GenericMethodHelper.TryGetTypeArguments(Object[] argList, Type[]& typeArguments) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 87
   at NUnit.Framework.Internal.GenericMethodHelperTests.GetTypeArgumentsForMethodTests(String methodName, Object[] args, Type[] typeArgs) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\tests\Internal\GenericMethodHelperTests.cs:line 116

2) Error : NUnit.Framework.Internal.GenericMethodHelperTests.GetTypeArgumentsForMethodTests("MethodWithGenericEnumerableOfTypeAsSecondArg",["X", Int32[]],[System.String, System.Int32])
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType(Type parmType, Type argType) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 131
   at NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType(Type parmType, Type argType) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 114
   at NUnit.Framework.Internal.GenericMethodHelper.TryGetTypeArguments(Object[] argList, Type[]& typeArguments) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 87
   at NUnit.Framework.Internal.GenericMethodHelperTests.GetTypeArgumentsForMethodTests(String methodName, Object[] args, Type[] typeArgs) in C:\src\NUnit\nunit.nunit\src\NUnitFramework\tests\Internal\GenericMethodHelperTests.cs:line 116
```
the problem is that `argType.HasElementType` is `true` (`argType` is `Int32[]`), but `parmType.GetElementType()` returns to `null`, as `parmType` is ``IEnumerable`1``.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/GenericMethodHelper.cs]: Oh! I missed that `argType` and `parmType` weren't the same variable. Thanks for the explanation!

**Comment by mikkelbu** [comment]
@jnm2 PR rebased on master
