### PR TITLE
Fixes CollectionAssert not using IEquatable of items in collections

### LINKED ISSUE #2271: When CollectionAssert.AreEqual do compare each element, it will ignore the IEquatable of the element too
With the code changes #2118 for [Issue2097](https://github.com/nunit/nunit/issues/2097), the test below still will fail, since when the `NUnitEqualityComparer` does each item comparison, the property `compareAsCollection` is still `true`,  so it will not get in the  [condition](https://github.com/nunit/nunit/blob/release/3.7/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L229), which ignoring the `IEquatable` of the element and will fail the assertion. 
```
namespace Nunit3TestsSamples {
	[TestFixture]
	class TestSample1 {

		[Test]
		public void test() {
			var set1 = new List<TestObject>() {
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" }
			};
			var set2 = new List<TestObject>() {
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" }
			};

			CollectionAssert.AreEqual( set1, set2 );
		}

		class TestObject : IEquatable<TestObject> {
			public string Value { get; set; }

			public bool Equals( TestObject other ) {
				return Value.Equals( other.Value );
			}
		}
	}
}
```

### PR DESCRIPTION
**Pull request by OmicronPersei**
Closes #2271 .

### CODE REVIEW

**Comment by CharliePoole** [comment]
Saving and restoring the `TopLevelComparison` flag seems fragile to me. What if you simply made it a parameter to `ObjectsEqual` with a default value of true. All the nested calls could then set it to false. Cleanup wouldn't be needed since it would just be on the call stack.

File: src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs [hunk 1]
```diff
@@ -85,6 +85,11 @@ internal NUnitEqualityComparer()
             };
         }
 
+        internal NUnitEqualityComparer(NUnitEqualityComparer copy)
```
Comment (CharliePoole) [inline src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs]: I can't figure out where this is used.

**Comment by OmicronPersei** [comment]
Tests still pass even if I don't change all of the calls to the equals methods but I thought it would be better to be consistent, especially if a method is refactored to make use of the new topLevelComparison flag

File: src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs (hunk 1 above)
Comment (OmicronPersei) [reply src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs]: It's not, looks like I forgot to remove it.

File: src/NUnitFramework/framework/Constraints/Comparers/DictionariesComparer.cs [hunk 2]
```diff
@@ -54,10 +54,10 @@ internal DictionariesComparer(NUnitEqualityComparer equalityComparer)
                 return false;
 
             foreach (object key in xDictionary.Keys)
-                if (!_equalityComparer.AreEqual(xDictionary[key], yDictionary[key], ref tolerance))
+                if (!_equalityComparer.AreEqual(xDictionary[key], yDictionary[key], ref tolerance, false))
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/Comparers/DictionariesComparer.cs]: Very minor, makes the code more readable IMO to use `topLevelComparison: false`.

File: src/NUnitFramework/framework/Constraints/Comparers/IChainComparer.cs [hunk 3]
```diff
@@ -36,10 +36,11 @@ internal interface IChainComparer
         /// <param name="x">The first object to compare.</param>
         /// <param name="y">The second object to compare.</param>
         /// <param name="tolerance">The tolerance to use when comparing the objects.</param>
+        /// <param name="topLevelComparison">Flag indicating whether or not this is the top level comparison.</param>
         /// <returns>
         ///     <c>null</c> if the objects cannot be compared using the method.
         ///     Otherwise the result of the comparison is returned.
         /// </returns>
-        bool? Equal(object x, object y, ref Tolerance tolerance);
+        bool? Equal(object x, object y, ref Tolerance tolerance, bool topLevelComparison = true);
```
Comment (jnm2) [inline src/NUnitFramework/framework/Constraints/Comparers/IChainComparer.cs]: The only reason to use default values is for the convenience of the caller. Is `IChainCaller` directly called a lot? I have a small preference for making things explicit at the call site. We don't want to make it easy for future developers to miss the significance of the decision going into the parameter.

File: src/NUnitFramework/tests/Assertions/CollectionAssertTest.cs [hunk 4]
```diff
@@ -220,6 +220,62 @@ public void AreEqual_UsingIterator()
...
+            IEnumerable set1 = new SimpleEnumerableWithIEquatable("x", "y", "z");
+            IEnumerable set2 = new SimpleEnumerableWithIEquatable("x", "z", "z");
+
+            Assert.AreNotEqual(set1, set2);
+
+            Assert.Throws<AssertionException>(() => CollectionAssert.AreEqual(set1, set2));
+        }
+
+        [Test]
+        public void IEnumerablesAreEqualWithCollectionsObjectsImplemetingIEquatable()
```
Comment (jnm2) [inline src/NUnitFramework/tests/Assertions/CollectionAssertTest.cs]: `Implemeting` is typo

File: src/NUnitFramework/tests/Assertions/CollectionAssertTest.cs [hunk 5]
```diff
@@ -220,6 +220,62 @@ public void AreEqual_UsingIterator()
...
+        //}
+
+        //[Test]
+        //public void IEnumerablesAreNotEqualWithCollectionObjectsImplementingOverridenEquals()
+        //{
+        //    IEnumerable set1 = new SimpleEnumerable(new SimpleOverridenEqualsObj());
+        //    IEnumerable set2 = new SimpleEnumerable(new SimpleOverridenEqualsObj(), new SimpleOverridenEqualsObj());
+
+        //    CollectionAssert.AreNotEqual(set1, set2);
+        //}
```
Comment (jnm2) [inline src/NUnitFramework/tests/Assertions/CollectionAssertTest.cs]: Why leave the commented-out code?

File: src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs [hunk 6]
```diff
@@ -54,4 +54,69 @@ public IEnumerator GetEnumerator()
 
         #endregion
     }
+
+    class SimpleEnumerableWithIEquatable : IEnumerable, IEquatable<IEnumerable<object>>
```
Comment (jnm2) [inline src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs]: I'm confused why this isn't either `IEquatable<SimpleEnumerableWithIEquatable>` or `IEquatable<IEnumerable>`?
The class doesn't implement `IEnumerable<object>` so right now it is not equatable to itself.

File: src/NUnitFramework/framework/Constraints/Comparers/DictionariesComparer.cs (hunk 2 above)
Comment (OmicronPersei) [reply src/NUnitFramework/framework/Constraints/Comparers/DictionariesComparer.cs]: That works!  I didn't even know that was valid C# syntax... how long has that been a language feature?

Comment (jnm2) [reply src/NUnitFramework/framework/Constraints/Comparers/DictionariesComparer.cs]: 1.0 I think :D

Comment (CharliePoole) [reply src/NUnitFramework/framework/Constraints/Comparers/DictionariesComparer.cs]: 4.0 actually.

File: src/NUnitFramework/framework/Constraints/Comparers/IChainComparer.cs (hunk 3 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Constraints/Comparers/IChainComparer.cs]: I geneally feel the same way but I have to disagree in this case. The external caller, which actually makes the top level call, should not have to say "This is a top level call" and should not be able to say "This is not a top level call."

 Admittedly, exposing the argument this way is a bit of a compromise. I suggested it because it allows keeping the information about whether it's a top level call on the stack.

**Comment by OmicronPersei** [comment]
All good, then?

File: src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs [hunk 7]
```diff
@@ -54,4 +54,59 @@ public IEnumerator GetEnumerator()
 
         #endregion
     }
+
+    class SimpleEnumerableWithIEquatable : IEnumerable<object>, IEquatable<SimpleEnumerableWithIEquatable>
+    {
+        public List<object> Contents { get; private set; } = new List<object>();
```
Comment (oznetmaster) [inline src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs]: Why the initializer?

Both constructors initialize the value of Contents, so this default initialization is redundant.

Comment (jnm2) [reply src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs]: Good catch; also the private set is unnecessary.

Comment (OmicronPersei) [reply src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs]: Just saw this, should I write a PR to do this small refactor?  Don't mind, just not sure if it's "PR worthy" or something like that since it is pretty minor.

Comment (ChrisMaddock) [reply src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs]: If you're willing, a small PR would be great. 😄

Comment (jnm2) [reply src/NUnitFramework/tests/TestUtilities/Collections/SimpleEnumerable.cs]: I agree. If something just makes sense to do, I don't care how small it is. =)
