### PR TITLE
MacOSX and XBox could not be excluded on CF

### LINKED ISSUE #878: Cannot exclude MacOSX or XBox platforms when running on CF
The CF build #if's the MacOSX and XBox platform code out. This doesn't make a difference when including platforms, but any platform exclusions for these will fail because CF sees them as an invalid platform identifier.

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #878

### CODE REVIEW

**Comment by rprouse** [comment]
Travis failure was unrelated. Restarted the failing build.

**Comment by CharliePoole** [comment]
That's why we don't like attributes to just fail with invalid data - if no workaround can be found, they have to throw in such a way that the test fails no matter what was being tested for, but with a decent message. Your fix avoids the problem. Let's let Neil look at it too before merging.

File: src/NUnitFramework/framework/Internal/OSPlatform.cs [hunk 1]
```diff
@@ -291,7 +291,17 @@ public bool IsWinCE
             get { return platform == PlatformID.WinCE; }
         }
 
-#if !NETCF
+#if NETCF
+        /// <summary>
+        /// Return true if the platform is Xbox
+        /// </summary>
+        public bool IsXbox { get { return false; } }
```
Comment (oznetmaster) [inline src/NUnitFramework/framework/Internal/OSPlatform.cs]: CF has PlatformID.Xbox defined.  Why not just use it and not special case it?

Comment (oznetmaster) [inline src/NUnitFramework/framework/Internal/OSPlatform.cs]: Unix and Xbox were added in .NET 3.5,

Do they both need to be conditioned for builds before 3.5?

Comment (oznetmaster) [inline src/NUnitFramework/framework/Internal/OSPlatform.cs]: Since we add UnixPlatformID_Microsoft and UnixPlatformID_Mono as out own defines to handle builds < 3.5, why not add MaxOSXPlatformID as a static value in OSPlatform as well.  It did not exist before 3.5 either.  Then, no conditional would be required.

**Comment by rprouse** [comment]
@oznetmaster, Do you have time to make the additional changes you suggested? I can do them, but I don't have the computer to test on CF with me. If not, should we just merge this to get the CF tests passing?

**Comment by CharliePoole** [comment]
As commented on the issue, I'll take a look at it.

@oznetmaster any review of outstanding issues marked for the beta 5 will be helpful!

**Comment by rprouse** [comment]
I have pushed the changes as suggested by @oznetmaster. The previous commit is tested on CF, but I only tested the latest on Windows. Last commit is pretty trivial though. **Merge when reviewed**

@oznetmaster or @CharliePoole, you mentioned the it was fairly straightforward to test on CF. That isn't my experience, so could you tell me what I am doing wrong? I build and deploy/run on an emulator, but because there is no UI, I map a folder on my computer to the device, copy the test results XML to that folder, open it on my computer in Notepad++ and read through the XML.

Is there an easier way? Should the test output be going to the output window in Visual Studio? Should I be running a different way?

**Comment by oznetmaster** [comment]
That is pretty much how I do it.

 

However, I have multiple GUI based Nunit result viewer programs, so I do not use Notepad to view the results.

**Comment by oznetmaster** [comment]
The code looks correct to me, but I cannot try to compile it.

Is the CI failure one of the spurious ones?

**Comment by CharliePoole** [comment]
Under CF, no console is assumed (and none of the emulators have them) You
have to direct output to a file using --out:TestResult.xml (don't use a
path). The file appears in the My Documents folder of the emulator.

I'll review it and if it looks like I need to test I will do that. I run
all the tests before releasing anyway.

**Comment by CharliePoole** [comment]
Looks good to me. Since I'm about to do a whole set of pre-release tests, I'm going to merge it, betting that it won't cause me any problems. If it does, I'll fix 'em.
