### PR TITLE
All Assert messages must be non-null

### LINKED ISSUE #4432: Fix null message in internal static string? ExtendedMessage(string methodName, string? message, string actualExpression, string constraintExpression)
Ref comment in PR #4430 

> The message comes from the _getExceptionMessageoverloads which are declared asFunc<string?>. Also there are some NUnit tests (e.g. LifeCycleAttributeTest) that pass in result.Messagewhich is also declaredstring?`.
If we want to change all that, I would do that in a separate PR.

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #4432 

We need to use `NUnitString = default` for the cases where the user does not specify an error.
This will call the `struct` hidden default constructor that initializes all fields with null.
Although the user cannot specify a null string (as there is no converter for it), the compiler can.

### CODE REVIEW

**Comment by manfred-brands** [comment]
@OsirisTerje Is there something wrong with the myget feed?
Do we even need it inside the repo?

**Comment by OsirisTerje** [comment]
@manfred-brands Seems like myget.org is down.
I believe we only need it for the appveyor, but not sure, never actually looked into it.

**Comment by OsirisTerje** [comment]
I don't really see myget.org to be needed in the project, suggest you just comment it out.

File: src/NUnitFramework/framework/NUnitString.cs [hunk 1]
```diff
@@ -43,6 +44,6 @@ public NUnitString(string? message)
         public static implicit operator NUnitString(string? message) => new(message);
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/NUnitString.cs:44]: This is the one that causes the build errors.  
Do we need the nullable string in here?  (Was a comment on some other PR I think, and perhaps we need to tackle the Result class too? )

**Review by OsirisTerje — APPROVED** [review]

File: src/NUnitFramework/framework/NUnitString.cs (hunk 1 above)
Comment (OsirisTerje) [reply src/NUnitFramework/framework/NUnitString.cs:44]: Looked very quickly at it, seems like it can be non-null since you have fixed the nullability in the Result class, if I am not missing something.

Comment (manfred-brands) [reply src/NUnitFramework/framework/NUnitString.cs]: Somehow I missed this one. Fixed.
