### PR TITLE
Use Synchronized writer for captured results

### LINKED ISSUE #1406: TextCapture is not threadsafe but is used to intercept calls that are expected to be threadsafe.
It looks like the TextWriter used in https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/TextCapture.cs is not thread safe, but the TextCapture is used to intercept  Console.WriteLine (which itself is thread safe).

A solution would be to use a synchronized TextWriter?

This is the stack trace I'm seeing in one of my tests
```
Unhandled Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: destinationIndex
  at System.Text.StringBuilder.ThreadSafeCopy (System.Char* sourcePtr, System.Char[] destination, Int32 destinationIndex, Int32 count) <0x1909ea0 + 0x000aa> in <filename unknown>:0 
  at System.Text.StringBuilder.Append (System.Char* value, Int32 valueCount) <0x1909970 + 0x0004c> in <filename unknown>:0 
  at System.Text.StringBuilder.Append (System.Char[] value, Int32 startIndex, Int32 charCount) <0x1906ec0 + 0x000a4> in <filename unknown>:0 
  at System.IO.StringWriter.Write (System.Char[] buffer, Int32 index, Int32 count) <0x185b9a0 + 0x0009f> in <filename unknown>:0 
  at System.IO.TextWriter.WriteLine (System.String value) <0x185e090 + 0x00174> in <filename unknown>:0 
  at NUnit.Framework.Internal.Execution.TextCapture.WriteLine (System.String value) <0x7d0900 + 0x0004a> in <filename unknown>:0 
  at System.Console.WriteLine (System.String value) <0x1b1a540 + 0x00045> in <filename unknown>:0 
```

### PR DESCRIPTION
**Pull request by CharliePoole**
This fixes #1406 

In framework builds that support parallel execution, TestResult now uses a synchronized TextWriter to write to the buffer that is used for text capture. This allows multiple threads that are part of the same test to write text safely.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 1]
```diff
@@ -194,12 +195,16 @@ public System.Collections.Generic.IList<ITestResult> Children
...
         /// Gets a TextWriter, which will write output to be included in the result.
         /// </summary>
-        public StringWriter OutWriter
+        public TextWriter OutWriter
         {
             get
             {
                 if (_outWriter == null)
-                    _outWriter = new StringWriter();
+#if PORTABLE || SILVERLIGHT
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs]: So, not fixed for Portable or SL. Should we create a secondary issue?

**Comment by CharliePoole** [comment]
Well, they don't support parallel, so I think it's OK.

**Comment by rprouse** [comment]
Good point. Reviewing too early in the morning :smile:

File: src/NUnitFramework/framework/Internal/Results/TestResult.cs [hunk 2]
```diff
@@ -194,12 +195,16 @@ public System.Collections.Generic.IList<ITestResult> Children
         /// <summary>
         /// Gets a TextWriter, which will write output to be included in the result.
         /// </summary>
-        public StringWriter OutWriter
+        public TextWriter OutWriter
         {
             get
             {
                 if (_outWriter == null)
```
Comment (jtattermusch) [inline src/NUnitFramework/framework/Internal/Results/TestResult.cs]: Btw, the lazy initialization is not threadsafe. So if you are very unluckly, you can end up with two separate StringWriter instances writing to the same _output (each of them is synchronized on its own), which is still not threadsafe.

**Comment by CharliePoole** [comment]
Ouch! Good catch. I'll put in a fix.

**Comment by jtattermusch** [comment]
If I'm not mistaken, there are more places where things get lazy initialized across the stack. Ideally, all of them should be reviewed. Btw, the lazy initialization doesn't really buy much in cases like this one, so I think it would be safer to initialize things in constructor unless there is some costly resource getting created when during the lazy initialization.

**Comment by rprouse** [comment]
@jtattermusch I agree with the comment about lazy initialization. I will create an issue to track this since it is on a closed PR. Thanks for the review.

**Comment by CharliePoole** [comment]
I used a regular expression to find properties with lazy initialization. I'll write individual comments about each of these as needed.

1. ParallelWorkItemDispatcher.ParallelQUeue
2. ParallelWorkItemDispatcher.ParallelSTAQUeue
3. ParallelWorkItemDispatcher.NonParallelQUeue
4. ParallelWorkItemDispatcher.NonParallelSTAQUeue
5. OSPlatform.CurrentPlatform
6. Randomizer.SeedGenerator
7. TestResult.Children
8. RuntimeFramework.CurrentFramework
9. TestExecutionContext.CurrentContext
10. TestExecutionContext.Dispatcher
11. TestExecutionContext.RandomGenerator
