### PR TITLE
Respect ApartmentState when running tests in Parallel

### LINKED ISSUE #2288: Killing thread cancels test run
I've only seen this once, but it's pretty scary. In the following CI build, an entire test run is cancelled while we are testing ThreadUtility.Kill. I've never see this before.

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.8.0-ci-04129-pr-2287

### LINKED ISSUE #2426: Regression in 3.8.1: ApartmentAttribute no longer works when applied to an assembly
Create a test project containing the following test:

```
[assembly:Apartment(ApartmentState.STA)]
namespace TestProject
{
    [TestFixture]
    public class TestFixture
    {
        [Test]
        public void Test()
        {
            if (Thread.CurrentThread.GetApartmentState() != ApartmentState.STA)
            {
                throw new ThreadStateException("The current threads apartment state is not STA");
            }
        }
    }
}
```

Compile it against NUnit 3.7.1 - Test Passes
Compile it against NUnit 3.8.1 - Test Fails

Compile it against NUnit 3.8.1 but with the `[Apartment]` attribute on the TestFixture - Test Passes
Compile it against NUnit 3.8.1 but with the `[Apartment]` attribute on the Test - Test Passes

Note that this bug is present in 3.8.0 as well as 3.8.1

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #2426 Confirmed by adding the tests from the issue to an integration test project.
Fixes #2288 Confirmed by adding the tests from this issue to the framework tests.

Walking through the code, I think this used to work before because test methods were not run in parallel. Because of this, if their parent was running STA, the tests would just run in that thread. Now the tests are possibly run in parallel too, they cannot rely on their parent. It still worked for simple tests where the test was the direct child of whatever was marked STA, but not more than one level of difference.

This fix has the tests walk up their parent hierarchy until they find the first level that specifies an `ApartmentState` other than `Unknown`. The tests then assume they should be running in the `ApartmentState` that their parent specifies.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/Execution/WorkItem.cs [hunk 1]
```diff
@@ -527,7 +525,24 @@ private ParallelExecutionStrategy GetExecutionStrategy()
...
+        /// <see cref="ApartmentState"/> has been set on any of the parent tests.
+        /// </summary>
+        static ApartmentState GetTargetApartment(ITest test)
+        {
+            var apartment = test.Properties.ContainsKey(PropertyNames.ApartmentState)
+                ? (ApartmentState)test.Properties.Get(PropertyNames.ApartmentState)
+                : ApartmentState.Unknown;
 
+            if (apartment == ApartmentState.Unknown && test.Parent != null)
+                return GetTargetApartment(test.Parent);
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/Execution/WorkItem.cs]: This is the meat of the fix, the rest is pretty much just tests.

**Comment by rprouse** [comment]
@CharliePoole just to be sure, I added tests that request a different apartment than their parent. I also created versions of the tests that are non-parallel. I then stepped through the `ParallelWorkItemDispatcher`. Each of these was executed with a `ParallelExecutionStrategy` of `Parallel` or `NonParallel` as appropriate, never `Direct`. Based on this, I think we are good. Just waiting for the CI to pass on the newly added tests.

**Comment by jnm2** [comment]
Sorry @rprouse, was just about to review since I pushed the PR I was head-down on. Looks excellent.
