### PR TITLE
Fix for Matches<T>(Predicate<T>) not accepting null for nullable types

### LINKED ISSUE #2533: Matches<T>(Predicate<T>) throws ArgumentException or Fails when actual is null
**Class:** `NUnit.Framework.Constraints.ConstraintExpression`
**Method:** `Constraint Matches<TActual>(Predicate<TActual> predicate)`

Hello,
I'm trying to use the Matches constraint that takes a predicate but I'm getting an ArgumentException:

> System.ArgumentException : The actual value is not of type String
> Parameter name: actual

or the test fails:

> Expected: <System.String> and value matching lambda expression
> But was:  null

I would expect the test to succeed/pass without an exception.

The same can be achieved with the Null.Or.Empty constraint, but I need to provide the predicate as parameter to the test method and the parameter cannot depend to the NUnit framework.

I'm assuming that the problem is at the [line 70 of the PredicateConstraint](https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Constraints/PredicateConstraint.cs#L70), but I can be wrong.
It checks if the actual passed to the ApplyTo method is of the type defined in the predicate. Since the actual passed is null, the check fails.

Thank you for your time.

## Test code:
```csharp
[TestFixture]
public class MatchesPredicateTests {

    [Test]
    public void HasAll_Matches_predicate_fails_When_actual_is_null_string() {
        var actuals = new[] {"", null};
        Predicate<String> predicate = o => (o == null) || (o == String.Empty);

        Assert.That(actuals, Has.All.Null.Or.Empty); // <-- Success
        Assert.That(actuals, Has.All.Matches(predicate)); // <-- Failure
    }

    [Test]
    public void Matches_predicate_fails_When_actual_is_null_string() {
        var actuals = new[] {"", null};
        Predicate<String> predicate = o => (o == null) || (o == String.Empty);

        foreach (String actual in actuals) {
            Assert.That(actual, Is.Null.Or.Empty); // <-- Success
            Assert.That(actual, Is.TypeOf<String>().And.Matches(predicate)); // <-- Failure
        }
    }

    [Test]
    public void HasAll_Matches_predicate_fails_When_actual_is_null_int() {
        var actuals = new Int32?[] {0, null};
        Predicate<Int32?> predicate = o => (o == null) || (o == 0);

        Assert.That(actuals, Has.All.Null.Or.Zero); // <-- Success
        Assert.That(actuals, Has.All.Matches(predicate)); // <-- Failure
    }

    [Test]
    public void Matches_predicate_fails_When_actual_is_null_int() {
        var actuals = new Int32?[] {0, null};
        Predicate<Int32?> predicate = o => (o == null) || (o == 0);

        foreach (Int32? actual in actuals) {
            Assert.That(actual, Is.Null.Or.Zero); // <-- Success
            Assert.That(actual, Is.TypeOf<Int32?>().And.Matches(predicate)); // <-- Failure
        }
    }

}
```

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2533.

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/ConstraintUtils.cs [hunk 1]
```diff
@@ -32,16 +31,18 @@ namespace NUnit.Framework.Internal
...
-        /// and that it is not null.
+        /// Requires that the provided object is actually of the type required.
         /// </summary>
         /// <param name="actual">The object to verify.</param>
         /// <param name="paramName">Name of the parameter as passed into the checking method.</param>
-        /// <typeparam name="T">The type to require.</typeparam>  
-        /// <returns>A properly typed object, or throws. Never null.</returns>
-        public static T RequireActual<T>(object actual, string paramName)
+        /// <param name="allowNull">
+        /// If <typeparamref name="T"/> can be null, returns null rather than throwing when <paramref name="actual"/> is null.
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Internal/ConstraintUtils.cs]: Perhaps we should state that this only is the case when `allowNull` is true, but perhaps this is implicit?

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/ConstraintUtils.cs]: I'm always interested in making things clearer. `If <see langword="true"/> and`?

**Comment by jnm2** [comment]
Oops, thanks for fixing my typo! :D

**Comment by jnm2** [comment]
The tests are difficult to read; I was just complaining about that over at https://github.com/nunit/nunit/issues/1215#issuecomment-342920782 Want to help? \</nerdsnipe> 😁

File: src/NUnitFramework/framework/Internal/ConstraintUtils.cs (hunk 1 above)
Comment (mikkelbu) [reply src/NUnitFramework/framework/Internal/ConstraintUtils.cs]: Sounds good

**Comment by mikkelbu** [comment]
Perhaps next week. Currently, all I've time for are small reviews :(

**Comment by jnm2** [comment]
That's completely fine.

**Comment by jnm2** [comment]
My push dismissed your review, sorry.

**Comment by jnm2** [comment]
Heard. 👍

**Comment by oznetmaster** [comment]
I added some line comments to the PredicateRestrainTests.cs code, forgetting, as usual, that no notification of those comments is sent :(

**Comment by jnm2** [comment]
I can't find any commit comments, and I didn't even force push or anything.

**Comment by oznetmaster** [comment]
[https://github.com/nunit/nunit/commit/34026d878bbc8234b3c3efd179b0cbb9c72b4e3e](url)

File: src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs [hunk 2]
```diff
@@ -52,5 +55,46 @@ public void CanUseConstraintExpressionSyntax()
...
+        [TestCase(typeof(object))]
+        [TestCase(typeof(string))]
+        [TestCase(typeof(int?))]
+        [TestCase(typeof(AttributeTargets?))]
+        public static void ActualMayBeNullForNullableTypes(Type type)
+        {
+            // https://github.com/nunit/nunit/issues/1215
+            var methodInfo = typeof(PredicateConstraintTests)
+                .GetMethods(BindingFlags.NonPublic | BindingFlags.Static)
+                .Single(method => method.Name == nameof(ActualMayBeNullForNullableTypes) && method.GetParameters().Length == 0)
```
Comment (oznetmaster) [inline src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs]: Isn't the test for the number of parameters redundant since there is only one matching method?

File: src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs [hunk 3]
```diff
@@ -52,5 +55,46 @@ public void CanUseConstraintExpressionSyntax()
...
+        }
+
+        [TestCase(typeof(int))]
+        [TestCase(typeof(AttributeTargets))]
+        public static void ActualMustNotBeNullForNonNullableTypes(Type type)
+        {
+            // https://github.com/nunit/nunit/issues/1215
+            var methodInfo = typeof(PredicateConstraintTests)
+                .GetMethods(BindingFlags.NonPublic | BindingFlags.Static)
+                .Single(method => method.Name == nameof(ActualMustNotBeNullForNonNullableTypes) && method.GetParameters().Length == 0)
```
Comment (oznetmaster) [inline src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs]: Isn't the test for the number of parameters redundant since there is only one matching method?

**Comment by oznetmaster** [comment]
Well, I added them again...

**Comment by jnm2** [comment]
Wait duh... *this* is the PR where I force-pushed. I got mixed up.

File: src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs (hunk 2 above)
Comment (jnm2) [reply src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs]: Yes. I see I overlooked that while juggling different approaches. The compatibility extension methods are far from complete; sometime I am going to flesh them out.

Comment (oznetmaster) [reply src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs]: I only noticed because GetParameters cannot be used on an open generic method in CF.  Since it was redundant anyway, I just removed it in my build.

Comment (jnm2) [reply src/NUnitFramework/tests/Constraints/PredicateConstraintTests.cs]: Oh, very interesting!

**Comment by mikkelbu** [comment]
@oznetmaster I got notifications about your comments (both before and now), so I think that it is working.

Ps. I edited your link to make it work.

**Comment by jnm2** [comment]
Huh, that's so weird!
