### PR TITLE
Fixed deadlocks on known synchronization contexts

### LINKED ISSUE #2123: Task.Run inside a test will result in deadlock if a control was created previously
Hi,

I'm not sure whether an issue with NUnit but the following test will always result in a deadlock:

```
[Test]
public async Task Deadlock()
{
    new Control();

    await Task.Run(() => { int x = 42; });
}
```

Version used: **3.6.1**

Thanks,
Costin

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2123, re: https://github.com/nunit/nunit/issues/2774

The first commit enabled me to quickly test because I was without internet, so build.cake couldn't pull the console runner from NuGet, and VS required my license to be refreshed.

I left some notes in the source about the later general-awaitable PR.

All reviews welcome, as usual. @sharwell, since you're knowledgeable in this area and you hit the bug, would you please review?

### CODE REVIEW

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+                context.Post(
+                    state => ((AwaitAdapter)state).OnCompleted(Application.Exit),
+                    state: awaitable);
+
+                Application.Run();
+            }
+        }
+
+#if !NET20
+        private sealed class WpfMessagePumpStrategy : MessagePumpStrategy
```
Comment (sharwell) [inline src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: :bulb: `DispatcherMessagePumpStrategy`

File: src/NUnitFramework/tests/SynchronizationContextTests.cs [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+using NUnit.TestData;
+using NUnit.TestUtilities;
+
+#if ASYNC
+using System.Threading.Tasks;
+#endif
+
+namespace NUnit.Framework
+{
+    public static class SynchronizationContextTests
```
Comment (sharwell) [inline src/NUnitFramework/tests/SynchronizationContextTests.cs]: :bulb: Several of these tests would benefit from assertions relating to the thread(s) on which code is executed.

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 1 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: You're right, but Dispatcher is such a generic name. Is it used for anything but WPF?

**Comment by jnm2** [comment]
@sharwell SingleThreadedSyncronization is coming in the next PR.

**Comment by jnm2** [comment]
WIP is for the net40 tests till I get a chance to look at this.

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 1 above)
Comment (CharliePoole) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: Worse than generic... it has a specific use already in the codebase. The WorkItemDispatcher is the thing that dispatches the work items that constitute the implementation of a test. We have three different dispatchers that do this in different ways.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: This is a private nested class, so if you're seeing the name you're also seeing that it's coupled to DispatcherSynchronizationContext. I'm less worried there and more just intent on... um, bikeshedding. 😎

**Comment by jnm2** [comment]
Yikes, caught the problem. Application.Exit and Dispatcher.ExitAllFrames were being called on the awaiter's continuation thread rather than being posted back to the synchronization context. That's pretty bad.

**Comment by jnm2** [comment]
Fixed the WaitForCompletion implementations and added thread assertions per @sharwell's review.

**Comment by jnm2** [comment]
Oh great, Mono is doing this in CI:

```
The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'System.Windows.Forms.XplatUI' threw an exception.
  ----> System.ArgumentNullException : Could not open display (X-Server required. Check your DISPLAY environment variable)
Parameter name: Display
```

And for `new DispatcherSynchronizationContext()`:
```
System.NotImplementedException : The method or operation is not implemented.
```

**Comment by jnm2** [comment]
I see that CI will pass. Ready for review.

**Comment by jnm2** [comment]
@rprouse Is this PR close enough to something you'd approve that I can start the next PR (continuing on the STA thread after an await) based on this one?

File: src/NUnitFramework/framework/Internal/AwaitAdapter.cs [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
+// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
+// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
+// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
+// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+// ***********************************************************************
+
+using System;
+
+#if ASYNC
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: The `AwaitAdapter` is only used in `AsyncInvocationRegion` which is only used when `ASYNC` is defined, so why isn't the whole class wrapped in `#if ASYNC` and why the `#ifdef` for other platforms that don't support async? Future PR?

Comment (rprouse) [reply src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: By other platform `#ifdef`s, I mean in the following files which could also be wrapped in an `#if ASYNC`.

File: src/NUnitFramework/framework/Internal/AwaitAdapter.cs [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+            {
+                if (action == null) return;
+
+                // Mimick TaskAwaiter.UnsafeOnCompleted
+                _task.ContinueWith(_ => action.Invoke(), TaskScheduler.FromCurrentSynchronizationContext());
+            }
+
+            public override void BlockUntilCompleted()
+            {
+                // Mimick TaskAwaiter.GetResult
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: Can you point to documentation on this and the mimic UnsafeOnCompleted above to help bring us up to speed?

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+
+namespace NUnit.Framework.Internal
+{
+    internal abstract class MessagePumpStrategy
+    {
+        public abstract void WaitForCompletion(AwaitAdapter awaitable);
+
+        public static MessagePumpStrategy FromCurrentSynchronizationContext()
+        {
+#if NET20 || NET35 || NET40 || NET45
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: Once again, why the support for platforms that don't support async?

File: src/NUnitFramework/testdata/On.cs [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+// ***********************************************************************
+
+using System;
+using System.Threading;
+
+namespace NUnit.TestData
+{
+    public static class On
+    {
+        public static IDisposable Dispose(Action action)
```
Comment (rprouse) [inline src/NUnitFramework/testdata/On.cs]: Some doc comments to explain what this is and what it does so people don't have to read through the code? Cool little helper, didn't you have this in another PR awhile ago?

File: src/NUnitFramework/tests/Extensions.cs [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+// ***********************************************************************
+
+using System;
+using NUnit.Framework.Interfaces;
+
+namespace NUnit.Framework
+{
+    internal static class Extensions
+    {
+        public static void AssertPassed(this ITestResult result)
```
Comment (rprouse) [inline src/NUnitFramework/tests/Extensions.cs]: Another useful utility, but we should add doc comments 😉

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 5 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: Originally this file wasn't related to C#'s async. Now that I've changed it to receive an object so that the message pump strategy can decide whether to use a callback or to block, and I called the object AwaitAdapter, it really makes sense to make this only show up along with async support. I'll use `ASYNC`.

File: src/NUnitFramework/framework/Internal/AwaitAdapter.cs (hunk 3 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: 🗨 https://github.com/nunit/nunit/pull/2776#discussion_r177935936

File: src/NUnitFramework/testdata/On.cs (hunk 6 above)
Comment (jnm2) [reply src/NUnitFramework/testdata/On.cs]: 😊 Yes I did, https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine.tests/Helpers/On.cs

**Comment by jnm2** [comment]
Awesome, thanks! I will add documentation.

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 5 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: Once I add `#if ASYNC` at the top, here I'll need to choose between doing `#if !(NETSTANDARD1_6 || NETSTANDARD2_0)` and `#if NET40 || NET45`.

File: src/NUnitFramework/framework/Internal/AwaitAdapter.cs (hunk 3 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: A future PR might remove the need for most of our #if ASYNC, but that should be done atomically.

**Comment by jnm2** [comment]
@rprouse Ready for review. Boarding a plane so I won't have internet for a few hours.

**Comment by jnm2** [comment]
False alarm, introduced a build error with the fuller polyfill.

**Comment by jnm2** [comment]
Ready now.

**Comment by jnm2** [comment]
@rprouse Sorry, I forgot to re-ping you.

**Comment by rprouse** [comment]
@jnm2 I'm booked up today. I'll try to take a look tomorrow.

File: src/NUnitFramework/framework/Internal/AwaitAdapter.cs [hunk 8]
```diff
@@ -0,0 +1,114 @@
...
+
+            var task = awaitable as Task;
+            if (task == null)
+                throw new NotImplementedException("Proper awaitable implementation to follow.");
+
+#if NET40
+            // TODO: use the general reflection-based awaiter if net40 build is running against a newer BCL
+            return new Net40BclTaskAwaitAdapter(task);
+#else
+            return new TaskAwaitAdapter(task);
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: What about `ValueTask`?

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+
+        public static MessagePumpStrategy FromCurrentSynchronizationContext()
+        {
+#if NET40 || NET45
+            var context = SynchronizationContext.Current;
+
+            if (context is WindowsFormsSynchronizationContext)
+                return WindowsFormsMessagePumpStrategy.Instance;
+
+            if (context is DispatcherSynchronizationContext)
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: Will we need to be adding additional message pump strategies for other platforms like Xamarin, possibly Unity?

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs [hunk 10]
```diff
@@ -0,0 +1,136 @@
...
+                return WpfMessagePumpStrategy.Instance;
```
Comment (rprouse) [inline src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: Is this used for UWP also?

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 9 above)
Comment (rprouse) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: If so, do we need issues to track these or do we wait for user requests?

File: src/NUnitFramework/testdata/On.cs [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+    /// <summary>
+    /// Enables the <see cref="On.Dispose"/> syntax.
+    /// </summary>
+    public static class On
+    {
+        /// <summary>
+        /// Wraps an action so that it is executed when the returned object is disposed.
+        /// This disposal is thread-safe and the action will be executed at most once.
+        /// </summary>
+        public static IDisposable Dispose(Action action)
```
Comment (rprouse) [inline src/NUnitFramework/testdata/On.cs]: Didn't you try to get this into an earlier pull requests? 😄 

Nice little utility 👍

File: src/NUnitFramework/framework/Internal/AwaitAdapter.cs (hunk 8 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/AwaitAdapter.cs]: I'm hoping to add support for awaitables (versus just Task as we have supported so far) in the third PR.

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 9 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: @rprouse I don't know enough about Xamarin and Unity to know whether they run message pumps.
https://developer.xamarin.com/api/type/Android.OS.Looper/ suggests that they do, but unless we can test these in CI, I'm not inclined to do any work on them. I spent an hour trying to figure out why VS starts the Visual Studio Android emulator but never finishes deploying a Xamarin Android project to it, so suffice it to say that I'm not in great shape for that on my main machine.

Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: \<rant>
The state of Android emulation on Windows is unreasonable. HAXM is no good because it requires me to shut down my Hyper-V virtual machines, one of which is a server, not to mention Docker. ARM is ten times slower since it's not hardware accelerated. The Visual Studio Android Emulator is perfect because it's accelerated and works without disabling Hyper-V, but I've never gotten it to work on my new machine and they only have up to API level 23 images.
\</rant>

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 10 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: No, but TIL UWP has its own: https://docs.microsoft.com/uwp/api/Windows.UI.Core.CoreDispatcher

**Comment by jnm2** [comment]
> Looks good, although the message pump strategies are a bit over my head

I have failed 😭 lol.

### Background

In a nutshell: -> **We are forced to run an async thing synchronously.**
(That is what we are adapting here. In general you *never ever* do this, but since NUnit is a framework and is the entry point to all user code, it can be excused. The entirety of NUnit's threading model expects us to block the worker thread until the test is finished, whether or not it is asynchronous.)

So let's say you do the obvious thing. You adapt async to sync by having NUnit's worker thread call .`Wait()` (or `.GetAwaiter.GetResult()`. The worker thread blocks until the awaitable is completed.
So what happens when some awaitables (like `Task`) schedule part of their execution by posting it to some kind of message queue to execute on the original thread? Well, the original thread is still blocked on `.Wait()` and won't wake up until the whole task is completed—and at the same time, the task can't complete unless the original thread _does_ wake up, pulls the continuation out of the queue, executes it, and goes back to waiting for the task to signal that it is totally finished executing. That can't happen via `Wait()`, so they wait for each other forever. There is a deadlock.

### Solution

-> **Instead of `Wait()` I call `Application.Run()`.**
It runs a message loop, so any time an async thing schedules part of its execution on the Windows Forms thread while we're waiting, it gets executed as intended. Voila, no deadlocks!

`Application.Run()` does not return to the caller until `Application.Exit()` is called. Therefore:
-> **instead of `task.Wait()`, we want to call `task.GetAwaiter().OnCompleted(Application.Exit)`**.
That means as soon as the task is complete it puts the action `Application.Exit()` in the queue to be executed by the message loop inside Application.Run(). As soon as the loop pulls that action out of the queue and executes it, that signals it to shut itself down instead of waiting for the next message. Thus, it returns back to the NUnit worker thread that called it.

That's all there is to the general idea! Of course, Application.Run/Exit is specific to Windows Forms so this must be repeated for each message pump's API.

### Edge cases

So why don't you see `.GetAwaiter().OnCompleted(Application.Exit)` anywhere? Well, if the thing you are awaiting is not a Task—for example, if it's a ConfiguredTaskAwaitable from `task.ConfigureAwait(false)`—there is no guarantee which thread `Application.Exit` will execute on. That's what [this `else`](https://github.com/nunit/nunit/pull/2776/files#diff-308ac1319e4d291401e5ccd48a2b3651R129) handles.

The only other catch is explained (clearly, I hope) by [this comment](https://github.com/nunit/nunit/pull/2776/files#diff-308ac1319e4d291401e5ccd48a2b3651R106).

### Bonus details: What is a `SynchronizationContext` even

It's per-thread global state. It's the API which says very generally, "Here’s how to get back to the context you started from."

If you are awaiting an HTTP download, you've stopped executing on any threads at all. You've just left enough information behind so that, when the data arrives and the underlying async Windows API starts executing on a background thread, that background thread has enough information to know 1) where to stash that data and 2) what action to invoke to execute the next piece of the higher-level async method.

Problem: you can't always execute the next piece of the async method right away. We're on a background thread. if we executed the rest of the async method after the `await`, we might try to do something with UI and Windows Forms will throw a helpful exception because we're on the wrong thread.

So: when the UI thread gets to an `await` in your async method, and records where it is, and quits executing the async method so that it can go back to pumping messages, _rather than_ leaving the background thread an action which _directly_ executes the next part of the async method after the `await`, it leaves behind an action which calls the equivalent of `capturedSynchronizationContext.Post(_ => executeNextPartOfAsyncMethod.Invoke(), null);`.

 1. The background I/O thread executes the action it was given.
 2. The action contains ~`capturedSynchronizationContext.Post(_ => innerAction.Invoke(), null)`, so when the background thread executes it, `capturedSynchronizationContext` puts `innerAction` in a thread message queue.
 3. `Application.Run()`, in a galaxy far, far away, wakes up from waiting on the same queue, pulls out the message, and executes `innerAction`.

**Comment by jnm2** [comment]
@rprouse I really do want to make sure that if something happens to me, I've left behind enough information that the team feels like they can own this stuff. Did the above help answer any questions about why I wrote exactly what I wrote?

**Comment by jnm2** [comment]
@rprouse 

> I think @sharwell's comment about checking the threads is a good idea.

I meant to address in https://github.com/nunit/nunit/pull/2776/commits/38470e67b42cc91958de89f2c5a6e0e7a43da6a5. Is there maybe room for more checking?

File: src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs (hunk 9 above)
Comment (jnm2) [reply src/NUnitFramework/framework/Internal/MessagePumpStrategy.cs]: 😍 https://blogs.msdn.microsoft.com/visualstudio/2018/05/08/hyper-v-android-emulator-support/
