### PR TITLE
Return also protected and internal properties

### LINKED ISSUE #2465: Possible wrong properties are returned by reflection in ReflectionExtensions.cs
When debugging #2448 I noticed that the filtering of properties in `ApplyBindingFlags` has the same problem as filtering of methods in #2448. The documentation says
https://msdn.microsoft.com/en-us/library/kyaxdd3x(v=vs.110).aspx#Remarks 
> Specify BindingFlags.NonPublic to include non-public properties (that is, private, internal, and protected properties) in the search. Only protected and internal properties on base classes are returned; private properties on base classes are not returned.

But the code only returns private properties for `BindingFlags.NonPublic`
https://github.com/nunit/nunit/blob/6980e958df0a94a4969258f8ed35aaccedb9ff31/src/NUnitFramework/framework/Compatibility/ReflectionExtensions.cs#L346-L349

The solution to this can probably be done similar to #2448 (replacing `p.GetMethod.IsPrivate` with `!p.GetMethod.IsPublic`), so the main issue is to write some tests that capture the intended behaviour.

### PR DESCRIPTION
**Pull request by mikkelbu**
As the documentation states "Specify BindingFlags.NonPublic
to include non-public properties (that is, private, internal,
and protected properties) in the search.

Fixes #2465

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
@mikkelbu - Have you spotted this failed the appveyor CI build? 🙂

**Comment by mikkelbu** [comment]
@ChrisMaddock Nope. I made the PR and then went to bed :). The test that fails is `PropertyValue_ShadowingPropertyOfDifferentType` which was merge into master just before I made the PR, so probably I have run the tests locally before fetching the latest commits from master, and forgot to run the tests again. I'll take a look at it tonight.

File: src/NUnitFramework/framework/Compatibility/ReflectionExtensions.cs [hunk 1]
```diff
@@ -250,7 +250,9 @@ public static PropertyInfo GetProperty(this Type type, string name)
         /// <returns></returns>
         public static PropertyInfo GetProperty(this Type type, string name, BindingFlags flags)
         {
+            bool declaredOnly = flags.HasFlag(BindingFlags.DeclaredOnly);
             return type.GetRuntimeProperties()
+                .Where(prop => declaredOnly ? prop.DeclaringType.Equals(type) : true)
```
Comment (mikkelbu) [inline src/NUnitFramework/framework/Compatibility/ReflectionExtensions.cs]: I was considering writing this more succinctly as 
`.Where(prop => !declaredOnly || prop.DeclaringType.Equals(type))`
but chose the more verbose solution for readability (also I guess/hope that the compiler will generate the same IL).

Comment (ChrisMaddock) [reply src/NUnitFramework/framework/Compatibility/ReflectionExtensions.cs]: Good choice - I agree!

Comment (ChrisMaddock) [reply src/NUnitFramework/framework/Compatibility/ReflectionExtensions.cs]: Good choice - I agree!
