### PR TITLE
Unhandled exception handling

### LINKED ISSUE #5132: Thread.Abort() in Test causes "Test cancelled by user" result for NUnit 4.5.0
A test containing a call to Thread.Abort() seems to let the test result in "Test cancelled by user".
The test when debugging, keeps executing. There are no exceptions and it runs to finish, but the result becomes Test cancelled by user.
I have tested this against 4.4.0 and 4.5.0. The old Version has no issues.

I was able to reproduce it with this function called from test.

```
        public static void simplifyAbort()
        {
            var thread = new Thread(() => 
            {
                Thread.Sleep(1000);
            });
            thread.Start();
            thread.Join(500);
            thread.Abort();
        }
```

Thank you for your time.

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #5132 

Adds an attribute to ignore exception on .NET Framework for now.

In .NET Core it is not possible to ignore exceptions raised from other threads.
They can be caught for logging purposes, but not ignored.

.NET10 has a new API that allows ignoring exceptions again.

### CODE REVIEW

**Comment by manfred-brands** [comment]
All tests pass with `dotnet test` and inside Visual Studio.
NunitLite crashes with: `net462/nunitlite-runner.exe returned rc = -532462766`

**Review by OsirisTerje — APPROVED** [review]

File: src/NUnitFramework/framework/Internal/PropertyNames.cs [hunk 1]
```diff
@@ -119,6 +119,12 @@ public static class PropertyNames
         /// The optional Order the test will run in
         /// </summary>
         public const string Order = "Order";
+
+        /// <summary>
+        /// How to deal with exceptions raised on threads other than the main test thread that are not handled by the user code.
+        /// </summary>
+        public const string UnhandledExceptionHandling = "UnhandledExceptionHandling";
```
Comment (OsirisTerje) [inline src/NUnitFramework/framework/Internal/PropertyNames.cs:126]:
```suggestion
        public const string UnhandledExceptionHandling = nameof(UnhandledExceptionHandling);
```

**Comment by OsirisTerje** [comment]
Works for the repro:
image

Without the attribute, we no longer have a message that says "Cancelled by user", but the stacktrace of the thread crash (which is nice).  

▶️ I think we should include a short descriptive message too, like "Unhandled exception in worker thread".

image

> NunitLite crashes with: net462/nunitlite-runner.exe returned rc = -532462766

I believe you fixed this, right ?

▶️  So only thing missing is the typeof(ThreadAbortException) parameter (can't refind where you suggested that, but sure I did see it, and I liked that).

▶️ Also, we should allow ` [UnhandledExceptionHandling]`, using the default value (Error). 
As it is now, it will be either Error or Ignore, meaning we have skipped Cancelled.  Perhaps more correct ?

------UPDATE-----

There is actually no difference now between no attribute (the test result is Error), and with the attribute set to Error handling.  

So, it means we don't need to specify Ignore, because that is the only setting that now changes the behavior.
- Without the attribute  --> Error
- With the attribute --> Ignore

If we add in the type, it could mean that any exception of that type will be ignored, all others will be error.

That sounds correct to me, and is the same behavior we have for exceptions in the test thread itself.

**Comment by manfred-brands** [comment]
> > NunitLite crashes with: net462/nunitlite-runner.exe returned rc = -532462766

> I believe you fixed this, right ?

No. It crashes with 'Unhandled Exception:' message raised by .NET itself.
It is as if the Exception is thrown after NUnitLite thinks the tests have finished.
It almost seems like NUnitLite doesn't wait for the TearDown.

> ▶️ So only thing missing is the typeof(ThreadAbortException) parameter (can't refind where you suggested that, but sure I did see it, and I liked that).

Done.

> There is actually no difference now between no attribute (the test result is Error), and with the attribute set to Error handling.

There is now:

You can ignore all exceptions, except ArgumentException:

```csharp
        [UnhandledExceptionHandling(UnhandledExceptionHandling.Ignore)]
        [UnhandledExceptionHandling(UnhandledExceptionHandling.Error, typeof(ArgumentException))]
```

But if you say that is a made-up use-case, then we can change it to:
```csharp
        [IgnoreUnhandledExceptions]
        [IgnoreUnhandledExceptions(typeof(ThreadAbortException))]
```

**Comment by OsirisTerje** [comment]
> No. It crashes with 'Unhandled Exception:' message raised by .NET itself.
It is as if the Exception is thrown after NUnitLite thinks the tests have finished.
It almost seems like NUnitLite doesn't wait for the TearDown.

It works on my machine.......

That is, you mean when running the `build --target test` on the nunit itself, right?

**Comment by manfred-brands** [comment]
> > No. It crashes with 'Unhandled Exception:' message raised by .NET itself.
> > It is as if the Exception is thrown after NUnitLite thinks the tests have finished.
> > It almost seems like NUnitLite doesn't wait for the TearDown.
> 
> It works on my machine.......
> 
> That is, you mean when running the `build --target test` on the nunit itself, right?

Did you comment out the ` [Explicit("When running in Nunit-Lite it seems to crash the process.")]`?

It fails on mine using `./build.cmd --target=TestNetFramework`

**Comment by OsirisTerje** [comment]
Yes, that fails here too, and works in VS.

So this is something NUnitLite does, we can fix that later I think.
